// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newAirbnbListingCmd() *cobra.Command {
	var p_adultsVar int
	var p_checkInVar string
	var p_checkOutVar string
	var p_childrenVar int
	var p_infantsVar int
	var p_locationVar string
	var p_neLatVar float64
	var p_neLngVar float64
	var p_nextPageTokenVar string
	var p_petsVar int
	var p_swLatVar float64
	var p_swLngVar float64

	cmd := &cobra.Command{
		Use:   "airbnb-listing",
		Short: "Airbnb Listing Scraper API  (5 credits/call)",
		Long:  "The Airbnb Listing Scraper API allows users to retrieve listings from Airbnb based on location and check-in/check-out dates.\n\nEndpoint: GET https://api.hasdata.com/scrape/airbnb/listing\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("adults") {
				params.Set("adults", strconv.Itoa(p_adultsVar))
			}
			params.Set("checkIn", p_checkInVar)
			if c.Flags().Changed("check-out") {
				params.Set("checkOut", p_checkOutVar)
			}
			if c.Flags().Changed("children") {
				params.Set("children", strconv.Itoa(p_childrenVar))
			}
			if c.Flags().Changed("infants") {
				params.Set("infants", strconv.Itoa(p_infantsVar))
			}
			if c.Flags().Changed("location") {
				params.Set("location", p_locationVar)
			}
			if c.Flags().Changed("ne-lat") {
				params.Set("neLat", strconv.FormatFloat(p_neLatVar, 'f', -1, 64))
			}
			if c.Flags().Changed("ne-lng") {
				params.Set("neLng", strconv.FormatFloat(p_neLngVar, 'f', -1, 64))
			}
			if c.Flags().Changed("next-page-token") {
				params.Set("nextPageToken", p_nextPageTokenVar)
			}
			if c.Flags().Changed("pets") {
				params.Set("pets", strconv.Itoa(p_petsVar))
			}
			if c.Flags().Changed("sw-lat") {
				params.Set("swLat", strconv.FormatFloat(p_swLatVar, 'f', -1, 64))
			}
			if c.Flags().Changed("sw-lng") {
				params.Set("swLng", strconv.FormatFloat(p_swLngVar, 'f', -1, 64))
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/airbnb/listing", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().IntVar(&p_adultsVar, "adults", 0, "adults Number of Adults: Number of adults.\n")
	cmd.Flags().StringVar(&p_checkInVar, "check-in", "2026-01-01", "checkIn Check-in Date: The check-in date for the listings. (required)")
	_ = cmd.MarkFlagRequired("check-in")
	cmd.Flags().StringVar(&p_checkOutVar, "check-out", "2026-01-05", "checkOut Check-out Date: The check-out date for the listings.")
	cmd.Flags().IntVar(&p_childrenVar, "children", 0, "children Number of Children: Number of children.\n")
	cmd.Flags().IntVar(&p_infantsVar, "infants", 0, "infants Number of Infants: Number of infants.\n")
	cmd.Flags().StringVar(&p_locationVar, "location", "", "location Location: The location to search for listings. Required unless a full map bounding box (neLat, neLng, swLat, swLng) is provided.")
	cmd.Flags().Float64Var(&p_neLatVar, "ne-lat", 40.8, "neLat North-East Latitude: North-east corner latitude of the map bounding box. When all four bounding-box coordinates are provided, listings are searched within the box instead of by location.\n")
	cmd.Flags().Float64Var(&p_neLngVar, "ne-lng", -73.9, "neLng North-East Longitude: North-east corner longitude of the map bounding box.\n")
	cmd.Flags().StringVar(&p_nextPageTokenVar, "next-page-token", "", "nextPageToken Next Page Token: The token used to retrieve the next page of results.")
	cmd.Flags().IntVar(&p_petsVar, "pets", 0, "pets Number of Pets: Number of pets.\n")
	cmd.Flags().Float64Var(&p_swLatVar, "sw-lat", 40.6, "swLat South-West Latitude: South-west corner latitude of the map bounding box.\n")
	cmd.Flags().Float64Var(&p_swLngVar, "sw-lng", -74.1, "swLng South-West Longitude: South-west corner longitude of the map bounding box.\n")

	return cmd
}

func init() {
	RegisterAPICommand("airbnb", "Airbnb", newAirbnbListingCmd())
}
