// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newFacebookProfileCmd() *cobra.Command {
	var p_handleVar string
	var p_languageVar string
	var p_nextPageTokenVar string

	cmd := &cobra.Command{
		Use:   "facebook-profile",
		Short: "Facebook Profile Scraper API  (10 credits/call)",
		Long:  "The Facebook Profile Scraper API lets you retrieve public information from a Facebook page or profile by its handle, together with the posts on the page. It returns name, category, bio, exact likes and talking-about counts, followers and following, website, phone, the page owner, profile and cover photos, the photo tiles, and the posts with their text, media, reaction breakdown, comment and share counts.\n\nEndpoint: GET https://api.hasdata.com/scrape/facebook/profile\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("language") {
				if err := validateEnumString("language", p_languageVar, []string{"ar", "bn", "cs", "da", "de", "el", "en", "es", "fi", "fil", "fr", "he", "hi", "hu", "id", "it", "ja", "ko", "ms", "nb", "nl", "pl", "pt", "ro", "ru", "sv", "th", "tr", "uk", "vi", "zh-hans", "zh-hant"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("handle", p_handleVar)
			if c.Flags().Changed("language") {
				params.Set("language", p_languageVar)
			}
			if c.Flags().Changed("next-page-token") {
				params.Set("nextPageToken", p_nextPageTokenVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/facebook/profile", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_handleVar, "handle", "nike", "handle Facebook Handle: The Facebook username of the page or profile you want to scrape, with or without the `@` symbol, or its numeric profile id (the `id` of a `profile.php?id=…` URL), e.g. `nike` or `61550916779928`. Groups and private personal accounts are not supported. (required)")
	_ = cmd.MarkFlagRequired("handle")
	cmd.Flags().StringVar(&p_languageVar, "language", "", "language Language: Language the page is rendered in. Facebook serves a page in the language of the request, so this changes the localised strings (`followersCount`, `followingCount`, `category`) while the exact figures (`likesCount`, `talkingAboutCount`) stay numeric in every language. [allowed: ar|bn|cs|da|de|el|en|es|fi|fil|fr|he|hi|hu|id|it|ja|ko|ms|nb|nl|pl|pt|ro|ru|sv|th|tr|uk|vi|zh-hans|zh-hant]")
	_ = cmd.RegisterFlagCompletionFunc("language", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"ar", "bn", "cs", "da", "de", "el", "en", "es", "fi", "fil", "fr", "he", "hi", "hu", "id", "it", "ja", "ko", "ms", "nb", "nl", "pl", "pt", "ro", "ru", "sv", "th", "tr", "uk", "vi", "zh-hans", "zh-hant"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_nextPageTokenVar, "next-page-token", "", "nextPageToken Next Page Token: Token from the `pagination.nextPageToken` field of a previous response; the page it leads to is reported as `pagination.nextPage`. Each paginated request returns the next three posts of the feed and a fresh token; the token is absent once the feed ends. Every request is billed separately.")

	return cmd
}

func init() {
	RegisterAPICommand("social", "Social", newFacebookProfileCmd())
}
