// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newYelpSearchCmd() *cobra.Command {
	var p_domainVar string
	var p_keywordVar string
	var p_lVar string
	var p_locationVar string
	var p_startVar int

	cmd := &cobra.Command{
		Use:   "yelp-search",
		Short: "Yelp Search API  (5 credits/call)",
		Long:  "The Yelp Search API allows users to get results from the Yelp search page. This API enables searching for businesses by keyword and location.\n\nEndpoint: GET https://api.hasdata.com/scrape/yelp/search\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("domain") {
				if err := validateEnumString("domain", p_domainVar, []string{"www.yelp.com", "www.yelp.co.uk", "www.yelp.ca", "www.yelp.com.au", "ms.yelp.my", "www.yelp.cz", "www.yelp.dk", "www.yelp.de", "www.yelp.at", "de.yelp.ch", "en.yelp.be", "en.yelp.com.hk", "en.yelp.my", "www.yelp.co.nz", "en.yelp.com.ph", "www.yelp.ie", "www.yelp.com.sg", "en.yelp.ch", "www.yelp.com.ar", "www.yelp.cl", "www.yelp.es", "www.yelp.com.mx", "fil.yelp.com.ph", "fr.yelp.be", "fr.yelp.ca", "www.yelp.fr", "fr.yelp.ch", "www.yelp.it", "it.yelp.ch", "nl.yelp.be", "www.yelp.nl", "www.yelp.no", "www.yelp.pl", "www.yelp.com.br", "www.yelp.pt", "fi.yelp.fi", "sv.yelp.fi", "www.yelp.com.tr", "www.yelp.co.jp", "zh.yelp.com.hk", "www.yelp.com.tw"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("domain") {
				params.Set("domain", p_domainVar)
			}
			params.Set("keyword", p_keywordVar)
			if c.Flags().Changed("l") {
				params.Set("l", p_lVar)
			}
			params.Set("location", p_locationVar)
			if c.Flags().Changed("start") {
				params.Set("start", strconv.Itoa(p_startVar))
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/yelp/search", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_domainVar, "domain", "", "domain Domain: Yelp domain to use. Default is `www.yelp.com`. [allowed: www.yelp.com|www.yelp.co.uk|www.yelp.ca|www.yelp.com.au|ms.yelp.my|www.yelp.cz|www.yelp.dk|www.yelp.de|www.yelp.at|de.yelp.ch|en.yelp.be|en.yelp.com.hk|en.yelp.my|www.yelp.co.nz|en.yelp.com.ph|www.yelp.ie|www.yelp.com.sg|en.yelp.ch|www.yelp.com.ar|www.yelp.cl|www.yelp.es|www.yelp.com.mx|fil.yelp.com.ph|fr.yelp.be|fr.yelp.ca|www.yelp.fr|fr.yelp.ch|www.yelp.it|it.yelp.ch|nl.yelp.be|www.yelp.nl|www.yelp.no|www.yelp.pl|www.yelp.com.br|www.yelp.pt|fi.yelp.fi|sv.yelp.fi|www.yelp.com.tr|www.yelp.co.jp|zh.yelp.com.hk|www.yelp.com.tw]")
	_ = cmd.RegisterFlagCompletionFunc("domain", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"www.yelp.com", "www.yelp.co.uk", "www.yelp.ca", "www.yelp.com.au", "ms.yelp.my", "www.yelp.cz", "www.yelp.dk", "www.yelp.de", "www.yelp.at", "de.yelp.ch", "en.yelp.be", "en.yelp.com.hk", "en.yelp.my", "www.yelp.co.nz", "en.yelp.com.ph", "www.yelp.ie", "www.yelp.com.sg", "en.yelp.ch", "www.yelp.com.ar", "www.yelp.cl", "www.yelp.es", "www.yelp.com.mx", "fil.yelp.com.ph", "fr.yelp.be", "fr.yelp.ca", "www.yelp.fr", "fr.yelp.ch", "www.yelp.it", "it.yelp.ch", "nl.yelp.be", "www.yelp.nl", "www.yelp.no", "www.yelp.pl", "www.yelp.com.br", "www.yelp.pt", "fi.yelp.fi", "sv.yelp.fi", "www.yelp.com.tr", "www.yelp.co.jp", "zh.yelp.com.hk", "www.yelp.com.tw"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_keywordVar, "keyword", "McDonald's", "keyword Search Query: The search term for which to get the search results. (required)")
	_ = cmd.MarkFlagRequired("keyword")
	cmd.Flags().StringVar(&p_lVar, "l", "", "l Area: Parameter defines the distance or map radius for the search results. For example: `g:-95.2486,29.8496,-95.4277,29.6324`.\n")
	cmd.Flags().StringVar(&p_locationVar, "location", "New York, NY", "location Location: The location where to search for businesses with the given keyword. (required)")
	_ = cmd.MarkFlagRequired("location")
	cmd.Flags().IntVar(&p_startVar, "start", 0, "start Result Offset: Result offset for pagination (e.g., 0 for the first page, 10 for the 2nd page, etc.).")

	return cmd
}

func init() {
	RegisterAPICommand("business", "Business", newYelpSearchCmd())
}
