// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newGoogleImmersiveProductCmd() *cobra.Command {
	var p_moreStoresVar bool
	var p_nextPageTokenVar string
	var p_pageTokenVar string

	cmd := &cobra.Command{
		Use:   "google-immersive-product",
		Short: "Google Immersive Product API  (5 credits/call)",
		Long:  "With the Google Immersive Product API, you can fetch extended product information from the \"Immersive Product\" block, which displays a pop-up with complete details when clicked.\n\nEndpoint: GET https://api.hasdata.com/scrape/google/immersive-product\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("more-stores") {
				params.Set("moreStores", strconv.FormatBool(p_moreStoresVar))
			}
			if c.Flags().Changed("next-page-token") {
				params.Set("nextPageToken", p_nextPageTokenVar)
			}
			params.Set("pageToken", p_pageTokenVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/google/immersive-product", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().BoolVar(&p_moreStoresVar, "more-stores", false, "moreStores Fetch More Stores: Fetch additional store results in a single search. By default it returns 3–5 stores, and when true it returns up to 13 or the maximum available for the product.")
	cmd.Flags().StringVar(&p_nextPageTokenVar, "next-page-token", "", "nextPageToken Stores Next Page Token: Token used to retrieve the next page of store results.")
	cmd.Flags().StringVar(&p_pageTokenVar, "page-token", "eyJlaSI6IjE0NXFaN0NlS3U3bjVOb1BtcmpTOFFvIiwicHJvZHVjdGlkIjoiIiwiY2F0YWxvZ2lkIjoiMTY5MTQ4Nzc2MjUyODA5Nzc4NjUiLCJoZWFkbGluZU9mZmVyRG9jaWQiOiIzMjM4MjI0ODQ0NjI0OTEyMTY5IiwiaW1hZ2VEb2NpZCI6IjQ3Njc0OTkxNTkwNjMyNzkxNCIsInJkcyI6IlBDXzMyNDU0NzY0MDA4MzM1NTE5NDh8UFJPRF9QQ18zMjQ1NDc2NDAwODMzNTUxOTQ4IiwicXVlcnkiOiIrQ29mZmVlIiwiZ3BjaWQiOiIzMjQ1NDc2NDAwODMzNTUxOTQ4IiwibWlkIjoiNTc2NDYyNjEyMjgwMTMwNDgxIiwicHZ0IjoiaGciLCJ1dWxlIjpudWxsfQ==", "pageToken Page Token: Token for displaying more product info in the Google immersive pop-up, available in the Google Shopping API response as the `immersiveProductPageToken` property. (required)")
	_ = cmd.MarkFlagRequired("page-token")

	return cmd
}

func init() {
	RegisterAPICommand("google_serp", "Google SERP", newGoogleImmersiveProductCmd())
}
