// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newGoogleHotelsCmd() *cobra.Command {
	var p_adultsVar int
	var p_amenityVar []string
	var p_bathroomsVar int
	var p_bedroomsVar int
	var p_brandsVar string
	var p_checkInDateVar string
	var p_checkOutDateVar string
	var p_childrenVar int
	var p_childrenAgesVar string
	var p_currencyVar string
	var p_ecoCertifiedVar bool
	var p_freeCancellationVar bool
	var p_glVar string
	var p_hlVar string
	var p_hotelClassVar string
	var p_maxPriceVar float64
	var p_minPriceVar float64
	var p_nextPageTokenVar string
	var p_propertyTokenVar string
	var p_propertyTypeVar []string
	var p_qVar string
	var p_ratingVar string
	var p_sortByVar string
	var p_specialOffersVar bool
	var p_vacationRentalsVar bool

	cmd := &cobra.Command{
		Use:   "google-hotels",
		Short: "Google Hotels API  (10 credits/call)",
		Long:  "The Google Hotels API provides real-time access to structured Google Hotels search results, including property listings, prices, ratings, amenities, and pagination.\n\nEndpoint: GET https://api.hasdata.com/scrape/google/hotels\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("amenity") {
				if err := validateEnumStringSlice("amenity", p_amenityVar, []string{"hotelFreeParking", "hotelParking", "hotelIndoorPool", "hotelOutdoorPool", "hotelPool", "hotelFitnessCenter", "hotelRestaurant", "hotelFreeBreakfast", "hotelSpa", "hotelBeachAccess", "hotelChildFriendly", "hotelBar", "hotelPetFriendly", "hotelRoomService", "hotelFreeWifi", "hotelAirConditioned", "hotelAllInclusive", "hotelWheelchairAccessible", "hotelEvCharger", "rentalHotTub", "rentalAirConditioned", "rentalOutdoorGrill", "rentalFireplace", "rentalPatioOrDeck", "rentalKitchen", "rentalFitnessCenter", "rentalCrib", "rentalBeachAccess", "rentalKidFriendly", "rentalPetFriendly", "rentalFreeWifi", "rentalPool"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("property-type") {
				if err := validateEnumStringSlice("property-type", p_propertyTypeVar, []string{"hotelBeach", "hotelBoutique", "hotelHostel", "hotelInn", "hotelMotel", "hotelResort", "hotelSpa", "hotelBedAndBreakfast", "hotelOther", "hotelAparthotel", "hotelMinshuku", "hotelJapaneseBusiness", "hotelRyokan", "rentalApartment", "rentalBungalow", "rentalCabin", "rentalChalet", "rentalCottage", "rentalGite", "rentalHolidayVillage", "rentalHouse", "rentalHouseboat", "rentalVilla", "rentalOther", "rentalAparthotel"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("rating") {
				if err := validateEnumString("rating", p_ratingVar, []string{"threePointFivePlus", "fourPlus", "fourPointFivePlus"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("sort-by") {
				if err := validateEnumString("sort-by", p_sortByVar, []string{"lowestPrice", "highestRating", "mostReviewed"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("adults") {
				params.Set("adults", strconv.Itoa(p_adultsVar))
			}
			if c.Flags().Changed("amenity") {
				for _, v := range p_amenityVar {
					params.Add("amenity"+"[]", v)
				}
			}
			if c.Flags().Changed("bathrooms") {
				params.Set("bathrooms", strconv.Itoa(p_bathroomsVar))
			}
			if c.Flags().Changed("bedrooms") {
				params.Set("bedrooms", strconv.Itoa(p_bedroomsVar))
			}
			if c.Flags().Changed("brands") {
				params.Set("brands", p_brandsVar)
			}
			params.Set("checkInDate", p_checkInDateVar)
			params.Set("checkOutDate", p_checkOutDateVar)
			if c.Flags().Changed("children") {
				params.Set("children", strconv.Itoa(p_childrenVar))
			}
			if c.Flags().Changed("children-ages") {
				params.Set("childrenAges", p_childrenAgesVar)
			}
			if c.Flags().Changed("currency") {
				params.Set("currency", p_currencyVar)
			}
			if c.Flags().Changed("eco-certified") {
				params.Set("ecoCertified", strconv.FormatBool(p_ecoCertifiedVar))
			}
			if c.Flags().Changed("free-cancellation") {
				params.Set("freeCancellation", strconv.FormatBool(p_freeCancellationVar))
			}
			if c.Flags().Changed("gl") {
				params.Set("gl", p_glVar)
			}
			if c.Flags().Changed("hl") {
				params.Set("hl", p_hlVar)
			}
			if c.Flags().Changed("hotel-class") {
				params.Set("hotelClass", p_hotelClassVar)
			}
			if c.Flags().Changed("max-price") {
				params.Set("maxPrice", strconv.FormatFloat(p_maxPriceVar, 'f', -1, 64))
			}
			if c.Flags().Changed("min-price") {
				params.Set("minPrice", strconv.FormatFloat(p_minPriceVar, 'f', -1, 64))
			}
			if c.Flags().Changed("next-page-token") {
				params.Set("nextPageToken", p_nextPageTokenVar)
			}
			if c.Flags().Changed("property-token") {
				params.Set("propertyToken", p_propertyTokenVar)
			}
			if c.Flags().Changed("property-type") {
				for _, v := range p_propertyTypeVar {
					params.Add("propertyType"+"[]", v)
				}
			}
			params.Set("q", p_qVar)
			if c.Flags().Changed("rating") {
				params.Set("rating", p_ratingVar)
			}
			if c.Flags().Changed("sort-by") {
				params.Set("sortBy", p_sortByVar)
			}
			if c.Flags().Changed("special-offers") {
				params.Set("specialOffers", strconv.FormatBool(p_specialOffersVar))
			}
			if c.Flags().Changed("vacation-rentals") {
				params.Set("vacationRentals", strconv.FormatBool(p_vacationRentalsVar))
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/google/hotels", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().IntVar(&p_adultsVar, "adults", 0, "adults Adults: Number of adult guests (1-6).\n")
	cmd.Flags().StringSliceVar(&p_amenityVar, "amenity", nil, "amenity[] Amenity: List of amenities to filter by (e.g., `hotelFreeWifi,hotelPool`).\n\nValues prefixed `hotel*` apply when searching hotels (the default mode). Values prefixed `rental*` apply when `vacationRentals=true`.\n\nThe two sets are disjoint because Google Hotels exposes different amenity catalogs for each mode — pass values matching the mode you're querying.\n")
	_ = cmd.RegisterFlagCompletionFunc("amenity", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"hotelFreeParking", "hotelParking", "hotelIndoorPool", "hotelOutdoorPool", "hotelPool", "hotelFitnessCenter", "hotelRestaurant", "hotelFreeBreakfast", "hotelSpa", "hotelBeachAccess", "hotelChildFriendly", "hotelBar", "hotelPetFriendly", "hotelRoomService", "hotelFreeWifi", "hotelAirConditioned", "hotelAllInclusive", "hotelWheelchairAccessible", "hotelEvCharger", "rentalHotTub", "rentalAirConditioned", "rentalOutdoorGrill", "rentalFireplace", "rentalPatioOrDeck", "rentalKitchen", "rentalFitnessCenter", "rentalCrib", "rentalBeachAccess", "rentalKidFriendly", "rentalPetFriendly", "rentalFreeWifi", "rentalPool"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().IntVar(&p_bathroomsVar, "bathrooms", 0, "bathrooms Bathrooms: Minimum number of bathrooms (vacation rentals only).\n")
	cmd.Flags().IntVar(&p_bedroomsVar, "bedrooms", 0, "bedrooms Bedrooms: Minimum number of bedrooms (vacation rentals only).\n")
	cmd.Flags().StringVar(&p_brandsVar, "brands", "", "brands Brands: Comma-separated list of brand IDs to filter by. Brand IDs are returned in the response under `brands` for the same query.\n")
	cmd.Flags().StringVar(&p_checkInDateVar, "check-in-date", "2026-08-15", "checkInDate Check-in Date: The check-in date in 'yyyy-MM-dd' format.\n (required)")
	_ = cmd.MarkFlagRequired("check-in-date")
	cmd.Flags().StringVar(&p_checkOutDateVar, "check-out-date", "2026-08-20", "checkOutDate Check-out Date: The check-out date in 'yyyy-MM-dd' format.\n (required)")
	_ = cmd.MarkFlagRequired("check-out-date")
	cmd.Flags().IntVar(&p_childrenVar, "children", 0, "children Children: Number of child guests (1-5). Total guests (adults + children) cannot exceed 6.\n")
	cmd.Flags().StringVar(&p_childrenAgesVar, "children-ages", "", "childrenAges Children Ages: Comma-separated list of children ages (e.g., `5,8,12`). Must match the number of children.\n")
	cmd.Flags().StringVar(&p_currencyVar, "currency", "", "currency Currency: Parameter defines the currency of the returned prices")
	cmd.Flags().BoolVar(&p_ecoCertifiedVar, "eco-certified", false, "ecoCertified Eco-certified: Show only eco-certified properties.\n")
	cmd.Flags().BoolVar(&p_freeCancellationVar, "free-cancellation", false, "freeCancellation Free Cancellation: Show only properties offering free cancellation.\n")
	cmd.Flags().StringVar(&p_glVar, "gl", "", "gl Country: The two-letter country code for the country you want to limit the search to.")
	cmd.Flags().StringVar(&p_hlVar, "hl", "", "hl Language: The two-letter language code for the language you want to use for the search.")
	cmd.Flags().StringVar(&p_hotelClassVar, "hotel-class", "", "hotelClass Hotel Class: Comma-separated list of hotel star classes to include (e.g., `2,3,4,5`).\n")
	cmd.Flags().Float64Var(&p_maxPriceVar, "max-price", 0, "maxPrice Maximum Price: Maximum price per night, in the selected currency.\n")
	cmd.Flags().Float64Var(&p_minPriceVar, "min-price", 0, "minPrice Minimum Price: Minimum price per night, in the selected currency.\n")
	cmd.Flags().StringVar(&p_nextPageTokenVar, "next-page-token", "", "nextPageToken Next Page Token: Token to fetch the next page of hotel results. Returned in the `pagination` field of a previous response.\n")
	cmd.Flags().StringVar(&p_propertyTokenVar, "property-token", "", "propertyToken Property Token: Token used to retrieve details for a specific property. Returned in each property in the results.\n")
	cmd.Flags().StringSliceVar(&p_propertyTypeVar, "property-type", nil, "propertyType[] Property Type: List of property types to filter by (e.g., `hotelResort,hotelMotel`).\n\nValues prefixed `hotel*` apply when searching hotels (the default mode). Values prefixed `rental*` apply when `vacationRentals=true`.\n\nThe two sets are disjoint because Google Hotels exposes different property-type catalogs for each mode — pass values matching the mode you're querying.\n")
	_ = cmd.RegisterFlagCompletionFunc("property-type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"hotelBeach", "hotelBoutique", "hotelHostel", "hotelInn", "hotelMotel", "hotelResort", "hotelSpa", "hotelBedAndBreakfast", "hotelOther", "hotelAparthotel", "hotelMinshuku", "hotelJapaneseBusiness", "hotelRyokan", "rentalApartment", "rentalBungalow", "rentalCabin", "rentalChalet", "rentalCottage", "rentalGite", "rentalHolidayVillage", "rentalHouse", "rentalHouseboat", "rentalVilla", "rentalOther", "rentalAparthotel"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_qVar, "q", "Hotels in New York", "q Search Query: The search query for Google Hotels (e.g., a city, neighborhood, or hotel name).\n (required)")
	_ = cmd.MarkFlagRequired("q")
	cmd.Flags().StringVar(&p_ratingVar, "rating", "", "rating Minimum Rating: Filter by minimum overall guest rating. Options:\n\n  - `threePointFivePlus` — 3.5 stars or higher\n  - `fourPlus` — 4.0 stars or higher\n  - `fourPointFivePlus` — 4.5 stars or higher\n [allowed: threePointFivePlus|fourPlus|fourPointFivePlus]")
	_ = cmd.RegisterFlagCompletionFunc("rating", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"threePointFivePlus", "fourPlus", "fourPointFivePlus"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_sortByVar, "sort-by", "", "sortBy Sort By: Sort hotel results. Options:\n\n  - `lowestPrice` — lowest price\n  - `highestRating` — highest rating\n  - `mostReviewed` — most reviewed\n [allowed: lowestPrice|highestRating|mostReviewed]")
	_ = cmd.RegisterFlagCompletionFunc("sort-by", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"lowestPrice", "highestRating", "mostReviewed"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().BoolVar(&p_specialOffersVar, "special-offers", false, "specialOffers Special Offers: Show only properties with special offers.\n")
	cmd.Flags().BoolVar(&p_vacationRentalsVar, "vacation-rentals", false, "vacationRentals Vacation Rentals: Search vacation rentals instead of hotels.\n")

	return cmd
}

func init() {
	RegisterAPICommand("google_travel", "Google Travel", newGoogleHotelsCmd())
}
