// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newInstagramPostsCmd() *cobra.Command {
	var p_handleVar string
	var p_limitVar int
	var p_nextPageTokenVar string

	cmd := &cobra.Command{
		Use:   "instagram-posts",
		Short: "Instagram Posts Scraper API  (5 credits/call)",
		Long:  "The Instagram Posts Scraper API lets you retrieve the latest posts of a public Instagram account using its handle. It returns posts with captions, hashtags, mentions, likes, comments, and plays counts, image and video URLs, and timestamps, with token-based pagination for retrieving older posts.\n\nEndpoint: GET https://api.hasdata.com/scrape/instagram/posts\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("handle", p_handleVar)
			if c.Flags().Changed("limit") {
				params.Set("limit", strconv.Itoa(p_limitVar))
			}
			if c.Flags().Changed("next-page-token") {
				params.Set("nextPageToken", p_nextPageTokenVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/instagram/posts", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_handleVar, "handle", "hasdatadotcom", "handle Instagram Handle: The Instagram username of the account whose posts you want to scrape, without the `@` symbol. (required)")
	_ = cmd.MarkFlagRequired("handle")
	cmd.Flags().IntVar(&p_limitVar, "limit", 12, "limit Results Limit: The maximum number of posts to retrieve per request. Defaults to 12.")
	cmd.Flags().StringVar(&p_nextPageTokenVar, "next-page-token", "", "nextPageToken Next Page Token: Defines the next page token. It is used for retrieving the next page results. Use the `nextPageToken` value returned by the previous response.")

	return cmd
}

func init() {
	RegisterAPICommand("social", "Social", newInstagramPostsCmd())
}
