// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newWalmartSearchCmd() *cobra.Command {
	var p_catIdVar string
	var p_deliveryTypeVar string
	var p_domainVar string
	var p_facetVar string
	var p_languageVar string
	var p_maxPriceVar float64
	var p_minPriceVar float64
	var p_pageVar int
	var p_qVar string
	var p_sortVar string
	var p_urlVar string

	cmd := &cobra.Command{
		Use:   "walmart-search",
		Short: "Walmart Search Scraper API  (10 credits/call)",
		Long:  "The Walmart Search Scraper API allows users to get search results from Walmart based on the specified query, category and storefront. This API enables searching for products on Walmart.\n\nEndpoint: GET https://api.hasdata.com/scrape/walmart/search\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("delivery-type") {
				if err := validateEnumString("delivery-type", p_deliveryTypeVar, []string{"shipping", "pickup"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("domain") {
				if err := validateEnumString("domain", p_domainVar, []string{"walmart.com", "walmart.ca"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("language") {
				if err := validateEnumString("language", p_languageVar, []string{"en", "es", "fr"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("sort") {
				if err := validateEnumString("sort", p_sortVar, []string{"bestMatch", "priceLowToHigh", "priceHighToLow", "bestseller", "highlyRated", "newArrivals"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("cat-id") {
				params.Set("catId", p_catIdVar)
			}
			if c.Flags().Changed("delivery-type") {
				params.Set("deliveryType", p_deliveryTypeVar)
			}
			if c.Flags().Changed("domain") {
				params.Set("domain", p_domainVar)
			}
			if c.Flags().Changed("facet") {
				params.Set("facet", p_facetVar)
			}
			if c.Flags().Changed("language") {
				params.Set("language", p_languageVar)
			}
			if c.Flags().Changed("max-price") {
				params.Set("maxPrice", strconv.FormatFloat(p_maxPriceVar, 'f', -1, 64))
			}
			if c.Flags().Changed("min-price") {
				params.Set("minPrice", strconv.FormatFloat(p_minPriceVar, 'f', -1, 64))
			}
			if c.Flags().Changed("page") {
				params.Set("page", strconv.Itoa(p_pageVar))
			}
			if c.Flags().Changed("q") {
				params.Set("q", p_qVar)
			}
			if c.Flags().Changed("sort") {
				params.Set("sort", p_sortVar)
			}
			if c.Flags().Changed("url") {
				params.Set("url", p_urlVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/walmart/search", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_catIdVar, "cat-id", "", "catId Category ID: Walmart category id, taken from a category URL (for example 976759_1086446_1229651). Combine it with q to search inside a category, or send it alone to browse the whole category. Required unless q is provided.")
	cmd.Flags().StringVar(&p_deliveryTypeVar, "delivery-type", "", "deliveryType Delivery Type: Keep only the products available with the selected fulfillment method. [allowed: shipping|pickup]")
	_ = cmd.RegisterFlagCompletionFunc("delivery-type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"shipping", "pickup"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_domainVar, "domain", "", "domain Domain: Walmart storefront to search. Each storefront has its own catalog, prices and currency. Default is walmart.com. [allowed: walmart.com|walmart.ca]")
	_ = cmd.RegisterFlagCompletionFunc("domain", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"walmart.com", "walmart.ca"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_facetVar, "facet", "", "facet Facet Filter: Walmart filter in the name:value form, for example brand:Great Value. Every value available for a query is listed in the facets block of the response, each one carrying the exact string to send back here, so a first unfiltered request tells you what can be filtered on. Combine several filters with a double pipe: brand:Great Value||retailer_type:Walmart.")
	cmd.Flags().StringVar(&p_languageVar, "language", "en", "language Language: Language of the results. Availability depends on the storefront - walmart.com serves en and es, walmart.ca serves en and fr. A language the storefront does not support falls back to its default. [allowed: en|es|fr]")
	_ = cmd.RegisterFlagCompletionFunc("language", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"en", "es", "fr"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().Float64Var(&p_maxPriceVar, "max-price", 0, "maxPrice Maximum Price: Upper bound of the price range, in the storefront currency.")
	cmd.Flags().Float64Var(&p_minPriceVar, "min-price", 0, "minPrice Minimum Price: Lower bound of the price range, in the storefront currency.")
	cmd.Flags().IntVar(&p_pageVar, "page", 0, "page Page Number: Page number for pagination (e.g., 1 for the first page, 2 for the second page, etc.). Walmart stops serving results after roughly page 10, returning an empty page beyond that.")
	cmd.Flags().StringVar(&p_qVar, "q", "coffee", "q Search Query: The search term for which to get the search results. It can be omitted only when catId is provided, to browse a whole category instead of searching.")
	cmd.Flags().StringVar(&p_sortVar, "sort", "bestMatch", "sort Sort By: The sorting option for the search results. [allowed: bestMatch|priceLowToHigh|priceHighToLow|bestseller|highlyRated|newArrivals]")
	_ = cmd.RegisterFlagCompletionFunc("sort", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"bestMatch", "priceLowToHigh", "priceHighToLow", "bestseller", "highlyRated", "newArrivals"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_urlVar, "url", "", "url Search URL: A full Walmart search or category URL to scrape as is. When provided, it overrides q, catId and the other search parameters, and the storefront is taken from the URL itself.")

	return cmd
}

func init() {
	RegisterAPICommand("ecommerce", "E-commerce", newWalmartSearchCmd())
}
