// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newGoogleScholarCmd() *cobra.Command {
	var p_asRrVar float64
	var p_asSdtVar string
	var p_asVisVar float64
	var p_asYhiVar int
	var p_asYloVar int
	var p_citesVar string
	var p_clusterVar string
	var p_filterVar float64
	var p_hlVar string
	var p_lrVar []string
	var p_numVar int
	var p_qVar string
	var p_safeVar string
	var p_scisbdVar int
	var p_startVar int

	cmd := &cobra.Command{
		Use:   "google-scholar",
		Short: "Google Scholar API  (5 credits/call)",
		Long:  "Provides real-time access to Google Scholar search results, including papers, citations, and related scholarly metadata.\n\nEndpoint: GET https://api.hasdata.com/scrape/google/scholar\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("lr") {
				if err := validateEnumStringSlice("lr", p_lrVar, []string{"lang_ar", "lang_hy", "lang_bg", "lang_ca", "lang_cs", "lang_da", "lang_de", "lang_el", "lang_en", "lang_es", "lang_et", "lang_tl", "lang_fi", "lang_fr", "lang_hr", "lang_hi", "lang_hu", "lang_id", "lang_is", "lang_it", "lang_iw", "lang_he", "lang_ja", "lang_ko", "lang_lt", "lang_lv", "lang_nl", "lang_no", "lang_fa", "lang_pl", "lang_pt", "lang_ro", "lang_ru", "lang_sk", "lang_sl", "lang_sr", "lang_sv", "lang_th", "lang_tr", "lang_uk", "lang_vi", "lang_zh-CN", "lang_zh-TW"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("safe") {
				if err := validateEnumString("safe", p_safeVar, []string{"active", "off"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("as-rr") {
				params.Set("asRr", strconv.FormatFloat(p_asRrVar, 'f', -1, 64))
			}
			if c.Flags().Changed("as-sdt") {
				params.Set("asSdt", p_asSdtVar)
			}
			if c.Flags().Changed("as-vis") {
				params.Set("asVis", strconv.FormatFloat(p_asVisVar, 'f', -1, 64))
			}
			if c.Flags().Changed("as-yhi") {
				params.Set("asYhi", strconv.Itoa(p_asYhiVar))
			}
			if c.Flags().Changed("as-ylo") {
				params.Set("asYlo", strconv.Itoa(p_asYloVar))
			}
			if c.Flags().Changed("cites") {
				params.Set("cites", p_citesVar)
			}
			if c.Flags().Changed("cluster") {
				params.Set("cluster", p_clusterVar)
			}
			if c.Flags().Changed("filter") {
				params.Set("filter", strconv.FormatFloat(p_filterVar, 'f', -1, 64))
			}
			if c.Flags().Changed("hl") {
				params.Set("hl", p_hlVar)
			}
			if c.Flags().Changed("lr") {
				for _, v := range p_lrVar {
					params.Add("lr"+"[]", v)
				}
			}
			if c.Flags().Changed("num") {
				params.Set("num", strconv.Itoa(p_numVar))
			}
			params.Set("q", p_qVar)
			if c.Flags().Changed("safe") {
				params.Set("safe", p_safeVar)
			}
			if c.Flags().Changed("scisbd") {
				params.Set("scisbd", strconv.Itoa(p_scisbdVar))
			}
			if c.Flags().Changed("start") {
				params.Set("start", strconv.Itoa(p_startVar))
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/google/scholar", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().Float64Var(&p_asRrVar, "as-rr", 0, "asRr Review Articles Only: Set to 1 to return review articles only, or 0 (default) to return all articles.")
	cmd.Flags().StringVar(&p_asSdtVar, "as-sdt", "0,5", "asSdt Search Type / Filter: Search type/filter, e.g. `0,5` for the default Articles filter, `4` for case law with court codes, or `0`/`7` for patents.")
	cmd.Flags().Float64Var(&p_asVisVar, "as-vis", 0, "asVis Exclude Citations: Set to 1 to exclude citations from the results, or 0 (default) to include them.")
	cmd.Flags().IntVar(&p_asYhiVar, "as-yhi", 2024, "asYhi Year To: Return results published up to and including this year.")
	cmd.Flags().IntVar(&p_asYloVar, "as-ylo", 2020, "asYlo Year From: Return results published from this year onward.")
	cmd.Flags().StringVar(&p_citesVar, "cites", "", "cites Cited By Search: Unique article ID to look up articles that cite it, as returned in a result's `citedBy.citesId`.")
	cmd.Flags().StringVar(&p_clusterVar, "cluster", "", "cluster All Versions Search: Unique article ID to look up all indexed versions of that article, as returned in a result's `versions.clusterId`.")
	cmd.Flags().Float64Var(&p_filterVar, "filter", 0, "filter Results Filtering: Defines whether to enable or disable the filters for 'Similar Results' and 'Omitted Results'. Set to 1 (default) to enable these filters, or 0 to disable them.\n")
	cmd.Flags().StringVar(&p_hlVar, "hl", "", "hl Language: The two-letter language code for the language you want to use for the search.")
	cmd.Flags().StringSliceVar(&p_lrVar, "lr", nil, "lr Set Multiple Languages: The 'lr' parameter specifies the language of the websites to return results from. This parameter filters results based on the language of the web content.")
	_ = cmd.RegisterFlagCompletionFunc("lr", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"lang_ar", "lang_hy", "lang_bg", "lang_ca", "lang_cs", "lang_da", "lang_de", "lang_el", "lang_en", "lang_es", "lang_et", "lang_tl", "lang_fi", "lang_fr", "lang_hr", "lang_hi", "lang_hu", "lang_id", "lang_is", "lang_it", "lang_iw", "lang_he", "lang_ja", "lang_ko", "lang_lt", "lang_lv", "lang_nl", "lang_no", "lang_fa", "lang_pl", "lang_pt", "lang_ro", "lang_ru", "lang_sk", "lang_sl", "lang_sr", "lang_sv", "lang_th", "lang_tr", "lang_uk", "lang_vi", "lang_zh-CN", "lang_zh-TW"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().IntVar(&p_numVar, "num", 0, "num Number of Results: Maximum number of results to return per page.")
	cmd.Flags().StringVar(&p_qVar, "q", "machine learning", "q Search Query: Search query. Supports Google Scholar search helpers such as `author:` and `source:`. (required)")
	_ = cmd.MarkFlagRequired("q")
	cmd.Flags().StringVar(&p_safeVar, "safe", "", "safe Adult Content Filtering: Adult content filtering option. [allowed: active|off]")
	_ = cmd.RegisterFlagCompletionFunc("safe", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"active", "off"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().IntVar(&p_scisbdVar, "scisbd", 0, "scisbd Sort By Date: Sort results by date instead of relevance: 1 for abstracts only, 2 for everything. Omit for relevance sorting.")
	cmd.Flags().IntVar(&p_startVar, "start", 0, "start Result Offset: Result offset for pagination, where 0 is the first result.")

	return cmd
}

func init() {
	RegisterAPICommand("google_scholar", "Google Scholar", newGoogleScholarCmd())
}
