// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newIndeedJobCmd() *cobra.Command {
	var p_urlVar string

	cmd := &cobra.Command{
		Use:   "indeed-job",
		Short: "Indeed Job API  (5 credits/call)",
		Long:  "The Indeed Job API allows you to retrieve detailed information about a specific job listing based on the provided vacancy URL.\n\nEndpoint: GET https://api.hasdata.com/scrape/indeed/job\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("url", p_urlVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/indeed/job", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_urlVar, "url", "https://www.indeed.com/viewjob?jk=3c916f0d7f870c71", "url Job URL: The URL of the job vacancy to retrieve details for. (required)")
	_ = cmd.MarkFlagRequired("url")

	return cmd
}

func init() {
	RegisterAPICommand("job", "Jobs", newIndeedJobCmd())
}
