// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newWalmartProductCmd() *cobra.Command {
	var p_domainVar string
	var p_itemIdVar string
	var p_languageVar string
	var p_otherOffersVar bool
	var p_urlVar string

	cmd := &cobra.Command{
		Use:   "walmart-product",
		Short: "Walmart Product Scraper API  (10 credits/call)",
		Long:  "The Walmart Product Scraper API returns the full detail page of a single Walmart item, and optionally the offers of other sellers competing for the same product.\n\nEndpoint: GET https://api.hasdata.com/scrape/walmart/product\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("domain") {
				if err := validateEnumString("domain", p_domainVar, []string{"walmart.com", "walmart.ca"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("language") {
				if err := validateEnumString("language", p_languageVar, []string{"en", "es", "fr"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("domain") {
				params.Set("domain", p_domainVar)
			}
			if c.Flags().Changed("item-id") {
				params.Set("itemId", p_itemIdVar)
			}
			if c.Flags().Changed("language") {
				params.Set("language", p_languageVar)
			}
			if c.Flags().Changed("other-offers") {
				params.Set("otherOffers", strconv.FormatBool(p_otherOffersVar))
			}
			if c.Flags().Changed("url") {
				params.Set("url", p_urlVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/walmart/product", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_domainVar, "domain", "", "domain Domain: Walmart storefront the item belongs to. Each storefront has its own catalog, item ids, prices and currency, so an id from one storefront does not resolve on another. Ignored when url is provided. Default is walmart.com. [allowed: walmart.com|walmart.ca]")
	_ = cmd.RegisterFlagCompletionFunc("domain", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"walmart.com", "walmart.ca"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_itemIdVar, "item-id", "14977205582", "itemId Item ID: Walmart item id, taken from a product URL or from the id field of the Walmart Search API response. On walmart.com it is numeric (for example 14977205582), on walmart.ca an alphanumeric code (for example 6NZMJ5CW6MH2). Required unless url is provided.")
	cmd.Flags().StringVar(&p_languageVar, "language", "en", "language Language: Language of the product details. Availability depends on the storefront - walmart.com serves en and es, walmart.ca serves en and fr. A language the storefront does not support falls back to its default. [allowed: en|es|fr]")
	_ = cmd.RegisterFlagCompletionFunc("language", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"en", "es", "fr"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().BoolVar(&p_otherOffersVar, "other-offers", false, "otherOffers Other Sellers: Also collect the offers of other sellers competing for this item - each seller name, storefront, price, condition, shipping cost, delivery date and return policy. This takes an extra request to Walmart and costs 5 credits on top of the base 10, whether or not the item turns out to have competing sellers. How many competitors the item advertises, and the cheapest competing price, are returned in the otherOffers block whether the switch is on or off, so it can be left off until the count shows there is something to collect. Default is false.")
	cmd.Flags().StringVar(&p_urlVar, "url", "https://www.walmart.com/ip/Samsung-Galaxy-S25-Ultra-256GB-Unlocked-Android-Cell-Phone-with-200MP-Camera-Titanium-Blue/14977205582", "url Product URL: A full Walmart product URL to scrape as is. When provided, it overrides itemId and the storefront is taken from the URL itself. Required unless itemId is provided.")

	return cmd
}

func init() {
	RegisterAPICommand("ecommerce", "E-commerce", newWalmartProductCmd())
}
