// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newYoutubeTranscriptApiCmd() *cobra.Command {
	var p_languageCodeVar string
	var p_typeVar string
	var p_vVar string

	cmd := &cobra.Command{
		Use:   "youtube-transcript-api",
		Short: "YouTube Transcript API  (10 credits/call)",
		Long:  "The YouTube Transcript API extracts the full transcript (subtitles) from a YouTube video.\n\nEndpoint: GET https://api.hasdata.com/scrape/youtube/transcript\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("type") {
				if err := validateEnumString("type", p_typeVar, []string{"asr"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("language-code") {
				params.Set("languageCode", p_languageCodeVar)
			}
			if c.Flags().Changed("type") {
				params.Set("type", p_typeVar)
			}
			params.Set("v", p_vVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/youtube/transcript", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_languageCodeVar, "language-code", "en", "languageCode Language Code: BCP-47 / YouTube language code of the transcript track to return (e.g. `en`, `de`, `en-US`, `pt-BR`). Must match a track that the video actually has. When omitted, the video's default language track is returned.")
	cmd.Flags().StringVar(&p_typeVar, "type", "", "type Transcript Type: Set to `asr` to fetch the YouTube auto-generated (speech-recognition) track. Omit to fetch the human-authored track for `languageCode` when one exists. [allowed: asr]")
	_ = cmd.RegisterFlagCompletionFunc("type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"asr"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_vVar, "v-param", "dQw4w9WgXcQ", "v Video ID: 11-character YouTube video ID — the value of the `v=` query parameter in a watch URL (e.g. `dQw4w9WgXcQ` for `https://www.youtube.com/watch?v=dQw4w9WgXcQ`). (required)")
	_ = cmd.MarkFlagRequired("v-param")

	return cmd
}

func init() {
	RegisterAPICommand("youtube", "YouTube", newYoutubeTranscriptApiCmd())
}
