// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newAmazonProductCmd() *cobra.Command {
	var p_asinVar string
	var p_deliveryZipVar string
	var p_domainVar string
	var p_languageVar string
	var p_otherSellersVar bool
	var p_otherSellersVarNeg bool
	var p_shippingLocationVar string

	cmd := &cobra.Command{
		Use:   "amazon-product",
		Short: "Amazon Product API  (5 credits/call)",
		Long:  "The Amazon Product API allows users to get product details from Amazon based on the specified ASIN and domain. This API enables retrieving detailed information about a specific product on Amazon.\n\nEndpoint: GET https://api.hasdata.com/scrape/amazon/product\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("domain") {
				if err := validateEnumString("domain", p_domainVar, []string{"www.amazon.com", "www.amazon.de", "www.amazon.co.uk", "www.amazon.ae", "www.amazon.com.au", "www.amazon.com.be", "www.amazon.com.br", "www.amazon.ca", "www.amazon.eg", "www.amazon.es", "www.amazon.fr", "www.amazon.ie", "www.amazon.in", "www.amazon.it", "www.amazon.co.jp", "www.amazon.com.mx", "www.amazon.nl", "www.amazon.pl", "www.amazon.sa", "www.amazon.se", "www.amazon.sg", "www.amazon.com.tr", "www.amazon.co.za"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("other-sellers") && c.Flags().Changed("no-"+"other-sellers") {
				return fmt.Errorf("cannot set both --%s and --no-%s", "other-sellers", "other-sellers")
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("asin", p_asinVar)
			if c.Flags().Changed("delivery-zip") {
				params.Set("deliveryZip", p_deliveryZipVar)
			}
			if c.Flags().Changed("domain") {
				params.Set("domain", p_domainVar)
			}
			if c.Flags().Changed("language") {
				params.Set("language", p_languageVar)
			}
			{
				val := p_otherSellersVar
				changed := c.Flags().Changed("other-sellers")
				if c.Flags().Changed("no-" + "other-sellers") {
					val = !p_otherSellersVarNeg
					changed = true
				}
				if changed {
					params.Set("otherSellers", strconv.FormatBool(val))
				}
			}
			if c.Flags().Changed("shipping-location") {
				params.Set("shippingLocation", p_shippingLocationVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/amazon/product", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_asinVar, "asin", "B0DHJ7SBDR", "asin ASIN: The Amazon Standard Identification Number (ASIN) of the product. (required)")
	_ = cmd.MarkFlagRequired("asin")
	cmd.Flags().StringVar(&p_deliveryZipVar, "delivery-zip", "", "deliveryZip Delivery ZIP Code: Postal code of the delivery location.")
	cmd.Flags().StringVar(&p_domainVar, "domain", "", "domain Domain: Amazon domain to use. Default is www.amazon.com. [allowed: www.amazon.com|www.amazon.de|www.amazon.co.uk|www.amazon.ae|www.amazon.com.au|www.amazon.com.be|www.amazon.com.br|www.amazon.ca|www.amazon.eg|www.amazon.es|www.amazon.fr|www.amazon.ie|www.amazon.in|www.amazon.it|www.amazon.co.jp|www.amazon.com.mx|www.amazon.nl|www.amazon.pl|www.amazon.sa|www.amazon.se|www.amazon.sg|www.amazon.com.tr|www.amazon.co.za]")
	_ = cmd.RegisterFlagCompletionFunc("domain", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"www.amazon.com", "www.amazon.de", "www.amazon.co.uk", "www.amazon.ae", "www.amazon.com.au", "www.amazon.com.be", "www.amazon.com.br", "www.amazon.ca", "www.amazon.eg", "www.amazon.es", "www.amazon.fr", "www.amazon.ie", "www.amazon.in", "www.amazon.it", "www.amazon.co.jp", "www.amazon.com.mx", "www.amazon.nl", "www.amazon.pl", "www.amazon.sa", "www.amazon.se", "www.amazon.sg", "www.amazon.com.tr", "www.amazon.co.za"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_languageVar, "language", "", "language Language: Optional Amazon language code. Supported values depend on the selected domain.")
	cmd.Flags().BoolVar(&p_otherSellersVar, "other-sellers", true, "otherSellers Other Sellers: If set to true, extracts the other sellers block from the product page.")
	cmd.Flags().BoolVar(&p_otherSellersVarNeg, "no-"+"other-sellers", false, "disable --other-sellers")
	cmd.Flags().StringVar(&p_shippingLocationVar, "shipping-location", "", "shippingLocation Shipping Location: The two-letter country code to define the country of the delivery address.")

	return cmd
}

func init() {
	RegisterAPICommand("amazon", "Amazon", newAmazonProductCmd())
}
