// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newTiktokPostsCmd() *cobra.Command {
	var p_handleVar string
	var p_nextPageTokenVar string

	cmd := &cobra.Command{
		Use:   "tiktok-posts",
		Short: "TikTok Posts Scraper API  (10 credits/call)",
		Long:  "The TikTok Posts Scraper API lets you retrieve the videos of a public TikTok account using its handle. It returns each video with description, hashtags, mentions, like/comment/share/play counts, cover and playable video URLs, music, and timestamp. Results are paginated with a token — pass the `nextPageToken` from a response to fetch the next page.\n\nEndpoint: GET https://api.hasdata.com/scrape/tiktok/posts\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("handle", p_handleVar)
			if c.Flags().Changed("next-page-token") {
				params.Set("nextPageToken", p_nextPageTokenVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/tiktok/posts", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_handleVar, "handle", "tiktok", "handle TikTok Handle: The TikTok username of the account whose videos you want to scrape, with or without the `@` symbol. (required)")
	_ = cmd.MarkFlagRequired("handle")
	cmd.Flags().StringVar(&p_nextPageTokenVar, "next-page-token", "", "nextPageToken Next Page Token: Defines the next page token. It is used for retrieving the next page of results. Use the `nextPageToken` value returned by the previous response. Omit it to fetch the first page.")

	return cmd
}

func init() {
	RegisterAPICommand("social", "Social", newTiktokPostsCmd())
}
