// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newGoogleShortVideosCmd() *cobra.Command {
	var p_crVar string
	var p_deviceTypeVar string
	var p_glVar string
	var p_hlVar string
	var p_locationVar string
	var p_lrVar []string
	var p_pageVar int
	var p_qVar string
	var p_uuleVar string

	cmd := &cobra.Command{
		Use:   "google-short-videos",
		Short: "Google Short Videos API  (5 credits/call)",
		Long:  "The Google Short Videos API provides real-time access to short-form video content indexed by Google, allowing users to retrieve videos based on specific queries, topics, platforms, and customizable filters for highly relevant video results.\n\nEndpoint: GET https://api.hasdata.com/scrape/google/short-videos\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("device-type") {
				if err := validateEnumString("device-type", p_deviceTypeVar, []string{"desktop", "mobile", "tablet"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("lr") {
				if err := validateEnumStringSlice("lr", p_lrVar, []string{"lang_ar", "lang_hy", "lang_bg", "lang_ca", "lang_cs", "lang_da", "lang_de", "lang_el", "lang_en", "lang_es", "lang_et", "lang_tl", "lang_fi", "lang_fr", "lang_hr", "lang_hi", "lang_hu", "lang_id", "lang_is", "lang_it", "lang_iw", "lang_he", "lang_ja", "lang_ko", "lang_lt", "lang_lv", "lang_nl", "lang_no", "lang_fa", "lang_pl", "lang_pt", "lang_ro", "lang_ru", "lang_sk", "lang_sl", "lang_sr", "lang_sv", "lang_th", "lang_tr", "lang_uk", "lang_vi", "lang_zh-CN", "lang_zh-TW"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("cr") {
				params.Set("cr", p_crVar)
			}
			if c.Flags().Changed("device-type") {
				params.Set("deviceType", p_deviceTypeVar)
			}
			if c.Flags().Changed("gl") {
				params.Set("gl", p_glVar)
			}
			if c.Flags().Changed("hl") {
				params.Set("hl", p_hlVar)
			}
			if c.Flags().Changed("location") {
				params.Set("location", p_locationVar)
			}
			if c.Flags().Changed("lr") {
				for _, v := range p_lrVar {
					params.Add("lr"+"[]", v)
				}
			}
			if c.Flags().Changed("page") {
				params.Set("page", strconv.Itoa(p_pageVar))
			}
			params.Set("q", p_qVar)
			if c.Flags().Changed("uule") {
				params.Set("uule", p_uuleVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/google/short-videos", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_crVar, "cr", "", "cr Country: The country code for the country you want to limit the search to.")
	cmd.Flags().StringVar(&p_deviceTypeVar, "device-type", "desktop", "deviceType Device: Specify the device type for the search. [allowed: desktop|mobile|tablet]")
	_ = cmd.RegisterFlagCompletionFunc("device-type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"desktop", "mobile", "tablet"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_glVar, "gl", "", "gl Country: The two-letter country code for the country you want to limit the search to.")
	cmd.Flags().StringVar(&p_hlVar, "hl", "", "hl Language: The two-letter language code for the language you want to use for the search.")
	cmd.Flags().StringVar(&p_locationVar, "location", "Austin,Texas,United States", "location Location: Google canonical location for the search.")
	cmd.Flags().StringSliceVar(&p_lrVar, "lr", nil, "lr Set Multiple Languages: The 'lr' parameter specifies the language of the websites to return results from. This parameter filters results based on the language of the web content.")
	_ = cmd.RegisterFlagCompletionFunc("lr", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"lang_ar", "lang_hy", "lang_bg", "lang_ca", "lang_cs", "lang_da", "lang_de", "lang_el", "lang_en", "lang_es", "lang_et", "lang_tl", "lang_fi", "lang_fr", "lang_hr", "lang_hi", "lang_hu", "lang_id", "lang_is", "lang_it", "lang_iw", "lang_he", "lang_ja", "lang_ko", "lang_lt", "lang_lv", "lang_nl", "lang_no", "lang_fa", "lang_pl", "lang_pt", "lang_ro", "lang_ru", "lang_sk", "lang_sl", "lang_sr", "lang_sv", "lang_th", "lang_tr", "lang_uk", "lang_vi", "lang_zh-CN", "lang_zh-TW"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().IntVar(&p_pageVar, "page", 0, "page Page Number: Page number for paginated results, where 0 is the first page.")
	cmd.Flags().StringVar(&p_qVar, "q", "Coffee", "q Search Query: Search query term for retrieving short videos results. (required)")
	_ = cmd.MarkFlagRequired("q")
	cmd.Flags().StringVar(&p_uuleVar, "uule", "", "uule Encoded Location: The encoded location parameter.")

	return cmd
}

func init() {
	RegisterAPICommand("google_serp", "Google SERP", newGoogleShortVideosCmd())
}
