// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newGoogleNewsCmd() *cobra.Command {
	var p_glVar string
	var p_hlVar string
	var p_publicationTokenVar string
	var p_qVar string
	var p_sectionTokenVar string
	var p_soVar string
	var p_storyTokenVar string
	var p_topicTokenVar string

	cmd := &cobra.Command{
		Use:   "google-news",
		Short: "Google News API  (10 credits/call)",
		Long:  "The Google News API offers real-time access to comprehensive news articles from Google, enabling users to fetch news based on specific queries, locations, publishers, and various filter options for tailored news feeds.\n\nEndpoint: GET https://api.hasdata.com/scrape/google/news\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("gl") {
				params.Set("gl", p_glVar)
			}
			if c.Flags().Changed("hl") {
				params.Set("hl", p_hlVar)
			}
			if c.Flags().Changed("publication-token") {
				params.Set("publicationToken", p_publicationTokenVar)
			}
			if c.Flags().Changed("q") {
				params.Set("q", p_qVar)
			}
			if c.Flags().Changed("section-token") {
				params.Set("sectionToken", p_sectionTokenVar)
			}
			if c.Flags().Changed("so") {
				params.Set("so", p_soVar)
			}
			if c.Flags().Changed("story-token") {
				params.Set("storyToken", p_storyTokenVar)
			}
			if c.Flags().Changed("topic-token") {
				params.Set("topicToken", p_topicTokenVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/google/news", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_glVar, "gl", "", "gl Country: The two-letter country code for the country you want to limit the search to.")
	cmd.Flags().StringVar(&p_hlVar, "hl", "", "hl Language: The two-letter language code for the language you want to use for the search.")
	cmd.Flags().StringVar(&p_publicationTokenVar, "publication-token", "", "publicationToken Publication Token: Token for a specific publisher such as CNN or BBC. Not allowed with `q`, `storyToken`, or `topicToken`.")
	cmd.Flags().StringVar(&p_qVar, "q", "", "q Search Query: Free-text query as used on news.google.com. Not allowed with `topicToken`, `storyToken`, or `publicationToken`.")
	cmd.Flags().StringVar(&p_sectionTokenVar, "section-token", "", "sectionToken Section Token: Token for a sub-section under a topic, for example Business → Economy. Use only when `topicToken` or `publicationToken` is present.")
	cmd.Flags().StringVar(&p_soVar, "so", "", "so Sort Order: Sort order for articles in a story. Use only with storyToken.")
	cmd.Flags().StringVar(&p_storyTokenVar, "story-token", "", "storyToken Story Token: Token for a single news story cluster (the “Full coverage” page).")
	cmd.Flags().StringVar(&p_topicTokenVar, "topic-token", "", "topicToken Topic Token: Token for a Google News topic such as World, Business, or Technology. Not allowed with `q`, `storyToken`, or `publicationToken`.")

	return cmd
}

func init() {
	RegisterAPICommand("google_serp", "Google SERP", newGoogleNewsCmd())
}
