// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newAirbnbListingCmd() *cobra.Command {
	var p_adultsVar int
	var p_checkInVar string
	var p_checkOutVar string
	var p_childrenVar int
	var p_infantsVar int
	var p_locationVar string
	var p_nextPageTokenVar string
	var p_petsVar int

	cmd := &cobra.Command{
		Use:   "airbnb-listing",
		Short: "Airbnb Listing API  (5 credits/call)",
		Long:  "The Airbnb Listing API allows users to retrieve listings from Airbnb based on location and check-in/check-out dates.\n\nEndpoint: GET https://api.hasdata.com/scrape/airbnb/listing\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("adults") {
				params.Set("adults", strconv.Itoa(p_adultsVar))
			}
			params.Set("checkIn", p_checkInVar)
			if c.Flags().Changed("check-out") {
				params.Set("checkOut", p_checkOutVar)
			}
			if c.Flags().Changed("children") {
				params.Set("children", strconv.Itoa(p_childrenVar))
			}
			if c.Flags().Changed("infants") {
				params.Set("infants", strconv.Itoa(p_infantsVar))
			}
			params.Set("location", p_locationVar)
			if c.Flags().Changed("next-page-token") {
				params.Set("nextPageToken", p_nextPageTokenVar)
			}
			if c.Flags().Changed("pets") {
				params.Set("pets", strconv.Itoa(p_petsVar))
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/airbnb/listing", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().IntVar(&p_adultsVar, "adults", 0, "adults Number of Adults: Number of adults.\n")
	cmd.Flags().StringVar(&p_checkInVar, "check-in", "2026-01-01", "checkIn Check-in Date: The check-in date for the listings. (required)")
	_ = cmd.MarkFlagRequired("check-in")
	cmd.Flags().StringVar(&p_checkOutVar, "check-out", "2026-01-05", "checkOut Check-out Date: The check-out date for the listings.")
	cmd.Flags().IntVar(&p_childrenVar, "children", 0, "children Number of Children: Number of children.\n")
	cmd.Flags().IntVar(&p_infantsVar, "infants", 0, "infants Number of Infants: Number of infants.\n")
	cmd.Flags().StringVar(&p_locationVar, "location", "New York", "location Location: The location to search for listings. (required)")
	_ = cmd.MarkFlagRequired("location")
	cmd.Flags().StringVar(&p_nextPageTokenVar, "next-page-token", "", "nextPageToken Next Page Token: The token used to retrieve the next page of results.")
	cmd.Flags().IntVar(&p_petsVar, "pets", 0, "pets Number of Pets: Number of pets.\n")

	return cmd
}

func init() {
	RegisterAPICommand("airbnb", "Airbnb", newAirbnbListingCmd())
}
