// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newGoogleFlightsCmd() *cobra.Command {
	var p_adultsVar int
	var p_arrivalIdVar string
	var p_bagsVar int
	var p_bookingTokenVar string
	var p_childrenVar int
	var p_currencyVar string
	var p_deepSearchVar bool
	var p_departureIdVar string
	var p_departureTokenVar string
	var p_excludeAirlinesVar string
	var p_excludeConnectionsVar string
	var p_glVar string
	var p_hlVar string
	var p_includeAirlinesVar string
	var p_includeConnectionsVar string
	var p_infantsInSeatVar int
	var p_infantsOnLapVar int
	var p_layoverDurationVar string
	var p_lessEmissionsVar bool
	var p_maxDurationVar int
	var p_maxPriceVar float64
	var p_multiCityJsonVar string
	var p_outboundDateVar string
	var p_outboundTimesVar string
	var p_returnDateVar string
	var p_returnTimesVar string
	var p_showHiddenVar bool
	var p_sortByVar string
	var p_stopsVar string
	var p_travelClassVar string
	var p_typeVar string

	cmd := &cobra.Command{
		Use:   "google-flights",
		Short: "Google Flights API  (15 credits/call)",
		Long:  "The Google Flights API provides real-time access to structured flight search results, enabling users to find flights based on various criteria.\n\nEndpoint: GET https://api.hasdata.com/scrape/google/flights\nCost: 15 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("sort-by") {
				if err := validateEnumString("sort-by", p_sortByVar, []string{"topFlights", "price", "departureTime", "arrivalTime", "duration", "emissions"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("stops") {
				if err := validateEnumString("stops", p_stopsVar, []string{"nonStop", "oneStopOrFewer", "twoStopsOrFewer"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("travel-class") {
				if err := validateEnumString("travel-class", p_travelClassVar, []string{"economy", "premiumEconomy", "business", "first"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("type") {
				if err := validateEnumString("type", p_typeVar, []string{"roundTrip", "oneWay", "multiCity"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("adults") {
				params.Set("adults", strconv.Itoa(p_adultsVar))
			}
			params.Set("arrivalId", p_arrivalIdVar)
			if c.Flags().Changed("bags") {
				params.Set("bags", strconv.Itoa(p_bagsVar))
			}
			if c.Flags().Changed("booking-token") {
				params.Set("bookingToken", p_bookingTokenVar)
			}
			if c.Flags().Changed("children") {
				params.Set("children", strconv.Itoa(p_childrenVar))
			}
			if c.Flags().Changed("currency") {
				params.Set("currency", p_currencyVar)
			}
			if c.Flags().Changed("deep-search") {
				params.Set("deepSearch", strconv.FormatBool(p_deepSearchVar))
			}
			params.Set("departureId", p_departureIdVar)
			if c.Flags().Changed("departure-token") {
				params.Set("departureToken", p_departureTokenVar)
			}
			if c.Flags().Changed("exclude-airlines") {
				params.Set("excludeAirlines", p_excludeAirlinesVar)
			}
			if c.Flags().Changed("exclude-connections") {
				params.Set("excludeConnections", p_excludeConnectionsVar)
			}
			if c.Flags().Changed("gl") {
				params.Set("gl", p_glVar)
			}
			if c.Flags().Changed("hl") {
				params.Set("hl", p_hlVar)
			}
			if c.Flags().Changed("include-airlines") {
				params.Set("includeAirlines", p_includeAirlinesVar)
			}
			if c.Flags().Changed("include-connections") {
				params.Set("includeConnections", p_includeConnectionsVar)
			}
			if c.Flags().Changed("infants-in-seat") {
				params.Set("infantsInSeat", strconv.Itoa(p_infantsInSeatVar))
			}
			if c.Flags().Changed("infants-on-lap") {
				params.Set("infantsOnLap", strconv.Itoa(p_infantsOnLapVar))
			}
			if c.Flags().Changed("layover-duration") {
				params.Set("layoverDuration", p_layoverDurationVar)
			}
			if c.Flags().Changed("less-emissions") {
				params.Set("lessEmissions", strconv.FormatBool(p_lessEmissionsVar))
			}
			if c.Flags().Changed("max-duration") {
				params.Set("maxDuration", strconv.Itoa(p_maxDurationVar))
			}
			if c.Flags().Changed("max-price") {
				params.Set("maxPrice", strconv.FormatFloat(p_maxPriceVar, 'f', -1, 64))
			}
			if c.Flags().Changed("multi-city-json") {
				params.Set("multiCityJson", p_multiCityJsonVar)
			}
			params.Set("outboundDate", p_outboundDateVar)
			if c.Flags().Changed("outbound-times") {
				params.Set("outboundTimes", p_outboundTimesVar)
			}
			if c.Flags().Changed("return-date") {
				params.Set("returnDate", p_returnDateVar)
			}
			if c.Flags().Changed("return-times") {
				params.Set("returnTimes", p_returnTimesVar)
			}
			if c.Flags().Changed("show-hidden") {
				params.Set("showHidden", strconv.FormatBool(p_showHiddenVar))
			}
			if c.Flags().Changed("sort-by") {
				params.Set("sortBy", p_sortByVar)
			}
			if c.Flags().Changed("stops") {
				params.Set("stops", p_stopsVar)
			}
			if c.Flags().Changed("travel-class") {
				params.Set("travelClass", p_travelClassVar)
			}
			if c.Flags().Changed("type") {
				params.Set("type", p_typeVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/google/flights", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().IntVar(&p_adultsVar, "adults", 0, "adults Adults: Number of adult passengers (>= 1 if specified).\n")
	cmd.Flags().StringVar(&p_arrivalIdVar, "arrival-id", "JFK", "arrivalId Arrival airport code / location kgmid: Specifies the arrival airport code (IATA) or location kgmid.\n\n  - **IATA Code**: A 3-letter uppercase code (e.g., `SFO` for San Francisco, `LHR` for London Heathrow). Search on [IATA](https://www.iata.org/en/publications/directories/code-search).\n  - **Location kgmid**: A string starting with `/m/`, found in Wikidata under \"Freebase ID\" (e.g., `/m/02_286` for New York, NY).\n\nMultiple values can be separated by commas (e.g., `JFK,LGA,/m/0hptm`).\n (required)")
	_ = cmd.MarkFlagRequired("arrival-id")
	cmd.Flags().IntVar(&p_bagsVar, "bags", 0, "bags Number of Bags: Number of carry-on bags per passenger.\n")
	cmd.Flags().StringVar(&p_bookingTokenVar, "booking-token", "", "bookingToken Booking Token: Used to request booking options for selected flights. This token is found in the flight results and cannot be used with `departureToken`.\n")
	cmd.Flags().IntVar(&p_childrenVar, "children", 0, "children Children: Number of child passengers.\n")
	cmd.Flags().StringVar(&p_currencyVar, "currency", "", "currency Currency: Parameter defines the currency of the returned prices")
	cmd.Flags().BoolVar(&p_deepSearchVar, "deep-search", false, "deepSearch Deep Search: Enable deep search. Returns the same results as Google Flights in a browser, but takes longer to respond. Default is `false`.\n")
	cmd.Flags().StringVar(&p_departureIdVar, "departure-id", "LHR", "departureId Departure airport code / location kgmid: Specifies the departure airport code (IATA) or location kgmid.\n\n  - **IATA Code**: A 3-letter uppercase code (e.g., SFO for San Francisco, LHR for London Heathrow). Search on [IATA](https://www.iata.org/en/publications/directories/code-search).\n  - **Location kgmid**: A string starting with `/m/`, found in Wikidata under \"Freebase ID\" (e.g., `/m/02_286` for New York, NY).\n\nMultiple values can be separated by commas (e.g., `JFK,LGA,/m/0hptm`).\n (required)")
	_ = cmd.MarkFlagRequired("departure-id")
	cmd.Flags().StringVar(&p_departureTokenVar, "departure-token", "", "departureToken Departure Token: Used to select a flight and retrieve return flights for a round trip or the next leg of the itinerary for a multi-city trip.\n")
	cmd.Flags().StringVar(&p_excludeAirlinesVar, "exclude-airlines", "", "excludeAirlines Exclude Airlines: A comma separated list of airline codes to exclude from results. You can search for airline codes on [IATA](https://www.iata.org/en/publications/directories/code-search). For example, `UA` is United Airlines.\n")
	cmd.Flags().StringVar(&p_excludeConnectionsVar, "exclude-connections", "", "excludeConnections Exclude Connections: A comma separated list of specific airports to exclude as connections.\n")
	cmd.Flags().StringVar(&p_glVar, "gl", "", "gl Country: The two-letter country code for the country you want to limit the search to.")
	cmd.Flags().StringVar(&p_hlVar, "hl", "", "hl Language: The two-letter language code for the language you want to use for the search.")
	cmd.Flags().StringVar(&p_includeAirlinesVar, "include-airlines", "", "includeAirlines Include Airlines: A comma separated list of airline codes to exclusively include in results. You can search for airline codes on [IATA](https://www.iata.org/en/publications/directories/code-search). For example, `UA` is United Airlines.\n\n`excludeAirlines` and `includeAirlines` parameters can't be used together.\n")
	cmd.Flags().StringVar(&p_includeConnectionsVar, "include-connections", "", "includeConnections Include Connections: A comma separated list of specific airports to allow as connections.\n")
	cmd.Flags().IntVar(&p_infantsInSeatVar, "infants-in-seat", 0, "infantsInSeat Infants in Seat: Number of infants occupying seats.\n")
	cmd.Flags().IntVar(&p_infantsOnLapVar, "infants-on-lap", 0, "infantsOnLap Infants on Lap: Number of infants sitting on an adult's lap.\n")
	cmd.Flags().StringVar(&p_layoverDurationVar, "layover-duration", "", "layoverDuration Maximum Layover Duration: Set the maximum layover duration in minutes to filter flights. For example, `120, 360` filters layovers between 2 hours and 6 hours, while `45, 180` allows layovers from 45 minutes to 3 hours.\n")
	cmd.Flags().BoolVar(&p_lessEmissionsVar, "less-emissions", false, "lessEmissions Fewer Emissions: Prefer flight options with lower carbon emissions.\n")
	cmd.Flags().IntVar(&p_maxDurationVar, "max-duration", 0, "maxDuration Maximum Flight Duration: The maximum total flight duration in minutes.\n")
	cmd.Flags().Float64Var(&p_maxPriceVar, "max-price", 0, "maxPrice Maximum Price: Maximum price limit for the flight search, in the selected currency.\n")
	cmd.Flags().StringVar(&p_multiCityJsonVar, "multi-city-json", "", "multiCityJson Multi-city JSON: This parameter specifies flight details for multi-city trips. It is a JSON string containing multiple flight objects. Each object must include the following fields:\n\n- **departureId** – The departure airport code or location KGMID. Uses the same format as the main `departureId` parameter.\n- **arrivalId** – The arrival airport code or location KGMID. Uses the same format as the main `arrivalId` parameter.\n- **date** – The flight date. Uses the same format as the `outboundDate` parameter.\n- **times** *(optional)* – The time range for the flight. Uses the same format as the `outboundTimes` parameter.\n")
	cmd.Flags().StringVar(&p_outboundDateVar, "outbound-date", "2026-08-15", "outboundDate Outbound Date: The outbound travel date in 'yyyy-MM-dd' format.\n (required)")
	_ = cmd.MarkFlagRequired("outbound-date")
	cmd.Flags().StringVar(&p_outboundTimesVar, "outbound-times", "", "outboundTimes Outbound Times: Set up to 4 time boundaries (2 for departure, 2 for arrival) to filter flights. Each number represents the start of an hour.\n\nExamples:\n  - `6,20` → 6:00 AM - 9:00 PM departure\n  - `1,15` → 1:00 AM - 4:00 PM departure\n  - `7,18,2,21` → 7:00 AM - 9:00 PM departure, 2:00 AM - 10:00 PM arrival\n")
	cmd.Flags().StringVar(&p_returnDateVar, "return-date", "2026-08-20", "returnDate Return Date: The return travel date in 'yyyy-MM-dd' format. Required when **type** is `roundTrip`.\n")
	cmd.Flags().StringVar(&p_returnTimesVar, "return-times", "", "returnTimes Return Times: Set up to 4 time boundaries (2 for departure, 2 for arrival) to filter return flights. Each number represents the start of an hour.\n\nExamples:\n  - `6,20` → 6:00 AM - 9:00 PM departure\n  - `1,15` → 1:00 AM - 4:00 PM departure\n  - `7,18,2,21` → 7:00 AM - 9:00 PM departure, 2:00 AM - 10:00 PM arrival\n")
	cmd.Flags().BoolVar(&p_showHiddenVar, "show-hidden", false, "showHidden Show Hidden Fares: Indicates whether to include hidden options in the results.\n")
	cmd.Flags().StringVar(&p_sortByVar, "sort-by", "", "sortBy Sort By: Sort the flight results based on price, departure time, arrival time, etc.\n [allowed: topFlights|price|departureTime|arrivalTime|duration|emissions]")
	_ = cmd.RegisterFlagCompletionFunc("sort-by", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"topFlights", "price", "departureTime", "arrivalTime", "duration", "emissions"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_stopsVar, "stops", "", "stops Stops: Restrict the number of stops (layovers) in the flight itinerary.\n [allowed: nonStop|oneStopOrFewer|twoStopsOrFewer]")
	_ = cmd.RegisterFlagCompletionFunc("stops", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"nonStop", "oneStopOrFewer", "twoStopsOrFewer"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_travelClassVar, "travel-class", "", "travelClass Travel Class: The travel class for the flight (Economy, Premium Economy, Business, or First).\n [allowed: economy|premiumEconomy|business|first]")
	_ = cmd.RegisterFlagCompletionFunc("travel-class", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"economy", "premiumEconomy", "business", "first"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_typeVar, "type", "", "type Flight Type: Specifies the type of flight. Options:\n\n  - `roundTrip` (default)\n  - `oneWay`\n  - `multiCity` (requires `multiCityJson` for flight details)\n\nFor round trips, retrieve return flight details with a separate request using `departureToken`.\n [allowed: roundTrip|oneWay|multiCity]")
	_ = cmd.RegisterFlagCompletionFunc("type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"roundTrip", "oneWay", "multiCity"}, cobra.ShellCompDirectiveNoFileComp
	})

	return cmd
}

func init() {
	RegisterAPICommand("google_travel", "Google Travel", newGoogleFlightsCmd())
}
