// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newShopifyCollectionsCmd() *cobra.Command {
	var p_limitVar int
	var p_pageVar int
	var p_urlVar string

	cmd := &cobra.Command{
		Use:   "shopify-collections",
		Short: "Shopify Collections API  (5 credits/call)",
		Long:  "The Shopify Collections API allows users to retrieve information about collections in a Shopify store, including details such as title, handle, description, and image.\n\nEndpoint: GET https://api.hasdata.com/scrape/shopify/collections\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("limit") {
				params.Set("limit", strconv.Itoa(p_limitVar))
			}
			if c.Flags().Changed("page") {
				params.Set("page", strconv.Itoa(p_pageVar))
			}
			params.Set("url", p_urlVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/shopify/collections", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().IntVar(&p_limitVar, "limit", 10, "limit Results Limit: The maximum number of collections to retrieve. Must be between 1 and 250.")
	cmd.Flags().IntVar(&p_pageVar, "page", 0, "page Page: The page number of the results to retrieve. Must be a positive integer.")
	cmd.Flags().StringVar(&p_urlVar, "url", "https://b2bdemoexperience.myshopify.com", "url Store URL: The URL of the Shopify store. For example, 'https://b2bdemoexperience.myshopify.com'. (required)")
	_ = cmd.MarkFlagRequired("url")

	return cmd
}

func init() {
	RegisterAPICommand("shopify", "Shopify", newShopifyCollectionsCmd())
}
