// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newRedfinListingCmd() *cobra.Command {
	var p_keywordVar string
	var p_pageVar float64
	var p_typeVar string

	cmd := &cobra.Command{
		Use:   "redfin-listing",
		Short: "Redfin Listing API  (5 credits/call)",
		Long:  "The Redfin Listing API allows you to retrieve real estate listings from Redfin based on various search parameters.\n\nEndpoint: GET https://api.hasdata.com/scrape/redfin/listing\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("type") {
				if err := validateEnumString("type", p_typeVar, []string{"forSale", "forRent", "sold"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("keyword", p_keywordVar)
			if c.Flags().Changed("page") {
				params.Set("page", strconv.FormatFloat(p_pageVar, 'f', -1, 64))
			}
			params.Set("type", p_typeVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/redfin/listing", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_keywordVar, "keyword", "33321", "keyword Location: The zipcode used to search for listings. (required)")
	_ = cmd.MarkFlagRequired("keyword")
	cmd.Flags().Float64Var(&p_pageVar, "page", 0, "page Page: The page number of the results to retrieve.")
	cmd.Flags().StringVar(&p_typeVar, "type", "forSale", "type Listing Type: The type of listing. [allowed: forSale|forRent|sold] (required)")
	_ = cmd.MarkFlagRequired("type")
	_ = cmd.RegisterFlagCompletionFunc("type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"forSale", "forRent", "sold"}, cobra.ShellCompDirectiveNoFileComp
	})

	return cmd
}

func init() {
	RegisterAPICommand("redfin", "Redfin", newRedfinListingCmd())
}
