// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newGoogleTrendsCmd() *cobra.Command {
	var p_catVar string
	var p_dataTypeVar string
	var p_dateVar string
	var p_geoVar string
	var p_gpropVar string
	var p_qVar string
	var p_regionVar string
	var p_tzVar float64

	cmd := &cobra.Command{
		Use:   "google-trends",
		Short: "Google Trends API  (5 credits/call)",
		Long:  "The Google Trends API provides real-time access to Google Trends data, offering insights into the popularity of search terms over time and across regions.\n\nEndpoint: GET https://api.hasdata.com/scrape/google-trends/search\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("cat") {
				params.Set("cat", p_catVar)
			}
			if c.Flags().Changed("data-type") {
				params.Set("dataType", p_dataTypeVar)
			}
			if c.Flags().Changed("date") {
				params.Set("date", p_dateVar)
			}
			if c.Flags().Changed("geo") {
				params.Set("geo", p_geoVar)
			}
			if c.Flags().Changed("gprop") {
				params.Set("gprop", p_gpropVar)
			}
			params.Set("q", p_qVar)
			if c.Flags().Changed("region") {
				params.Set("region", p_regionVar)
			}
			if c.Flags().Changed("tz") {
				params.Set("tz", strconv.FormatFloat(p_tzVar, 'f', -1, 64))
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/google-trends/search", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_catVar, "cat", "", "cat Category: Category of the search term. The default value is 0 (\"All categories\").")
	cmd.Flags().StringVar(&p_dataTypeVar, "data-type", "", "dataType Data Type: Defines the type of search to perform.\n\nAvailable options:\n  - `timeseries`: Interest over time (default). Accepts both single and multiple queries per search.\n  - `geoMap`: Interest by region. Accepts both single and multiple queries per search.\n  - `relatedTopics`: Related topics. Accepts only single query per search.\n  - `relatedQueries`: Related queries. Accepts only single query per search.\n")
	cmd.Flags().StringVar(&p_dateVar, "date", "", "date Date Range: Defines a date range for the search. Available options:\n\n- `now 1-H`: Past hour\n- `now 4-H`: Past 4 hours\n- `now 1-d`: Past day\n- `now 7-d`: Past 7 days\n- `today 1-m`: Past 30 days\n- `today 3-m`: Past 90 days\n- `today 12-m`: Past 12 months\n- `today 5-y`: Past 5 years\n- `all`: 2004 - present\n\nYou can also specify a custom date range using one of the following formats:\n\n- `yyyy-mm-dd yyyy-mm-dd` - (e.g. 2021-10-15 2022-05-25) for dates from 2004 to present.\n- `yyyy-mm-ddThh yyyy-mm-ddThh` - (e.g. 2022-05-19T10 2022-05-24T22) for dates with hours within a week range. The hours will be calculated based on the tz (time zone) parameter.\n")
	cmd.Flags().StringVar(&p_geoVar, "geo", "", "geo Location: Specifies the location for the search. Defaults to Worldwide if not set or empty.")
	cmd.Flags().StringVar(&p_gpropVar, "gprop", "", "gprop Google Property: Sorts results by a specific property. The default property is Web Search (applied when the gprop parameter is not set or empty).\n\nAvailable options:\n  - `images`: Image Search\n  - `news`: News Search\n  - `froogle`: Google Shopping\n  - `youtube`: YouTube Search\n")
	cmd.Flags().StringVar(&p_qVar, "q", "Coffee", "q Search Query: Specify the search term for which you want to retrieve trends data. (required)")
	_ = cmd.MarkFlagRequired("q")
	cmd.Flags().StringVar(&p_regionVar, "region", "", "region Region: Used to get more specific results when using \"Interest by region\" data type. Other data types do not accept this parameter. The default value depends on the geo location that is set.\n\nAvailable options:\n - `country`: Country\n - `region`: Subregion\n - `dma`: Metro\n - `city`: City\n\nNote: Not all region options will return results for every geo location.\n")
	cmd.Flags().Float64Var(&p_tzVar, "tz", 0, "tz Time Zone: Defines a time zone offset in minutes. The default value is 420 (Pacific Daylight Time (PDT): UTC-7). The valid range for this parameter is from -1439 to 1439.\n\nTo calculate the `tz` value for a specific time zone, you can use the time difference between UTC +0 and the desired time zone.\n\nExamples:\n- `420`: Pacific Daylight Time (PDT)\n- `60`: Central European Time (CET)\n- `-540`: Japan Standard Time\n")

	return cmd
}

func init() {
	RegisterAPICommand("google_trends", "Google Trends", newGoogleTrendsCmd())
}
