// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/pflag"
)

// jsonOrFile is a pflag.Value that accepts raw JSON, "@path" to read from a
// file, or "-" to read from stdin. The underlying json.RawMessage is only
// populated if the flag was explicitly set.
type jsonOrFile struct {
	raw     json.RawMessage
	changed bool
}

func (j *jsonOrFile) Set(s string) error {
	var data []byte
	switch {
	case s == "-":
		b, err := io.ReadAll(os.Stdin)
		if err != nil {
			return err
		}
		data = b
	case strings.HasPrefix(s, "@"):
		b, err := os.ReadFile(s[1:])
		if err != nil {
			return err
		}
		data = b
	default:
		data = []byte(s)
	}
	if len(data) == 0 {
		return fmt.Errorf("empty JSON")
	}
	if !json.Valid(data) {
		return fmt.Errorf("invalid JSON")
	}
	j.raw = json.RawMessage(data)
	j.changed = true
	return nil
}

func (j *jsonOrFile) String() string {
	if len(j.raw) == 0 {
		return ""
	}
	return string(j.raw)
}

func (j *jsonOrFile) Type() string { return "json" }

// Ensure type implements pflag.Value at compile time.
var _ pflag.Value = (*jsonOrFile)(nil)

// parseKVs turns a list of "key=value" strings into a map. Splits on the FIRST
// '=' only, so values containing '=' (cookies, tokens) round-trip correctly.
func parseKVs(items []string) (map[string]string, error) {
	out := make(map[string]string, len(items))
	for _, it := range items {
		idx := strings.IndexByte(it, '=')
		if idx < 0 {
			return nil, fmt.Errorf("expected key=value, got %q", it)
		}
		out[it[:idx]] = it[idx+1:]
	}
	return out, nil
}

// mergeKVOverride merges "k=v" items on top of a JSON object base; base values
// are overwritten by kv items per key.
func mergeKVOverride(base json.RawMessage, items []string) (map[string]any, error) {
	out := map[string]any{}
	if len(base) > 0 {
		if err := json.Unmarshal(base, &out); err != nil {
			return nil, err
		}
	}
	kv, err := parseKVs(items)
	if err != nil {
		return nil, err
	}
	for k, v := range kv {
		out[k] = v
	}
	return out, nil
}

// validateEnumString errors if val is not in allowed.
func validateEnumString(name, val string, allowed []string) error {
	for _, a := range allowed {
		if a == val {
			return nil
		}
	}
	return fmt.Errorf("--%s: %q not in allowed values %v", name, val, allowed)
}

// validateEnumStringSlice errors if any of vals is not in allowed.
func validateEnumStringSlice(name string, vals, allowed []string) error {
	for _, v := range vals {
		if err := validateEnumString(name, v, allowed); err != nil {
			return err
		}
	}
	return nil
}

// validateEnumInt errors if val is not in allowed.
func validateEnumInt(name string, val int, allowed []int) error {
	for _, a := range allowed {
		if a == val {
			return nil
		}
	}
	return fmt.Errorf("--%s: %d not in allowed values %v", name, val, allowed)
}
