// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newGlassdoorListingCmd() *cobra.Command {
	var p_domainVar string
	var p_keywordVar string
	var p_locationVar string
	var p_nextPageTokenVar string
	var p_sortVar string

	cmd := &cobra.Command{
		Use:   "glassdoor-listing",
		Short: "Glassdoor Listing API  (5 credits/call)",
		Long:  "The Glassdoor Listing API allows you to retrieve job listings from Glassdoor based on various search parameters.\n\nEndpoint: GET https://api.hasdata.com/scrape/glassdoor/listing\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("domain") {
				if err := validateEnumString("domain", p_domainVar, []string{"www.glassdoor.com.ar", "www.glassdoor.com.au", "www.glassdoor.at", "nl.glassdoor.be", "fr.glassdoor.be", "www.glassdoor.com.br", "www.glassdoor.ca", "fr.glassdoor.ca", "www.glassdoor.fr", "www.glassdoor.de", "www.glassdoor.com.hk", "www.glassdoor.co.in", "www.glassdoor.ie", "www.glassdoor.it", "www.glassdoor.com.mx", "www.glassdoor.nl", "www.glassdoor.co.nz", "www.glassdoor.sg", "www.glassdoor.es", "de.glassdoor.ch", "fr.glassdoor.ch", "www.glassdoor.co.uk"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("sort") {
				if err := validateEnumString("sort", p_sortVar, []string{"recent", "relevant"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("domain") {
				params.Set("domain", p_domainVar)
			}
			params.Set("keyword", p_keywordVar)
			params.Set("location", p_locationVar)
			if c.Flags().Changed("next-page-token") {
				params.Set("nextPageToken", p_nextPageTokenVar)
			}
			if c.Flags().Changed("sort") {
				params.Set("sort", p_sortVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/glassdoor/listing", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_domainVar, "domain", "www.glassdoor.com", "domain: The domain of the Glassdoor site (optional). [allowed: www.glassdoor.com.ar|www.glassdoor.com.au|www.glassdoor.at|nl.glassdoor.be|fr.glassdoor.be|www.glassdoor.com.br|www.glassdoor.ca|fr.glassdoor.ca|www.glassdoor.fr|www.glassdoor.de|www.glassdoor.com.hk|www.glassdoor.co.in|www.glassdoor.ie|www.glassdoor.it|www.glassdoor.com.mx|www.glassdoor.nl|www.glassdoor.co.nz|www.glassdoor.sg|www.glassdoor.es|de.glassdoor.ch|fr.glassdoor.ch|www.glassdoor.co.uk]")
	_ = cmd.RegisterFlagCompletionFunc("domain", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"www.glassdoor.com.ar", "www.glassdoor.com.au", "www.glassdoor.at", "nl.glassdoor.be", "fr.glassdoor.be", "www.glassdoor.com.br", "www.glassdoor.ca", "fr.glassdoor.ca", "www.glassdoor.fr", "www.glassdoor.de", "www.glassdoor.com.hk", "www.glassdoor.co.in", "www.glassdoor.ie", "www.glassdoor.it", "www.glassdoor.com.mx", "www.glassdoor.nl", "www.glassdoor.co.nz", "www.glassdoor.sg", "www.glassdoor.es", "de.glassdoor.ch", "fr.glassdoor.ch", "www.glassdoor.co.uk"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_keywordVar, "keyword", "software engineer", "keyword Search Query: The keyword used to search for job listings. (required)")
	_ = cmd.MarkFlagRequired("keyword")
	cmd.Flags().StringVar(&p_locationVar, "location", "New York, NY", "location Location: The location to search for job listings. (required)")
	_ = cmd.MarkFlagRequired("location")
	cmd.Flags().StringVar(&p_nextPageTokenVar, "next-page-token", "", "nextPageToken Next Page Token: Token for fetching the next page of jobs.")
	cmd.Flags().StringVar(&p_sortVar, "sort", "recent", "sort Sort By: The sorting option for the search results. [allowed: recent|relevant]")
	_ = cmd.RegisterFlagCompletionFunc("sort", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"recent", "relevant"}, cobra.ShellCompDirectiveNoFileComp
	})

	return cmd
}

func init() {
	RegisterAPICommand("job", "Jobs", newGlassdoorListingCmd())
}
