// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newInstagramCommentsCmd() *cobra.Command {
	var p_nextPageTokenVar string
	var p_urlVar string

	cmd := &cobra.Command{
		Use:   "instagram-comments",
		Short: "Instagram Comments Scraper API  (10 credits/call)",
		Long:  "The Instagram Comments Scraper API returns the comments on a public Instagram post or reel by its URL. The first page also returns the post itself with caption, likes and comments counts, and every image or video in the post, including all carousel items. Each comment includes its text, like count, reply count, timestamp, and author (with a link to the author's profile). Results are paginated with a token.\n\nEndpoint: GET https://api.hasdata.com/scrape/instagram/comments\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("next-page-token") {
				params.Set("nextPageToken", p_nextPageTokenVar)
			}
			params.Set("url", p_urlVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/instagram/comments", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_nextPageTokenVar, "next-page-token", "", "nextPageToken Next Page Token: Defines the next page token. Use the `nextPageToken` value returned by the previous response. Omit it to fetch the first page.")
	cmd.Flags().StringVar(&p_urlVar, "url", "https://www.instagram.com/instagram/p/Ddjis3vETcP/", "url Post URL: The URL of the Instagram post or reel, for example `https://www.instagram.com/p/Ddjis3vETcP/` or `https://www.instagram.com/instagram/reel/DcymgItMFao/`. (required)")
	_ = cmd.MarkFlagRequired("url")

	return cmd
}

func init() {
	RegisterAPICommand("social", "Social", newInstagramCommentsCmd())
}
