// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newYellowpagesSearchCmd() *cobra.Command {
	var p_domainVar string
	var p_keywordVar string
	var p_locationVar string
	var p_pageVar int
	var p_sortVar string

	cmd := &cobra.Command{
		Use:   "yellowpages-search",
		Short: "YellowPages Search API  (5 credits/call)",
		Long:  "The YellowPages Search API allows users to get results from the YellowPages search page. This API enables searching for businesses by keyword and location.\n\nEndpoint: GET https://api.hasdata.com/scrape/yellowpages/search\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("domain") {
				if err := validateEnumString("domain", p_domainVar, []string{"www.yellowpages.com", "www.yellowpages.ca"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("sort") {
				if err := validateEnumString("sort", p_sortVar, []string{"default", "distance", "averageRating", "name"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("domain") {
				params.Set("domain", p_domainVar)
			}
			params.Set("keyword", p_keywordVar)
			params.Set("location", p_locationVar)
			if c.Flags().Changed("page") {
				params.Set("page", strconv.Itoa(p_pageVar))
			}
			if c.Flags().Changed("sort") {
				params.Set("sort", p_sortVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/yellowpages/search", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_domainVar, "domain", "", "domain Domain: YellowPages domain to use. Default is `www.yellowpages.com`. [allowed: www.yellowpages.com|www.yellowpages.ca]")
	_ = cmd.RegisterFlagCompletionFunc("domain", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"www.yellowpages.com", "www.yellowpages.ca"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_keywordVar, "keyword", "Plumbers", "keyword Search Query: The search term for which to get the search results. (required)")
	_ = cmd.MarkFlagRequired("keyword")
	cmd.Flags().StringVar(&p_locationVar, "location", "New York, NY", "location Location: The location where to search for businesses with the given keyword. (required)")
	_ = cmd.MarkFlagRequired("location")
	cmd.Flags().IntVar(&p_pageVar, "page", 0, "page Page: The page number of the results to retrieve.")
	cmd.Flags().StringVar(&p_sortVar, "sort", "default", "sort Sort By: The sorting option for the search results. [allowed: default|distance|averageRating|name]")
	_ = cmd.RegisterFlagCompletionFunc("sort", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"default", "distance", "averageRating", "name"}, cobra.ShellCompDirectiveNoFileComp
	})

	return cmd
}

func init() {
	RegisterAPICommand("business", "Business", newYellowpagesSearchCmd())
}
