// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newWebScrapingCmd() *cobra.Command {
	var p_aiExtractRulesVar jsonOrFile
	var p_blockAdsVar bool
	var p_blockAdsVarNeg bool
	var p_blockResourcesVar bool
	var p_blockResourcesVarNeg bool
	var p_blockUrlsVar []string
	var p_excludeTagsVar []string
	var p_extractEmailsVar bool
	var p_extractEmailsVarNeg bool
	var p_extractLinksVar bool
	var p_extractRulesVarKV []string
	var p_extractRulesVarJSON jsonOrFile
	var p_headersVarKV []string
	var p_headersVarJSON jsonOrFile
	var p_includeOnlyTagsVar []string
	var p_jsRenderingVar bool
	var p_jsRenderingVarNeg bool
	var p_jsScenarioVar jsonOrFile
	var p_outputFormatVar []string
	var p_proxyCountryVar string
	var p_proxyTypeVar string
	var p_removeBase64ImagesVar bool
	var p_screenshotVar bool
	var p_screenshotVarNeg bool
	var p_urlVar string
	var p_waitVar int
	var p_waitForVar string

	cmd := &cobra.Command{
		Use:   "web-scraping",
		Short: "Web Scraping API  (10 credits/call)",
		Long:  "If you're tired of fiddling with proxies, headless browsers and captchas, it's time to use Scrape-it.cloud. Send the desired URL and we'll return an HTML response. Work without headaches and worries about blocking.\n\nEndpoint: POST https://api.hasdata.com/scrape/web\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("block-ads") && c.Flags().Changed("no-"+"block-ads") {
				return fmt.Errorf("cannot set both --%s and --no-%s", "block-ads", "block-ads")
			}
			if c.Flags().Changed("block-resources") && c.Flags().Changed("no-"+"block-resources") {
				return fmt.Errorf("cannot set both --%s and --no-%s", "block-resources", "block-resources")
			}
			if c.Flags().Changed("extract-emails") && c.Flags().Changed("no-"+"extract-emails") {
				return fmt.Errorf("cannot set both --%s and --no-%s", "extract-emails", "extract-emails")
			}
			if c.Flags().Changed("js-rendering") && c.Flags().Changed("no-"+"js-rendering") {
				return fmt.Errorf("cannot set both --%s and --no-%s", "js-rendering", "js-rendering")
			}
			if c.Flags().Changed("output-format") {
				if err := validateEnumStringSlice("output-format", p_outputFormatVar, []string{"json", "html", "markdown", "text"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("proxy-country") {
				if err := validateEnumString("proxy-country", p_proxyCountryVar, []string{"US", "UK", "DE", "IE", "FR", "IT", "SE", "BR", "CA", "JP", "SG", "IN", "ID"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("proxy-type") {
				if err := validateEnumString("proxy-type", p_proxyTypeVar, []string{"datacenter", "residential"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("screenshot") && c.Flags().Changed("no-"+"screenshot") {
				return fmt.Errorf("cannot set both --%s and --no-%s", "screenshot", "screenshot")
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			body := map[string]any{}
			if p_aiExtractRulesVar.changed {
				var v any
				if err := json.Unmarshal(p_aiExtractRulesVar.raw, &v); err != nil {
					return fmt.Errorf("--ai-extract-rules-json: %w", err)
				}
				body["aiExtractRules"] = v
			}
			{
				val := p_blockAdsVar
				changed := c.Flags().Changed("block-ads")
				if c.Flags().Changed("no-" + "block-ads") {
					val = !p_blockAdsVarNeg
					changed = true
				}
				if changed {
					body["blockAds"] = val
				}
			}
			{
				val := p_blockResourcesVar
				changed := c.Flags().Changed("block-resources")
				if c.Flags().Changed("no-" + "block-resources") {
					val = !p_blockResourcesVarNeg
					changed = true
				}
				if changed {
					body["blockResources"] = val
				}
			}
			if c.Flags().Changed("block-urls") {
				body["blockUrls"] = p_blockUrlsVar
			}
			if c.Flags().Changed("exclude-tags") {
				body["excludeTags"] = p_excludeTagsVar
			}
			{
				val := p_extractEmailsVar
				changed := c.Flags().Changed("extract-emails")
				if c.Flags().Changed("no-" + "extract-emails") {
					val = !p_extractEmailsVarNeg
					changed = true
				}
				if changed {
					body["extractEmails"] = val
				}
			}
			if c.Flags().Changed("extract-links") {
				body["extractLinks"] = p_extractLinksVar
			}
			if p_extractRulesVarJSON.changed || c.Flags().Changed("extract-rules") {
				merged, mErr := mergeKVOverride(p_extractRulesVarJSON.raw, p_extractRulesVarKV)
				if mErr != nil {
					return fmt.Errorf("--extract-rules: %w", mErr)
				}
				body["extractRules"] = merged
			}
			if p_headersVarJSON.changed || c.Flags().Changed("headers") {
				merged, mErr := mergeKVOverride(p_headersVarJSON.raw, p_headersVarKV)
				if mErr != nil {
					return fmt.Errorf("--headers: %w", mErr)
				}
				body["headers"] = merged
			}
			if c.Flags().Changed("include-only-tags") {
				body["includeOnlyTags"] = p_includeOnlyTagsVar
			}
			{
				val := p_jsRenderingVar
				changed := c.Flags().Changed("js-rendering")
				if c.Flags().Changed("no-" + "js-rendering") {
					val = !p_jsRenderingVarNeg
					changed = true
				}
				if changed {
					body["jsRendering"] = val
				}
			}
			if p_jsScenarioVar.changed {
				var v any
				if err := json.Unmarshal(p_jsScenarioVar.raw, &v); err != nil {
					return fmt.Errorf("--js-scenario-json: %w", err)
				}
				body["jsScenario"] = v
			}
			if c.Flags().Changed("output-format") {
				body["outputFormat"] = p_outputFormatVar
			}
			if c.Flags().Changed("proxy-country") {
				body["proxyCountry"] = p_proxyCountryVar
			}
			if c.Flags().Changed("proxy-type") {
				body["proxyType"] = p_proxyTypeVar
			}
			if c.Flags().Changed("remove-base64-images") {
				body["removeBase64Images"] = p_removeBase64ImagesVar
			}
			{
				val := p_screenshotVar
				changed := c.Flags().Changed("screenshot")
				if c.Flags().Changed("no-" + "screenshot") {
					val = !p_screenshotVarNeg
					changed = true
				}
				if changed {
					body["screenshot"] = val
				}
			}
			body["url"] = p_urlVar
			if c.Flags().Changed("wait") {
				body["wait"] = p_waitVar
			}
			if c.Flags().Changed("wait-for") {
				body["waitFor"] = p_waitForVar
			}
			resp, err := cli.Do(ctx, "POST", "https://api.hasdata.com/scrape/web", nil, body)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().Var(&p_aiExtractRulesVar, "ai-extract-rules-json", "aiExtractRules AI Extraction Rules: Defines custom rules for AI-based data extraction using LLMs. This enables the system to extract structured data directly from the HTML of the page. Each key in the object represents a desired output field name, and the value specifies its type and optional description to guide the AI.\n\nSupported types:\n- `string`: plain text value\n- `number`: numeric value\n- `boolean`: true/false\n- `list`: an array of values\n- `item`: a nested object with its own structure defined under `output`\n — accepts raw JSON, @file, or - (stdin)")
	cmd.Flags().BoolVar(&p_blockAdsVar, "block-ads", true, "blockAds Block ADS: Whether to block ads.")
	cmd.Flags().BoolVar(&p_blockAdsVarNeg, "no-"+"block-ads", false, "disable --block-ads")
	cmd.Flags().BoolVar(&p_blockResourcesVar, "block-resources", true, "blockResources Block Images And CSS: Whether to block loading of resources like images and stylesheets.")
	cmd.Flags().BoolVar(&p_blockResourcesVarNeg, "no-"+"block-resources", false, "disable --block-resources")
	cmd.Flags().StringSliceVar(&p_blockUrlsVar, "block-urls", nil, "blockUrls Block URLs: List of URLs to block.")
	cmd.Flags().StringSliceVar(&p_excludeTagsVar, "exclude-tags", nil, "excludeTags Exclude Tags: The `excludeTags` parameter accepts an array of valid CSS selectors.\nElements matching these selectors will be removed from the final output.\nEach value must be a valid `querySelectorAll` selector. This can be used to remove ads, scripts, or\nother unwanted sections.\n")
	cmd.Flags().BoolVar(&p_extractEmailsVar, "extract-emails", true, "extractEmails Extract Emails: Extract emails from the page.")
	cmd.Flags().BoolVar(&p_extractEmailsVarNeg, "no-"+"extract-emails", false, "disable --extract-emails")
	cmd.Flags().BoolVar(&p_extractLinksVar, "extract-links", false, "extractLinks Extract Links: Extract links from the page.")
	cmd.Flags().StringArrayVar(&p_extractRulesVarKV, "extract-rules", nil, "extractRules Extraction Rules: Rules for extracting specific data from the page. For example: `{ \"title\": \"h1\", \"link_href\": \"a#link @href\", \"page_text\": \"body\" }`\n")
	cmd.Flags().Var(&p_extractRulesVarJSON, "extract-rules-json", "extractRules Extraction Rules as raw JSON, @file, or -")
	cmd.Flags().StringArrayVar(&p_headersVarKV, "headers", nil, "headers Headers: Optional custom headers to send with the request.")
	cmd.Flags().Var(&p_headersVarJSON, "headers-json", "headers Headers as raw JSON, @file, or -")
	cmd.Flags().StringSliceVar(&p_includeOnlyTagsVar, "include-only-tags", nil, "includeOnlyTags Include Only Tags: The `includeOnlyTags` parameter accepts an array of valid CSS selectors.\nWhen specified, only the elements matching these selectors will be included in the response content.\nEach value must be a valid `querySelectorAll` selector. Useful for extracting specific parts of the document.\n")
	cmd.Flags().BoolVar(&p_jsRenderingVar, "js-rendering", true, "jsRendering JS Rendering: Enable JavaScript rendering.")
	cmd.Flags().BoolVar(&p_jsRenderingVarNeg, "no-"+"js-rendering", false, "disable --js-rendering")
	cmd.Flags().Var(&p_jsScenarioVar, "js-scenario-json", "jsScenario JavaScript Execution: Enables custom JavaScript interactions on the target webpage during scraping. It's an array where each object defines a specific action or step. These actions can include clicking elements, waiting for elements, executing custom scripts, and more. Key actions within this field include:\n\n- `evaluate`: Run custom JavaScript code on the page.\n- `click`: Click on an element specified by a CSS selector.\n- `wait`: Pause for a set duration (in milliseconds).\n- `waitFor`: Delay until a specific element appears.\n- `waitForAndClick`: Combine waiting for an element and then clicking it.\n- `scrollX`, `scrollY`: Scroll to specified positions on the page.\n- `fill`: Enter values into input fields identified by CSS selectors.\n\nActions are executed sequentially.\n — accepts raw JSON, @file, or - (stdin)")
	cmd.Flags().StringSliceVar(&p_outputFormatVar, "output-format", nil, "outputFormat Output Format: The outputFormat parameter specifies the desired response format: `html`, `text`, `markdown`, or `json`. If only one of `html`, `text`, or `markdown` is provided, the API returns the response in that format. If multiple formats are specified, the API returns a JSON response with keys for each requested format. If `json` is included with any other format, the API returns a JSON response with keys for the other specified formats.\n")
	_ = cmd.RegisterFlagCompletionFunc("output-format", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"json", "html", "markdown", "text"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_proxyCountryVar, "proxy-country", "US", "proxyCountry Proxy Country: Optional proxy country code. [allowed: US|UK|DE|IE|FR|IT|SE|BR|CA|JP|SG|IN|ID]")
	_ = cmd.RegisterFlagCompletionFunc("proxy-country", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"US", "UK", "DE", "IE", "FR", "IT", "SE", "BR", "CA", "JP", "SG", "IN", "ID"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_proxyTypeVar, "proxy-type", "datacenter", "proxyType Proxy Type: Type of proxy to use. [allowed: datacenter|residential]")
	_ = cmd.RegisterFlagCompletionFunc("proxy-type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"datacenter", "residential"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().BoolVar(&p_removeBase64ImagesVar, "remove-base64-images", false, "removeBase64Images Remove Base64 Images: If set to `true`, any images embedded as base64-encoded strings will be removed from the output.\nUseful for reducing response size or when base64 images are not needed.\n")
	cmd.Flags().BoolVar(&p_screenshotVar, "screenshot", true, "screenshot Screenshot: Whether to take a screenshot of the page.")
	cmd.Flags().BoolVar(&p_screenshotVarNeg, "no-"+"screenshot", false, "disable --screenshot")
	cmd.Flags().StringVar(&p_urlVar, "url", "https://example.com", "url URL: The URL of the web page to scrape. (required)")
	_ = cmd.MarkFlagRequired("url")
	cmd.Flags().IntVar(&p_waitVar, "wait", 0, "wait Wait For A Time: Time in milliseconds to wait after the page load.")
	cmd.Flags().StringVar(&p_waitForVar, "wait-for", "", "waitFor Wait For CSS Selector: CSS selector to wait for before scraping.")

	return cmd
}

func init() {
	RegisterAPICommand("web_scraping", "Web Scraping", newWebScrapingCmd())
}
