// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newInstagramProfileCmd() *cobra.Command {
	var p_handleVar string

	cmd := &cobra.Command{
		Use:   "instagram-profile",
		Short: "Instagram Profile API  (5 credits/call)",
		Long:  "The Instagram Profile API lets you retrieve public profile information for a specific Instagram account using its handle. It returns data such as bio, followers, following, posts count, and other visible profile details.\n\nEndpoint: GET https://api.hasdata.com/scrape/instagram/profile\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("handle", p_handleVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/instagram/profile", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_handleVar, "handle", "hasdatadotcom", "handle Instagram Handle: The Instagram username of the profile you want to scrape, without the `@` symbol. (required)")
	_ = cmd.MarkFlagRequired("handle")

	return cmd
}

func init() {
	RegisterAPICommand("instagram", "Instagram", newInstagramProfileCmd())
}
