// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newGoogleMapsPostsCmd() *cobra.Command {
	var p_dataIdVar string
	var p_hlVar string
	var p_nextPageTokenVar string
	var p_placeIdVar string

	cmd := &cobra.Command{
		Use:   "google-maps-posts",
		Short: "Google Maps Posts API  (10 credits/call)",
		Long:  "The Google Maps Posts API provides access to posts (offers, events, announcements) published by businesses on their Google Maps listings, identified by data ID or place ID.\n\nEndpoint: GET https://api.hasdata.com/scrape/google-maps/posts\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("data-id") {
				params.Set("dataId", p_dataIdVar)
			}
			if c.Flags().Changed("hl") {
				params.Set("hl", p_hlVar)
			}
			if c.Flags().Changed("next-page-token") {
				params.Set("nextPageToken", p_nextPageTokenVar)
			}
			if c.Flags().Changed("place-id") {
				params.Set("placeId", p_placeIdVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/google-maps/posts", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_dataIdVar, "data-id", "0x873312ae759b4d15:0x1f38a9bec9912029", "dataId Data ID: Google Maps data ID.")
	cmd.Flags().StringVar(&p_hlVar, "hl", "", "hl Language: The two-letter language code for the language you want to use for the search.")
	cmd.Flags().StringVar(&p_nextPageTokenVar, "next-page-token", "", "nextPageToken Next Page Token: Defines the next page token. It is used for retrieving the next page results.")
	cmd.Flags().StringVar(&p_placeIdVar, "place-id", "", "placeId Place ID: Unique reference to a place on a Google Map. Either dataId or placeId should be set.")

	return cmd
}

func init() {
	RegisterAPICommand("google_maps", "Google Maps", newGoogleMapsPostsCmd())
}
