// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newGoogleMapsPhotosCmd() *cobra.Command {
	var p_categoryIdVar string
	var p_dataIdVar string
	var p_hlVar string
	var p_nextPageTokenVar string
	var p_placeIdVar string

	cmd := &cobra.Command{
		Use:   "google-maps-photos",
		Short: "Google Maps Photos API  (5 credits/call)",
		Long:  "The Google Maps Photos API returns photos for a place on Google Maps. Use either dataId or placeId with optional language, category, and pagination.\n\nEndpoint: GET https://api.hasdata.com/scrape/google-maps/photos\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("category-id") {
				params.Set("categoryId", p_categoryIdVar)
			}
			if c.Flags().Changed("data-id") {
				params.Set("dataId", p_dataIdVar)
			}
			if c.Flags().Changed("hl") {
				params.Set("hl", p_hlVar)
			}
			if c.Flags().Changed("next-page-token") {
				params.Set("nextPageToken", p_nextPageTokenVar)
			}
			if c.Flags().Changed("place-id") {
				params.Set("placeId", p_placeIdVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/google-maps/photos", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_categoryIdVar, "category-id", "", "categoryId Category ID: Filters photos by category.")
	cmd.Flags().StringVar(&p_dataIdVar, "data-id", "0x80cc0654bd27e08d:0xb1c2554442d42e8d", "dataId Data ID: Google Maps data ID. Either dataId or placeId should be set.")
	cmd.Flags().StringVar(&p_hlVar, "hl", "", "hl Language: The two-letter language code for the language you want to use for the search.")
	cmd.Flags().StringVar(&p_nextPageTokenVar, "next-page-token", "", "nextPageToken Next Page Token: Token for fetching the next page of photos.")
	cmd.Flags().StringVar(&p_placeIdVar, "place-id", "", "placeId Place ID: Unique reference to a place on Google Maps. Either dataId or placeId should be set.")

	return cmd
}

func init() {
	RegisterAPICommand("google_maps", "Google Maps", newGoogleMapsPhotosCmd())
}
