// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newYelpReviewsCmd() *cobra.Command {
	var p_domainVar string
	var p_languageCodeVar string
	var p_nextPageTokenVar string
	var p_notRecommendedVar bool
	var p_numVar int
	var p_placeIdVar string
	var p_queryVar string
	var p_ratingVar string
	var p_sortByVar string
	var p_startVar int

	cmd := &cobra.Command{
		Use:   "yelp-reviews",
		Short: "Yelp Reviews Scraper API  (10 credits/call)",
		Long:  "The Yelp Reviews Scraper API allows users to retrieve the review feed of a specific place on Yelp, with filtering by rating, language and keyword.\n\nEndpoint: GET https://api.hasdata.com/scrape/yelp/reviews\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("domain") {
				if err := validateEnumString("domain", p_domainVar, []string{"www.yelp.com", "www.yelp.co.uk", "www.yelp.ca", "www.yelp.com.au", "ms.yelp.my", "www.yelp.cz", "www.yelp.dk", "www.yelp.de", "www.yelp.at", "de.yelp.ch", "en.yelp.be", "en.yelp.com.hk", "en.yelp.my", "www.yelp.co.nz", "en.yelp.com.ph", "www.yelp.ie", "www.yelp.com.sg", "en.yelp.ch", "www.yelp.com.ar", "www.yelp.cl", "www.yelp.es", "www.yelp.com.mx", "fil.yelp.com.ph", "fr.yelp.be", "fr.yelp.ca", "www.yelp.fr", "fr.yelp.ch", "www.yelp.it", "it.yelp.ch", "nl.yelp.be", "www.yelp.nl", "www.yelp.no", "www.yelp.pl", "www.yelp.com.br", "www.yelp.pt", "fi.yelp.fi", "sv.yelp.fi", "www.yelp.com.tr", "www.yelp.co.jp", "zh.yelp.com.hk", "www.yelp.com.tw"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("sort-by") {
				if err := validateEnumString("sort-by", p_sortByVar, []string{"relevanceDesc", "dateDesc", "dateAsc", "ratingDesc", "ratingAsc", "elitesDesc"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("domain") {
				params.Set("domain", p_domainVar)
			}
			if c.Flags().Changed("language-code") {
				params.Set("languageCode", p_languageCodeVar)
			}
			if c.Flags().Changed("next-page-token") {
				params.Set("nextPageToken", p_nextPageTokenVar)
			}
			if c.Flags().Changed("not-recommended") {
				params.Set("notRecommended", strconv.FormatBool(p_notRecommendedVar))
			}
			if c.Flags().Changed("num") {
				params.Set("num", strconv.Itoa(p_numVar))
			}
			params.Set("placeId", p_placeIdVar)
			if c.Flags().Changed("query") {
				params.Set("query", p_queryVar)
			}
			if c.Flags().Changed("rating") {
				params.Set("rating", p_ratingVar)
			}
			if c.Flags().Changed("sort-by") {
				params.Set("sortBy", p_sortByVar)
			}
			if c.Flags().Changed("start") {
				params.Set("start", strconv.Itoa(p_startVar))
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/yelp/reviews", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_domainVar, "domain", "", "domain Domain: Yelp domain to use. Default is `www.yelp.com`. [allowed: www.yelp.com|www.yelp.co.uk|www.yelp.ca|www.yelp.com.au|ms.yelp.my|www.yelp.cz|www.yelp.dk|www.yelp.de|www.yelp.at|de.yelp.ch|en.yelp.be|en.yelp.com.hk|en.yelp.my|www.yelp.co.nz|en.yelp.com.ph|www.yelp.ie|www.yelp.com.sg|en.yelp.ch|www.yelp.com.ar|www.yelp.cl|www.yelp.es|www.yelp.com.mx|fil.yelp.com.ph|fr.yelp.be|fr.yelp.ca|www.yelp.fr|fr.yelp.ch|www.yelp.it|it.yelp.ch|nl.yelp.be|www.yelp.nl|www.yelp.no|www.yelp.pl|www.yelp.com.br|www.yelp.pt|fi.yelp.fi|sv.yelp.fi|www.yelp.com.tr|www.yelp.co.jp|zh.yelp.com.hk|www.yelp.com.tw]")
	_ = cmd.RegisterFlagCompletionFunc("domain", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"www.yelp.com", "www.yelp.co.uk", "www.yelp.ca", "www.yelp.com.au", "ms.yelp.my", "www.yelp.cz", "www.yelp.dk", "www.yelp.de", "www.yelp.at", "de.yelp.ch", "en.yelp.be", "en.yelp.com.hk", "en.yelp.my", "www.yelp.co.nz", "en.yelp.com.ph", "www.yelp.ie", "www.yelp.com.sg", "en.yelp.ch", "www.yelp.com.ar", "www.yelp.cl", "www.yelp.es", "www.yelp.com.mx", "fil.yelp.com.ph", "fr.yelp.be", "fr.yelp.ca", "www.yelp.fr", "fr.yelp.ch", "www.yelp.it", "it.yelp.ch", "nl.yelp.be", "www.yelp.nl", "www.yelp.no", "www.yelp.pl", "www.yelp.com.br", "www.yelp.pt", "fi.yelp.fi", "sv.yelp.fi", "www.yelp.com.tr", "www.yelp.co.jp", "zh.yelp.com.hk", "www.yelp.com.tw"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_languageCodeVar, "language-code", "en", "languageCode Language: Language of the reviews to return, as a two-letter code (e.g., 'en', 'es', 'fr'). Defaults to en.")
	cmd.Flags().StringVar(&p_nextPageTokenVar, "next-page-token", "", "nextPageToken Next Page Token: Opaque cursor for the next page, taken verbatim from `pagination.nextPageToken` of the previous response. It carries both the offset and the page size, so passing it alone continues the feed where the last response ended. Keep the other filters (`sortBy`, `rating`, `languageCode`, `query`, `notRecommended`) identical across pages. Use either this or `start`, not both. Paginate until `pagination.hasNextPage` is false.\n")
	cmd.Flags().BoolVar(&p_notRecommendedVar, "not-recommended", false, "notRecommended Not Recommended: Returns the reviews Yelp does not currently recommend (filtered out of the main feed by its recommendation software) instead of the recommended ones. These reviews carry no photos, videos or reactions, and are paginated ten at a time. Defaults to false.\n")
	cmd.Flags().IntVar(&p_numVar, "num", 0, "num Number of Results: Number of reviews to return per page. The maximum is 49. Defaults to 49 for the recommended feed and to 10 when `notRecommended` is set. The response echoes it back as `pagination.num`.\n")
	cmd.Flags().StringVar(&p_placeIdVar, "place-id", "-4ofMtrD7pSpZIX5pnDkig", "placeId Place ID: The Yelp ID of the place. For example, '-4ofMtrD7pSpZIX5pnDkig'. Yelp IDs can be obtained from the Yelp Search Scraper API. (required)")
	_ = cmd.MarkFlagRequired("place-id")
	cmd.Flags().StringVar(&p_queryVar, "query", "", "query Search Query: Note: Yelp ignores the `rating` filter while searching, so a query returns matching reviews of every star rating. Free-text query to search within the reviews of the place.\n")
	cmd.Flags().StringVar(&p_ratingVar, "rating", "5,4", "rating Rating: Note: Yelp ignores this filter when `query` is set, so a search returns matching reviews of every star rating. Filters the reviews by star rating. Possible values are 5, 4, 3, 2 and 1. To return only five-star reviews, set it to `5`. To include several ratings, pass them comma-separated, for example `5,4,3`. When omitted, reviews with any rating are returned.\n")
	cmd.Flags().StringVar(&p_sortByVar, "sort-by", "", "sortBy Sort By: The order in which the reviews are returned. Defaults to relevanceDesc. [allowed: relevanceDesc|dateDesc|dateAsc|ratingDesc|ratingAsc|elitesDesc]")
	_ = cmd.RegisterFlagCompletionFunc("sort-by", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"relevanceDesc", "dateDesc", "dateAsc", "ratingDesc", "ratingAsc", "elitesDesc"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().IntVar(&p_startVar, "start", 0, "start Result Offset: Result offset for pagination. It skips the given number of reviews, so the step matches `num` (e.g., 0, 49, 98 for the recommended feed, or 0, 10, 20 when `notRecommended` is set). The response echoes it back as `pagination.start`. Cannot be combined with `nextPageToken`.\n")

	return cmd
}

func init() {
	RegisterAPICommand("business", "Business", newYelpReviewsCmd())
}
