// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newAmazonReviewsCmd() *cobra.Command {
	var p_asinVar string
	var p_domainVar string
	var p_formatVar string
	var p_languageVar string
	var p_mediaTypeVar string
	var p_pageVar int
	var p_reviewerTypeVar string
	var p_searchTermVar string
	var p_sortByVar string
	var p_starsVar string

	cmd := &cobra.Command{
		Use:    "amazon-reviews",
		Short:  "[deprecated] Amazon Reviews API  (5 credits/call)",
		Long:   "The Amazon Reviews API allows users to get product reviews from Amazon based on the specified ASIN and other optional parameters. This API enables retrieving detailed reviews about a specific product on Amazon.\n\nThis API is deprecated — Amazon Reviews API is currently unavailable because Amazon now requires login to access reviews..\n\nEndpoint: GET https://api.hasdata.com/scrape/amazon/reviews\nCost: 5 credits per call.",
		Args:   cobra.NoArgs,
		Hidden: true,
		PreRunE: func(c *cobra.Command, _ []string) error {
			fmt.Fprintln(c.ErrOrStderr(), "warning: this API is deprecated — Amazon Reviews API is currently unavailable because Amazon now requires login to access reviews.")
			if c.Flags().Changed("domain") {
				if err := validateEnumString("domain", p_domainVar, []string{"www.amazon.com", "www.amazon.de", "www.amazon.co.uk", "www.amazon.ae", "www.amazon.com.au", "www.amazon.com.be", "www.amazon.com.br", "www.amazon.ca", "www.amazon.eg", "www.amazon.es", "www.amazon.fr", "www.amazon.ie", "www.amazon.in", "www.amazon.it", "www.amazon.co.jp", "www.amazon.com.mx", "www.amazon.nl", "www.amazon.pl", "www.amazon.sa", "www.amazon.se", "www.amazon.sg", "www.amazon.com.tr", "www.amazon.co.za"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("format") {
				if err := validateEnumString("format", p_formatVar, []string{"allFormats", "currentFormat"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("media-type") {
				if err := validateEnumString("media-type", p_mediaTypeVar, []string{"allReviews", "mediaReviews"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("reviewer-type") {
				if err := validateEnumString("reviewer-type", p_reviewerTypeVar, []string{"allReviews", "verifiedPurchaseReviews"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("sort-by") {
				if err := validateEnumString("sort-by", p_sortByVar, []string{"helpful", "recent"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("stars") {
				if err := validateEnumString("stars", p_starsVar, []string{"allStars", "fiveStar", "fourStar", "threeStar", "twoStar", "oneStar", "positive", "critical"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("asin", p_asinVar)
			if c.Flags().Changed("domain") {
				params.Set("domain", p_domainVar)
			}
			if c.Flags().Changed("format") {
				params.Set("format", p_formatVar)
			}
			if c.Flags().Changed("language") {
				params.Set("language", p_languageVar)
			}
			if c.Flags().Changed("media-type") {
				params.Set("mediaType", p_mediaTypeVar)
			}
			if c.Flags().Changed("page") {
				params.Set("page", strconv.Itoa(p_pageVar))
			}
			if c.Flags().Changed("reviewer-type") {
				params.Set("reviewerType", p_reviewerTypeVar)
			}
			if c.Flags().Changed("search-term") {
				params.Set("searchTerm", p_searchTermVar)
			}
			if c.Flags().Changed("sort-by") {
				params.Set("sortBy", p_sortByVar)
			}
			if c.Flags().Changed("stars") {
				params.Set("stars", p_starsVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/amazon/reviews", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_asinVar, "asin", "B0DHJ7SBDR", "asin ASIN: The Amazon Standard Identification Number (ASIN) of the product. (required)")
	_ = cmd.MarkFlagRequired("asin")
	cmd.Flags().StringVar(&p_domainVar, "domain", "", "domain Domain: Amazon domain to use. Default is www.amazon.com. [allowed: www.amazon.com|www.amazon.de|www.amazon.co.uk|www.amazon.ae|www.amazon.com.au|www.amazon.com.be|www.amazon.com.br|www.amazon.ca|www.amazon.eg|www.amazon.es|www.amazon.fr|www.amazon.ie|www.amazon.in|www.amazon.it|www.amazon.co.jp|www.amazon.com.mx|www.amazon.nl|www.amazon.pl|www.amazon.sa|www.amazon.se|www.amazon.sg|www.amazon.com.tr|www.amazon.co.za]")
	_ = cmd.RegisterFlagCompletionFunc("domain", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"www.amazon.com", "www.amazon.de", "www.amazon.co.uk", "www.amazon.ae", "www.amazon.com.au", "www.amazon.com.be", "www.amazon.com.br", "www.amazon.ca", "www.amazon.eg", "www.amazon.es", "www.amazon.fr", "www.amazon.ie", "www.amazon.in", "www.amazon.it", "www.amazon.co.jp", "www.amazon.com.mx", "www.amazon.nl", "www.amazon.pl", "www.amazon.sa", "www.amazon.se", "www.amazon.sg", "www.amazon.com.tr", "www.amazon.co.za"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_formatVar, "format", "", "format Format Type: The format type to filter reviews. Include reviews of any product format/variant or specifically to the current format/variant. [allowed: allFormats|currentFormat]")
	_ = cmd.RegisterFlagCompletionFunc("format", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"allFormats", "currentFormat"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_languageVar, "language", "", "language Language: Optional Amazon language code. Supported values depend on the selected domain.")
	cmd.Flags().StringVar(&p_mediaTypeVar, "media-type", "", "mediaType Media Type: The media type to filter reviews. [allowed: allReviews|mediaReviews]")
	_ = cmd.RegisterFlagCompletionFunc("media-type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"allReviews", "mediaReviews"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().IntVar(&p_pageVar, "page", 1, "page Page: The page number to retrieve.")
	cmd.Flags().StringVar(&p_reviewerTypeVar, "reviewer-type", "", "reviewerType Reviewer Type: The type of reviewers to filter. [allowed: allReviews|verifiedPurchaseReviews]")
	_ = cmd.RegisterFlagCompletionFunc("reviewer-type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"allReviews", "verifiedPurchaseReviews"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_searchTermVar, "search-term", "", "searchTerm Search Term: A term to search within the reviews.")
	cmd.Flags().StringVar(&p_sortByVar, "sort-by", "", "sortBy Sort By: The criterion to sort reviews. [allowed: helpful|recent]")
	_ = cmd.RegisterFlagCompletionFunc("sort-by", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"helpful", "recent"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_starsVar, "stars", "", "stars Review Stars: The star ratings to filter reviews. [allowed: allStars|fiveStar|fourStar|threeStar|twoStar|oneStar|positive|critical]")
	_ = cmd.RegisterFlagCompletionFunc("stars", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"allStars", "fiveStar", "fourStar", "threeStar", "twoStar", "oneStar", "positive", "critical"}, cobra.ShellCompDirectiveNoFileComp
	})

	return cmd
}

func init() {
	RegisterAPICommand("amazon", "Amazon", newAmazonReviewsCmd())
}
