// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newGoogleFlightsDealsCmd() *cobra.Command {
	var p_adultsVar int
	var p_arrivalIdVar string
	var p_childrenVar int
	var p_currencyVar string
	var p_departureIdVar string
	var p_excludeAirlinesVar string
	var p_glVar string
	var p_hlVar string
	var p_includeAirlinesVar string
	var p_infantsInSeatVar int
	var p_infantsOnLapVar int
	var p_maxDurationVar int
	var p_maxPriceVar int
	var p_outboundDateVar string
	var p_qVar string
	var p_returnDateVar string
	var p_stopsVar string
	var p_travelClassVar string
	var p_travelDurationVar string
	var p_tripLengthVar string
	var p_typeVar string

	cmd := &cobra.Command{
		Use:   "google-flights-deals",
		Short: "Google Flights Deals API  (15 credits/call)",
		Long:  "The Google Flights Deals API turns a plain-language trip description into concrete flight deals, letting Google's AI work out the destinations and travel dates on its own.\n\nEndpoint: GET https://api.hasdata.com/scrape/google/flights-deals\nCost: 15 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("stops") {
				if err := validateEnumString("stops", p_stopsVar, []string{"1", "nonStop", "2", "oneStopOrFewer", "3", "twoStopsOrFewer"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("travel-class") {
				if err := validateEnumString("travel-class", p_travelClassVar, []string{"1", "economy", "2", "premiumEconomy", "3", "business", "4", "first"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("travel-duration") {
				if err := validateEnumString("travel-duration", p_travelDurationVar, []string{"1", "week", "2", "weekend", "3", "twoWeeks"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("type") {
				if err := validateEnumString("type", p_typeVar, []string{"1", "roundTrip", "2", "oneWay"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("adults") {
				params.Set("adults", strconv.Itoa(p_adultsVar))
			}
			if c.Flags().Changed("arrival-id") {
				params.Set("arrivalId", p_arrivalIdVar)
			}
			if c.Flags().Changed("children") {
				params.Set("children", strconv.Itoa(p_childrenVar))
			}
			if c.Flags().Changed("currency") {
				params.Set("currency", p_currencyVar)
			}
			params.Set("departureId", p_departureIdVar)
			if c.Flags().Changed("exclude-airlines") {
				params.Set("excludeAirlines", p_excludeAirlinesVar)
			}
			if c.Flags().Changed("gl") {
				params.Set("gl", p_glVar)
			}
			if c.Flags().Changed("hl") {
				params.Set("hl", p_hlVar)
			}
			if c.Flags().Changed("include-airlines") {
				params.Set("includeAirlines", p_includeAirlinesVar)
			}
			if c.Flags().Changed("infants-in-seat") {
				params.Set("infantsInSeat", strconv.Itoa(p_infantsInSeatVar))
			}
			if c.Flags().Changed("infants-on-lap") {
				params.Set("infantsOnLap", strconv.Itoa(p_infantsOnLapVar))
			}
			if c.Flags().Changed("max-duration") {
				params.Set("maxDuration", strconv.Itoa(p_maxDurationVar))
			}
			if c.Flags().Changed("max-price") {
				params.Set("maxPrice", strconv.Itoa(p_maxPriceVar))
			}
			if c.Flags().Changed("outbound-date") {
				params.Set("outboundDate", p_outboundDateVar)
			}
			params.Set("q", p_qVar)
			if c.Flags().Changed("return-date") {
				params.Set("returnDate", p_returnDateVar)
			}
			if c.Flags().Changed("stops") {
				params.Set("stops", p_stopsVar)
			}
			if c.Flags().Changed("travel-class") {
				params.Set("travelClass", p_travelClassVar)
			}
			if c.Flags().Changed("travel-duration") {
				params.Set("travelDuration", p_travelDurationVar)
			}
			if c.Flags().Changed("trip-length") {
				params.Set("tripLength", p_tripLengthVar)
			}
			if c.Flags().Changed("type") {
				params.Set("type", p_typeVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/google/flights-deals", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().IntVar(&p_adultsVar, "adults", 0, "adults Adults: Number of adults. Prices cover the whole party, so raising this raises every deal price.\n\nPassenger counts reprice rather than narrow the search, so they need no `arrivalId`. The whole party must not exceed 9.\n")
	cmd.Flags().StringVar(&p_arrivalIdVar, "arrival-id", "", "arrivalId Arrival airport code / location kgmid: Pins the search to one destination instead of letting Google pick from the query.\n\n  - **IATA code**: 3 uppercase letters, e.g. `NRT` for Tokyo Narita.\n  - **Location kgmid**: starts with `/m/`, found in Wikidata under \"Freebase ID\", e.g. `/m/07dfk` for Tokyo.\n\nRequired by every filter: `type`, `travelClass`, `stops`, `outboundDate`, `returnDate`, `travelDuration`, `tripLength`, `maxPrice`, `maxDuration`, `includeAirlines` and `excludeAirlines`. Without it Google drops them silently.\n")
	cmd.Flags().IntVar(&p_childrenVar, "children", 0, "children Children: Number of children, priced at their own fare. Counts towards the limit of 9 passengers.\n")
	cmd.Flags().StringVar(&p_currencyVar, "currency", "", "currency Currency: Parameter defines the currency of the returned prices")
	cmd.Flags().StringVar(&p_departureIdVar, "departure-id", "LAX", "departureId Departure airport code: Departure airport as a 3-letter uppercase IATA code, e.g. `LAX` or `LHR`. Search on [IATA](https://www.iata.org/en/publications/directories/code-search).\n\nOne airport per search; city names are not accepted.\n (required)")
	_ = cmd.MarkFlagRequired("departure-id")
	cmd.Flags().StringVar(&p_excludeAirlinesVar, "exclude-airlines", "", "excludeAirlines Exclude airlines: Drops these airlines from the deals. Requires `arrivalId`. Cannot be combined with `includeAirlines`.\n\nTakes the same values as `includeAirlines`.\n")
	cmd.Flags().StringVar(&p_glVar, "gl", "", "gl Country: The two-letter country code for the country you want to limit the search to.")
	cmd.Flags().StringVar(&p_hlVar, "hl", "", "hl Language: The two-letter language code for the language you want to use for the search.")
	cmd.Flags().StringVar(&p_includeAirlinesVar, "include-airlines", "", "includeAirlines Include airlines: Keeps only these airlines. Requires `arrivalId`. Cannot be combined with `excludeAirlines`.\n\nComma-separated 2-character IATA codes (`AF`, `UA`, `B6`) and Google's alliances `STAR_ALLIANCE`, `SKYTEAM`, `ONEWORLD`. The two can be mixed.\n\nAn airline that does not serve the route returns an empty `flightDeals` array, not an error.\n")
	cmd.Flags().IntVar(&p_infantsInSeatVar, "infants-in-seat", 0, "infantsInSeat Infants in seat: Number of infants in their own seat. Counts towards the limit of 9 passengers.\n")
	cmd.Flags().IntVar(&p_infantsOnLapVar, "infants-on-lap", 0, "infantsOnLap Infants on lap: Number of infants on an adult's lap. Counts towards the limit of 9 passengers.\n\nGoogle prices a lap infant above one in its own seat — the opposite of how airlines usually charge.\n")
	cmd.Flags().IntVar(&p_maxDurationVar, "max-duration", 0, "maxDuration Maximum flight duration: Maximum flight duration in minutes — `1500` for 25 hours. Requires `arrivalId`. Omitted, it is unbounded. Applies to each leg, not to the round trip.\n\nGoogle measures against a longer figure than the `durationMinutes` it returns, so set the ceiling above the flight you want: on a route whose shortest deal is 635 minutes, `635` comes back empty and `680` returns it. On an empty result, raise `maxDuration` by up to 200 before concluding the route has nothing.\n")
	cmd.Flags().IntVar(&p_maxPriceVar, "max-price", 0, "maxPrice Maximum price: Maximum ticket price, inclusive. Requires `arrivalId`. Omitted, it is unbounded.\n\nRead in the currency of the request: `650` means 650 EUR when `currency` is `EUR`, and 650 USD by default.\n")
	cmd.Flags().StringVar(&p_outboundDateVar, "outbound-date", "", "outboundDate Departure date or window: When to depart. Requires `arrivalId`.\n\n  - **Exact date**: `2026-12-10`\n  - **Window**: `2026-12-01,2026-12-10` — any day within it\n\nOmitted, Google picks the dates from the query, or from whatever is cheapest.\n")
	cmd.Flags().StringVar(&p_qVar, "q", "I would like to see cherry blossom in Japan", "q Trip description: Free-text trip description, from a bare place name to a full sentence:\n\n  - **Destination**: `Tokyo`\n  - **Type of trip**: `beach escape`, `weekend getaway in Europe`\n  - **Season or event**: `I would like to see cherry blossom in Japan`\n\nWhen the query implies a time of year, Google dates it itself and reports the range in `searchInformation.dateRange`.\n (required)")
	_ = cmd.MarkFlagRequired("q")
	cmd.Flags().StringVar(&p_returnDateVar, "return-date", "", "returnDate Return date or window: When to return, in the same exact-or-window spelling as `outboundDate`, which is required alongside it.\n\nCannot be combined with `travelDuration` or `tripLength` — all three set the trip length. Ignored when `type` is `oneWay`.\n")
	cmd.Flags().StringVar(&p_stopsVar, "stops", "", "stops Stops: Maximum number of stops. Requires `arrivalId`. Omitted, any number is allowed.\n\n  - `1` / `nonStop` — direct flights only\n  - `2` / `oneStopOrFewer` — at most one connection\n  - `3` / `twoStopsOrFewer` — at most two connections\n\nA route with nothing at that depth returns an empty `flightDeals` array, not an error — `nonStop` on a route without a direct flight is a valid, empty answer.\n [allowed: 1|nonStop|2|oneStopOrFewer|3|twoStopsOrFewer]")
	_ = cmd.RegisterFlagCompletionFunc("stops", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"1", "nonStop", "2", "oneStopOrFewer", "3", "twoStopsOrFewer"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_travelClassVar, "travel-class", "", "travelClass Travel class: Travel class. Requires `arrivalId`.\n\n  - `1` / `economy` — economy (default)\n  - `2` / `premiumEconomy` — premium economy\n  - `3` / `business` — business\n  - `4` / `first` — first\n\nFares climb steeply: on LAX-NRT the same search ran $730 in economy against $2882 in business.\n [allowed: 1|economy|2|premiumEconomy|3|business|4|first]")
	_ = cmd.RegisterFlagCompletionFunc("travel-class", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"1", "economy", "2", "premiumEconomy", "3", "business", "4", "first"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_travelDurationVar, "travel-duration", "", "travelDuration Trip duration preset: Preset trip length. Requires `arrivalId`. Cannot be combined with `returnDate` or `tripLength`.\n\n  - `1` / `week` — about a week (6-8 days)\n  - `2` / `weekend` — a weekend (2-3 days)\n  - `3` / `twoWeeks` — about two weeks (13-15 days)\n\nPairs with `outboundDate` to limit the departure period. Ignored when `type` is `oneWay`.\n [allowed: 1|week|2|weekend|3|twoWeeks]")
	_ = cmd.RegisterFlagCompletionFunc("travel-duration", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"1", "week", "2", "weekend", "3", "twoWeeks"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_tripLengthVar, "trip-length", "", "tripLength Trip length in days: Trip length in days. Requires `arrivalId`. Cannot be combined with `returnDate` or `travelDuration`.\n\n  - **Exact**: `7`\n  - **Range**: `5,10` — min first\n\nPairs with `outboundDate` to limit the departure period. Ignored when `type` is `oneWay`.\n")
	cmd.Flags().StringVar(&p_typeVar, "type", "", "type Flight type: Flight type. Requires `arrivalId`.\n\n  - `1` / `roundTrip` — round trip (default)\n  - `2` / `oneWay` — one way\n\nA one-way deal carries no `returnDate` and no `tripLengthDays`.\n [allowed: 1|roundTrip|2|oneWay]")
	_ = cmd.RegisterFlagCompletionFunc("type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"1", "roundTrip", "2", "oneWay"}, cobra.ShellCompDirectiveNoFileComp
	})

	return cmd
}

func init() {
	RegisterAPICommand("google_travel", "Google Travel", newGoogleFlightsDealsCmd())
}
