// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newIndeedListingCmd() *cobra.Command {
	var p_domainVar string
	var p_keywordVar string
	var p_locationVar string
	var p_sortVar string
	var p_startVar float64

	cmd := &cobra.Command{
		Use:   "indeed-listing",
		Short: "Indeed Listing API  (5 credits/call)",
		Long:  "The Indeed Listing API allows you to retrieve job listings from Indeed based on various search parameters.\n\nEndpoint: GET https://api.hasdata.com/scrape/indeed/listing\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("domain") {
				if err := validateEnumString("domain", p_domainVar, []string{"ar.indeed.com", "au.indeed.com", "at.indeed.com", "bh.indeed.com", "be.indeed.com", "br.indeed.com", "ca.indeed.com", "cl.indeed.com", "cn.indeed.com", "co.indeed.com", "cr.indeed.com", "cz.indeed.com", "dk.indeed.com", "ec.indeed.com", "eg.indeed.com", "fi.indeed.com", "fr.indeed.com", "de.indeed.com", "gr.indeed.com", "hk.indeed.com", "hu.indeed.com", "in.indeed.com", "id.indeed.com", "ie.indeed.com", "il.indeed.com", "it.indeed.com", "jp.indeed.com", "kw.indeed.com", "lu.indeed.com", "malaysia.indeed.com", "mx.indeed.com", "ma.indeed.com", "nl.indeed.com", "nz.indeed.com", "ng.indeed.com", "no.indeed.com", "om.indeed.com", "pk.indeed.com", "pa.indeed.com", "pe.indeed.com", "ph.indeed.com", "pl.indeed.com", "pt.indeed.com", "qa.indeed.com", "ro.indeed.com", "sa.indeed.com", "sg.indeed.com", "za.indeed.com", "kr.indeed.com", "es.indeed.com", "se.indeed.com", "ch.indeed.com", "tw.indeed.com", "th.indeed.com", "tr.indeed.com", "ua.indeed.com", "ae.indeed.com", "uk.indeed.com", "www.indeed.com", "uy.indeed.com", "ve.indeed.com", "vn.indeed.com"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("sort") {
				if err := validateEnumString("sort", p_sortVar, []string{"relevance", "date"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("domain") {
				params.Set("domain", p_domainVar)
			}
			params.Set("keyword", p_keywordVar)
			params.Set("location", p_locationVar)
			if c.Flags().Changed("sort") {
				params.Set("sort", p_sortVar)
			}
			if c.Flags().Changed("start") {
				params.Set("start", strconv.FormatFloat(p_startVar, 'f', -1, 64))
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/indeed/listing", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_domainVar, "domain", "www.indeed.com", "domain: The domain of the Indeed site (optional). [allowed: ar.indeed.com|au.indeed.com|at.indeed.com|bh.indeed.com|be.indeed.com|br.indeed.com|ca.indeed.com|cl.indeed.com|cn.indeed.com|co.indeed.com|cr.indeed.com|cz.indeed.com|dk.indeed.com|ec.indeed.com|eg.indeed.com|fi.indeed.com|fr.indeed.com|de.indeed.com|gr.indeed.com|hk.indeed.com|hu.indeed.com|in.indeed.com|id.indeed.com|ie.indeed.com|il.indeed.com|it.indeed.com|jp.indeed.com|kw.indeed.com|lu.indeed.com|malaysia.indeed.com|mx.indeed.com|ma.indeed.com|nl.indeed.com|nz.indeed.com|ng.indeed.com|no.indeed.com|om.indeed.com|pk.indeed.com|pa.indeed.com|pe.indeed.com|ph.indeed.com|pl.indeed.com|pt.indeed.com|qa.indeed.com|ro.indeed.com|sa.indeed.com|sg.indeed.com|za.indeed.com|kr.indeed.com|es.indeed.com|se.indeed.com|ch.indeed.com|tw.indeed.com|th.indeed.com|tr.indeed.com|ua.indeed.com|ae.indeed.com|uk.indeed.com|www.indeed.com|uy.indeed.com|ve.indeed.com|vn.indeed.com]")
	_ = cmd.RegisterFlagCompletionFunc("domain", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"ar.indeed.com", "au.indeed.com", "at.indeed.com", "bh.indeed.com", "be.indeed.com", "br.indeed.com", "ca.indeed.com", "cl.indeed.com", "cn.indeed.com", "co.indeed.com", "cr.indeed.com", "cz.indeed.com", "dk.indeed.com", "ec.indeed.com", "eg.indeed.com", "fi.indeed.com", "fr.indeed.com", "de.indeed.com", "gr.indeed.com", "hk.indeed.com", "hu.indeed.com", "in.indeed.com", "id.indeed.com", "ie.indeed.com", "il.indeed.com", "it.indeed.com", "jp.indeed.com", "kw.indeed.com", "lu.indeed.com", "malaysia.indeed.com", "mx.indeed.com", "ma.indeed.com", "nl.indeed.com", "nz.indeed.com", "ng.indeed.com", "no.indeed.com", "om.indeed.com", "pk.indeed.com", "pa.indeed.com", "pe.indeed.com", "ph.indeed.com", "pl.indeed.com", "pt.indeed.com", "qa.indeed.com", "ro.indeed.com", "sa.indeed.com", "sg.indeed.com", "za.indeed.com", "kr.indeed.com", "es.indeed.com", "se.indeed.com", "ch.indeed.com", "tw.indeed.com", "th.indeed.com", "tr.indeed.com", "ua.indeed.com", "ae.indeed.com", "uk.indeed.com", "www.indeed.com", "uy.indeed.com", "ve.indeed.com", "vn.indeed.com"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_keywordVar, "keyword", "software engineer", "keyword Search Query: The keyword used to search for job listings. (required)")
	_ = cmd.MarkFlagRequired("keyword")
	cmd.Flags().StringVar(&p_locationVar, "location", "New York, NY", "location Location: The location to search for job listings. (required)")
	_ = cmd.MarkFlagRequired("location")
	cmd.Flags().StringVar(&p_sortVar, "sort", "date", "sort Sort By: The sorting option for the search results. [allowed: relevance|date]")
	_ = cmd.RegisterFlagCompletionFunc("sort", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"relevance", "date"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().Float64Var(&p_startVar, "start", 0, "start Result Offset: The starting index of the results to retrieve (optional).")

	return cmd
}

func init() {
	RegisterAPICommand("job", "Jobs", newIndeedListingCmd())
}
