// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newWalmartReviewsCmd() *cobra.Command {
	var p_aspectIdVar string
	var p_conditionVar string
	var p_domainVar string
	var p_itemIdVar string
	var p_languageVar string
	var p_pageVar int
	var p_ratingVar int
	var p_sortVar string
	var p_urlVar string
	var p_verifiedPurchasesOnlyVar bool

	cmd := &cobra.Command{
		Use:   "walmart-reviews",
		Short: "Walmart Reviews Scraper API  (10 credits/call)",
		Long:  "The Walmart Reviews Scraper API returns the customer reviews of a single Walmart item, ten a page, with the sorting and filtering the product page itself offers.\n\nEndpoint: GET https://api.hasdata.com/scrape/walmart/reviews\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("domain") {
				if err := validateEnumString("domain", p_domainVar, []string{"walmart.com", "walmart.ca"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("language") {
				if err := validateEnumString("language", p_languageVar, []string{"en", "es", "fr"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("sort") {
				if err := validateEnumString("sort", p_sortVar, []string{"mostRelevant", "mostRecent", "mostHelpful", "highestRated", "lowestRated", "oldest"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("aspect-id") {
				params.Set("aspectId", p_aspectIdVar)
			}
			if c.Flags().Changed("condition") {
				params.Set("condition", p_conditionVar)
			}
			if c.Flags().Changed("domain") {
				params.Set("domain", p_domainVar)
			}
			if c.Flags().Changed("item-id") {
				params.Set("itemId", p_itemIdVar)
			}
			if c.Flags().Changed("language") {
				params.Set("language", p_languageVar)
			}
			if c.Flags().Changed("page") {
				params.Set("page", strconv.Itoa(p_pageVar))
			}
			if c.Flags().Changed("rating") {
				params.Set("rating", strconv.Itoa(p_ratingVar))
			}
			if c.Flags().Changed("sort") {
				params.Set("sort", p_sortVar)
			}
			if c.Flags().Changed("url") {
				params.Set("url", p_urlVar)
			}
			if c.Flags().Changed("verified-purchases-only") {
				params.Set("verifiedPurchasesOnly", strconv.FormatBool(p_verifiedPurchasesOnlyVar))
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/walmart/reviews", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_aspectIdVar, "aspect-id", "", "aspectId Frequent Mention: Return only reviews mentioning one topic, given as its id. The topics differ per product - a phone has Battery Life or Display, a coffee has Flavor or Aroma - so take the id from the Frequent mentions group of the filters block in the response rather than guessing it.")
	cmd.Flags().StringVar(&p_conditionVar, "condition", "", "condition Condition: Return only reviews written about one item condition, given as its code. Applies to items sold in several conditions, such as new and restored. Take the code from the Condition group of the filters block in the response.")
	cmd.Flags().StringVar(&p_domainVar, "domain", "", "domain Domain: Walmart storefront the item belongs to. Each storefront has its own catalog, item ids and review pool, so an id from one storefront does not resolve on another. Ignored when url is provided. Default is walmart.com. [allowed: walmart.com|walmart.ca]")
	_ = cmd.RegisterFlagCompletionFunc("domain", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"walmart.com", "walmart.ca"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_itemIdVar, "item-id", "1028936148", "itemId Item ID: Walmart item id, taken from a product URL or from the id field of the Walmart Search API response. On walmart.com it is numeric (for example 14977205582), on walmart.ca an alphanumeric code (for example 6NZMJ5CW6MH2). Required unless url is provided.")
	cmd.Flags().StringVar(&p_languageVar, "language", "en", "language Language: Language of the review page. Availability depends on the storefront - walmart.com serves en and es, walmart.ca serves en and fr. A language the storefront does not support falls back to its default. Reviews themselves are returned in the language their author wrote them in. [allowed: en|es|fr]")
	_ = cmd.RegisterFlagCompletionFunc("language", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"en", "es", "fr"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().IntVar(&p_pageVar, "page", 1, "page Page: Page of reviews to return, ten reviews a page. The response reports the last available page in pagination.totalPages, and the next one in pagination.nextPage. Note that only reviews carrying written text are paginated, so the ceiling follows reviewsInformation.totalReviews rather than the larger totalRatings. Default is 1.")
	cmd.Flags().IntVar(&p_ratingVar, "rating", 0, "rating Star Rating: Return only reviews carrying this star rating. The filters block of the response lists the ratings this item actually has, with a review count for each.")
	cmd.Flags().StringVar(&p_sortVar, "sort", "mostRelevant", "sort Sort By: Order of the returned reviews, named as the Walmart review page names it. Default is mostRelevant. [allowed: mostRelevant|mostRecent|mostHelpful|highestRated|lowestRated|oldest]")
	_ = cmd.RegisterFlagCompletionFunc("sort", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"mostRelevant", "mostRecent", "mostHelpful", "highestRated", "lowestRated", "oldest"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_urlVar, "url", "https://www.walmart.com/ip/Restored-Apple-iPhone-14-Carrier-Unlocked-128-GB-Starlight-MPUN3LL-A-Refurbished/1028936148", "url Product URL: A full Walmart product URL whose reviews to scrape. When provided, it overrides itemId and the storefront is taken from the URL itself. Required unless itemId is provided.")
	cmd.Flags().BoolVar(&p_verifiedPurchasesOnlyVar, "verified-purchases-only", false, "verifiedPurchasesOnly Verified Purchases Only: Return only reviews left by customers whose purchase Walmart confirmed. Narrows the pool considerably, since most reviews are unverified or syndicated from the manufacturer.")

	return cmd
}

func init() {
	RegisterAPICommand("ecommerce", "E-commerce", newWalmartReviewsCmd())
}
