// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newAmazonSellerProductsCmd() *cobra.Command {
	var p_domainVar string
	var p_languageVar string
	var p_pageVar int
	var p_sellerIdVar string

	cmd := &cobra.Command{
		Use:   "amazon-seller-products",
		Short: "Amazon Seller Products API  (5 credits/call)",
		Long:  "The Amazon Seller Products API allows users to retrieve products listed by a specific Amazon seller using the seller ID, with optional domain, language, and page settings.\n\nEndpoint: GET https://api.hasdata.com/scrape/amazon/seller-products\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("domain") {
				if err := validateEnumString("domain", p_domainVar, []string{"www.amazon.com", "www.amazon.de", "www.amazon.co.uk", "www.amazon.ae", "www.amazon.com.au", "www.amazon.com.be", "www.amazon.com.br", "www.amazon.ca", "www.amazon.eg", "www.amazon.es", "www.amazon.fr", "www.amazon.ie", "www.amazon.in", "www.amazon.it", "www.amazon.co.jp", "www.amazon.com.mx", "www.amazon.nl", "www.amazon.pl", "www.amazon.sa", "www.amazon.se", "www.amazon.sg", "www.amazon.com.tr", "www.amazon.co.za"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("domain") {
				params.Set("domain", p_domainVar)
			}
			if c.Flags().Changed("language") {
				params.Set("language", p_languageVar)
			}
			if c.Flags().Changed("page") {
				params.Set("page", strconv.Itoa(p_pageVar))
			}
			params.Set("sellerId", p_sellerIdVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/amazon/seller-products", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_domainVar, "domain", "", "domain Domain: Amazon domain to use. Default is www.amazon.com. [allowed: www.amazon.com|www.amazon.de|www.amazon.co.uk|www.amazon.ae|www.amazon.com.au|www.amazon.com.be|www.amazon.com.br|www.amazon.ca|www.amazon.eg|www.amazon.es|www.amazon.fr|www.amazon.ie|www.amazon.in|www.amazon.it|www.amazon.co.jp|www.amazon.com.mx|www.amazon.nl|www.amazon.pl|www.amazon.sa|www.amazon.se|www.amazon.sg|www.amazon.com.tr|www.amazon.co.za]")
	_ = cmd.RegisterFlagCompletionFunc("domain", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"www.amazon.com", "www.amazon.de", "www.amazon.co.uk", "www.amazon.ae", "www.amazon.com.au", "www.amazon.com.be", "www.amazon.com.br", "www.amazon.ca", "www.amazon.eg", "www.amazon.es", "www.amazon.fr", "www.amazon.ie", "www.amazon.in", "www.amazon.it", "www.amazon.co.jp", "www.amazon.com.mx", "www.amazon.nl", "www.amazon.pl", "www.amazon.sa", "www.amazon.se", "www.amazon.sg", "www.amazon.com.tr", "www.amazon.co.za"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_languageVar, "language", "", "language Language: Optional Amazon language code. Supported values depend on the selected domain.")
	cmd.Flags().IntVar(&p_pageVar, "page", 0, "page Page Number: Page number for pagination (e.g., 1 for the first page, 2 for the second page, etc.).")
	cmd.Flags().StringVar(&p_sellerIdVar, "seller-id", "ATQQBVXK188KS", "sellerId Seller ID: The unique Amazon seller ID. (required)")
	_ = cmd.MarkFlagRequired("seller-id")

	return cmd
}

func init() {
	RegisterAPICommand("amazon", "Amazon", newAmazonSellerProductsCmd())
}
