// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newYoutubeSearchApiCmd() *cobra.Command {
	var p_dateVar string
	var p_deviceTypeVar string
	var p_filtersVar []string
	var p_glVar string
	var p_hlVar string
	var p_lengthVar string
	var p_paginationTokenVar string
	var p_qVar string
	var p_sortByVar string
	var p_spVar string
	var p_videoTypeVar string

	cmd := &cobra.Command{
		Use:   "youtube-search-api",
		Short: "YouTube Search API  (10 credits/call)",
		Long:  "The YouTube Search API provides real-time access to structured YouTube search results.\n\nEndpoint: GET https://api.hasdata.com/scrape/youtube/search\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("date") {
				if err := validateEnumString("date", p_dateVar, []string{"hour", "today", "week", "month", "year"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("device-type") {
				if err := validateEnumString("device-type", p_deviceTypeVar, []string{"desktop", "mobile"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("filters") {
				if err := validateEnumStringSlice("filters", p_filtersVar, []string{"hd", "subtitles", "cc", "d3", "live", "bought", "k4", "d360", "location", "hdr", "vr180"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("length") {
				if err := validateEnumString("length", p_lengthVar, []string{"under4", "between420", "plus20"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("sort-by") {
				if err := validateEnumString("sort-by", p_sortByVar, []string{"relevance", "popularity", "rating", "date", "views"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("video-type") {
				if err := validateEnumString("video-type", p_videoTypeVar, []string{"video", "shorts", "channel", "playlist", "movie"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("date") {
				params.Set("date", p_dateVar)
			}
			if c.Flags().Changed("device-type") {
				params.Set("deviceType", p_deviceTypeVar)
			}
			if c.Flags().Changed("filters") {
				for _, v := range p_filtersVar {
					params.Add("filters"+"[]", v)
				}
			}
			if c.Flags().Changed("gl") {
				params.Set("gl", p_glVar)
			}
			if c.Flags().Changed("hl") {
				params.Set("hl", p_hlVar)
			}
			if c.Flags().Changed("length") {
				params.Set("length", p_lengthVar)
			}
			if c.Flags().Changed("pagination-token") {
				params.Set("paginationToken", p_paginationTokenVar)
			}
			params.Set("q", p_qVar)
			if c.Flags().Changed("sort-by") {
				params.Set("sortBy", p_sortByVar)
			}
			if c.Flags().Changed("sp") {
				params.Set("sp", p_spVar)
			}
			if c.Flags().Changed("video-type") {
				params.Set("videoType", p_videoTypeVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/youtube/search", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_dateVar, "date", "", "date Upload Date: Limit results to videos uploaded within this time window relative to now. [allowed: hour|today|week|month|year]")
	_ = cmd.RegisterFlagCompletionFunc("date", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"hour", "today", "week", "month", "year"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_deviceTypeVar, "device-type", "", "deviceType Device: Device type for the request. [allowed: desktop|mobile]")
	_ = cmd.RegisterFlagCompletionFunc("device-type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"desktop", "mobile"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringSliceVar(&p_filtersVar, "filters", nil, "filters[] Features: Feature flags to require on results. Multiple values are combined with AND (every flag must apply).\n\n- `hd` — HD quality\n- `k4` — 4K quality\n- `hdr` — HDR\n- `subtitles` — has subtitles/closed captions\n- `cc` — Creative Commons license\n- `d3` — 3D video\n- `d360` — 360° video\n- `vr180` — VR180 video\n- `live` — currently live\n- `bought` — purchased/paid content\n- `location` — has a geographic location tag\n")
	_ = cmd.RegisterFlagCompletionFunc("filters", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"hd", "subtitles", "cc", "d3", "live", "bought", "k4", "d360", "location", "hdr", "vr180"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_glVar, "gl", "", "gl Country: The two-letter country code for the country you want to limit the search to.")
	cmd.Flags().StringVar(&p_hlVar, "hl", "", "hl Language: The two-letter language code for the language you want to use for the search.")
	cmd.Flags().StringVar(&p_lengthVar, "length", "", "length Duration: Filter by video duration bucket:\n- `under4` — under 4 minutes\n- `between420` — 4 to 20 minutes\n- `plus20` — over 20 minutes\n [allowed: under4|between420|plus20]")
	_ = cmd.RegisterFlagCompletionFunc("length", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"under4", "between420", "plus20"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_paginationTokenVar, "pagination-token", "", "paginationToken Pagination Token: Token returned in the previous response to fetch the next page.")
	cmd.Flags().StringVar(&p_qVar, "q", "BMW", "q Search Query: Free-text search query, exactly as a user would type it into the YouTube search box. (required)")
	_ = cmd.MarkFlagRequired("q")
	cmd.Flags().StringVar(&p_sortByVar, "sort-by", "", "sortBy Sort By: Sort order applied to the results page. `relevance` (default) — best match for the query; `date` — newest first; `views` — most viewed first; `rating` — highest rated first; `popularity` — trending/most popular. [allowed: relevance|popularity|rating|date|views]")
	_ = cmd.RegisterFlagCompletionFunc("sort-by", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"relevance", "popularity", "rating", "date", "views"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_spVar, "sp", "", "sp Search Parameters: Raw YouTube `sp` filter token, copied verbatim from a YouTube search URL (e.g. `EgIQAQ%253D%253D`). When provided, it overrides `sortBy`, `date`, `videoType`, `length`, and `filters[]`. Use only if you need a YouTube-side filter that this API does not expose as a structured parameter.")
	cmd.Flags().StringVar(&p_videoTypeVar, "video-type", "", "videoType Type: Restrict results to a single YouTube content type — regular videos, Shorts, channels, playlists, or movies. [allowed: video|shorts|channel|playlist|movie]")
	_ = cmd.RegisterFlagCompletionFunc("video-type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"video", "shorts", "channel", "playlist", "movie"}, cobra.ShellCompDirectiveNoFileComp
	})

	return cmd
}

func init() {
	RegisterAPICommand("youtube", "YouTube", newYoutubeSearchApiCmd())
}
