// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newBookingSearchCmd() *cobra.Command {
	var p_adultsVar int
	var p_bathroomsVar int
	var p_bedPreferenceVar []string
	var p_bedroomsVar int
	var p_checkInDateVar string
	var p_checkOutDateVar string
	var p_childrenVar int
	var p_childrenAgesJsonVar string
	var p_currencyVar string
	var p_distanceFromCenterVar []string
	var p_facilitiesVar []string
	var p_keywordVar string
	var p_languageVar string
	var p_mealsVar []string
	var p_onlinePaymentVar []string
	var p_pageVar int
	var p_price_maxVar float64
	var p_price_minVar float64
	var p_propertyAccessibilityVar []string
	var p_propertyTypeVar []string
	var p_ratingVar []string
	var p_reservationPolicyVar []string
	var p_reviewScoreVar []string
	var p_roomAccessibilityVar []string
	var p_roomFacilitiesVar []string
	var p_roomsVar int
	var p_sortVar string
	var p_travelGroupVar []string

	cmd := &cobra.Command{
		Use:   "booking-search",
		Short: "Booking Search API  (10 credits/call)",
		Long:  "The Booking Search API returns the collection of accommodations from a Booking.com search results page for a given destination and stay dates, with rich filtering by property type, rating, facilities, price and more.\n\nEndpoint: GET https://api.hasdata.com/scrape/booking/search\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("bed-preference") {
				if err := validateEnumStringSlice("bed-preference", p_bedPreferenceVar, []string{"twinBeds", "doubleBed"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("distance-from-center") {
				if err := validateEnumStringSlice("distance-from-center", p_distanceFromCenterVar, []string{"lessThan1Km", "lessThan3Km", "lessThan5Km"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("facilities") {
				if err := validateEnumStringSlice("facilities", p_facilitiesVar, []string{"swimmingPool", "parking", "spa", "freeWifi", "hotTubJacuzzi", "airportShuttle", "fitnessCenter", "restaurant", "nonSmokingRooms", "frontDesk24Hour", "electricVehicleChargingStation", "wheelchairAccessible", "roomService"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("meals") {
				if err := validateEnumStringSlice("meals", p_mealsVar, []string{"breakfastIncluded", "kitchenFacilities"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("online-payment") {
				if err := validateEnumStringSlice("online-payment", p_onlinePaymentVar, []string{"acceptsOnlinePayments"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("property-accessibility") {
				if err := validateEnumStringSlice("property-accessibility", p_propertyAccessibilityVar, []string{"auditoryGuidance", "toiletWithGrabRails", "visualAidsTactileSigns", "visualAidsBraille", "bathroomEmergencyCord", "raisedToilet", "loweredSink"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("property-type") {
				if err := validateEnumStringSlice("property-type", p_propertyTypeVar, []string{"hostels", "bedAndBreakfast", "hotels", "apartments", "resorts", "guesthouses", "homestays", "entireHomesAndApartments"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("rating") {
				if err := validateEnumStringSlice("rating", p_ratingVar, []string{"oneStar", "twoStars", "threeStars", "fourStars", "fiveStars"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("reservation-policy") {
				if err := validateEnumStringSlice("reservation-policy", p_reservationPolicyVar, []string{"freeCancellation", "noPrepayment"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("review-score") {
				if err := validateEnumStringSlice("review-score", p_reviewScoreVar, []string{"wonderful", "veryGood", "good", "pleasant"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("room-accessibility") {
				if err := validateEnumStringSlice("room-accessibility", p_roomAccessibilityVar, []string{"upperFloorsAccessibleByElevator", "entireUnitLocatedOnGroundFloor", "walkInShower", "entireUnitWheelchairAccessible", "adaptedBath", "rollInShower", "showerChair", "emergencyCordInBathroom", "toiletWithGrabRails", "raisedToilet", "lowerSink"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("room-facilities") {
				if err := validateEnumStringSlice("room-facilities", p_roomFacilitiesVar, []string{"privateBathroom", "balcony", "seaView", "kitchenKitchenette", "airConditioning", "bathtub", "hotTub", "view", "spaTub", "upperFloorsAccessibleByElevator", "microwave", "refrigerator", "coffeeMachine", "electricKettle", "heating", "towels", "toilet", "mountainView", "flatScreenTv", "tv", "coffeeTeaMaker", "hairdryer", "toiletPaper", "shower", "linens"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("sort") {
				if err := validateEnumString("sort", p_sortVar, []string{"ourTopPicks", "homesAndApartmentsFirst", "priceLowestFirst", "priceHighestFirst", "bestReviewedAndLowestPrice", "ratingHighToLow", "ratingLowToHigh", "ratingAndPrice", "distanceFromDowntown", "topReviewed"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("travel-group") {
				if err := validateEnumStringSlice("travel-group", p_travelGroupVar, []string{"adultsOnly", "petFriendly"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("adults", strconv.Itoa(p_adultsVar))
			if c.Flags().Changed("bathrooms") {
				params.Set("bathrooms", strconv.Itoa(p_bathroomsVar))
			}
			if c.Flags().Changed("bed-preference") {
				for _, v := range p_bedPreferenceVar {
					params.Add("bedPreference"+"[]", v)
				}
			}
			if c.Flags().Changed("bedrooms") {
				params.Set("bedrooms", strconv.Itoa(p_bedroomsVar))
			}
			params.Set("checkInDate", p_checkInDateVar)
			params.Set("checkOutDate", p_checkOutDateVar)
			params.Set("children", strconv.Itoa(p_childrenVar))
			if c.Flags().Changed("children-ages-json") {
				params.Set("childrenAgesJson", p_childrenAgesJsonVar)
			}
			if c.Flags().Changed("currency") {
				params.Set("currency", p_currencyVar)
			}
			if c.Flags().Changed("distance-from-center") {
				for _, v := range p_distanceFromCenterVar {
					params.Add("distanceFromCenter"+"[]", v)
				}
			}
			if c.Flags().Changed("facilities") {
				for _, v := range p_facilitiesVar {
					params.Add("facilities"+"[]", v)
				}
			}
			params.Set("keyword", p_keywordVar)
			if c.Flags().Changed("language") {
				params.Set("language", p_languageVar)
			}
			if c.Flags().Changed("meals") {
				for _, v := range p_mealsVar {
					params.Add("meals"+"[]", v)
				}
			}
			if c.Flags().Changed("online-payment") {
				for _, v := range p_onlinePaymentVar {
					params.Add("onlinePayment"+"[]", v)
				}
			}
			if c.Flags().Changed("page") {
				params.Set("page", strconv.Itoa(p_pageVar))
			}
			if c.Flags().Changed("price-max") {
				params.Set("price[max]", strconv.FormatFloat(p_price_maxVar, 'f', -1, 64))
			}
			if c.Flags().Changed("price-min") {
				params.Set("price[min]", strconv.FormatFloat(p_price_minVar, 'f', -1, 64))
			}
			if c.Flags().Changed("property-accessibility") {
				for _, v := range p_propertyAccessibilityVar {
					params.Add("propertyAccessibility"+"[]", v)
				}
			}
			if c.Flags().Changed("property-type") {
				for _, v := range p_propertyTypeVar {
					params.Add("propertyType"+"[]", v)
				}
			}
			if c.Flags().Changed("rating") {
				for _, v := range p_ratingVar {
					params.Add("rating"+"[]", v)
				}
			}
			if c.Flags().Changed("reservation-policy") {
				for _, v := range p_reservationPolicyVar {
					params.Add("reservationPolicy"+"[]", v)
				}
			}
			if c.Flags().Changed("review-score") {
				for _, v := range p_reviewScoreVar {
					params.Add("reviewScore"+"[]", v)
				}
			}
			if c.Flags().Changed("room-accessibility") {
				for _, v := range p_roomAccessibilityVar {
					params.Add("roomAccessibility"+"[]", v)
				}
			}
			if c.Flags().Changed("room-facilities") {
				for _, v := range p_roomFacilitiesVar {
					params.Add("roomFacilities"+"[]", v)
				}
			}
			params.Set("rooms", strconv.Itoa(p_roomsVar))
			if c.Flags().Changed("sort") {
				params.Set("sort", p_sortVar)
			}
			if c.Flags().Changed("travel-group") {
				for _, v := range p_travelGroupVar {
					params.Add("travelGroup"+"[]", v)
				}
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/booking/search", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().IntVar(&p_adultsVar, "adults", 2, "adults Adults: Number of adult guests across all rooms. (required)")
	_ = cmd.MarkFlagRequired("adults")
	cmd.Flags().IntVar(&p_bathroomsVar, "bathrooms", 0, "bathrooms Bathrooms: Minimum number of bathrooms in the property.")
	cmd.Flags().StringSliceVar(&p_bedPreferenceVar, "bed-preference", nil, "bedPreference[] Bed Preference: Filter by bed configuration. Multiple values are combined with OR.")
	_ = cmd.RegisterFlagCompletionFunc("bed-preference", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"twinBeds", "doubleBed"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().IntVar(&p_bedroomsVar, "bedrooms", 0, "bedrooms Bedrooms: Minimum number of bedrooms in the property.")
	cmd.Flags().StringVar(&p_checkInDateVar, "check-in-date", "2026-06-01", "checkInDate Check-in Date: Check-in date in `YYYY-MM-DD` format. Must be in the future and earlier than `checkOutDate`. (required)")
	_ = cmd.MarkFlagRequired("check-in-date")
	cmd.Flags().StringVar(&p_checkOutDateVar, "check-out-date", "2026-06-05", "checkOutDate Check-out Date: Check-out date in `YYYY-MM-DD` format. Must be later than `checkInDate`. (required)")
	_ = cmd.MarkFlagRequired("check-out-date")
	cmd.Flags().IntVar(&p_childrenVar, "children", 0, "children Children Count: Number of child guests across all rooms (0–10). Pass `0` if there are no children. (required)")
	_ = cmd.MarkFlagRequired("children")
	cmd.Flags().StringVar(&p_childrenAgesJsonVar, "children-ages-json", "", "childrenAgesJson Children Ages: JSON-encoded array of child ages, one entry per child (each `0`–`17`). Required when `children > 0` and the array length must equal `children`. Must not be passed when `children = 0`.\n\nExample: `[1, 3, 7]`\n")
	cmd.Flags().StringVar(&p_currencyVar, "currency", "", "currency Currency: Currency of the prices returned in the response. Use `hotelCurrency` to keep each property's native currency.")
	cmd.Flags().StringSliceVar(&p_distanceFromCenterVar, "distance-from-center", nil, "distanceFromCenter[] Distance from Center: Filter by distance from the destination center. Multiple values are combined with OR.")
	_ = cmd.RegisterFlagCompletionFunc("distance-from-center", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"lessThan1Km", "lessThan3Km", "lessThan5Km"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringSliceVar(&p_facilitiesVar, "facilities", nil, "facilities[] Hotel Facilities: Filter by property-level facilities. Multiple values are combined with OR.")
	_ = cmd.RegisterFlagCompletionFunc("facilities", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"swimmingPool", "parking", "spa", "freeWifi", "hotTubJacuzzi", "airportShuttle", "fitnessCenter", "restaurant", "nonSmokingRooms", "frontDesk24Hour", "electricVehicleChargingStation", "wheelchairAccessible", "roomService"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_keywordVar, "keyword", "Paris", "keyword Search Query: Free-text destination query. Usually a city, region or neighborhood (e.g. `Paris`, `Manhattan, New York`); a specific property name is also accepted. (required)")
	_ = cmd.MarkFlagRequired("keyword")
	cmd.Flags().StringVar(&p_languageVar, "language", "", "language Language: Language of the Booking.com interface and localized fields in the response.")
	cmd.Flags().StringSliceVar(&p_mealsVar, "meals", nil, "meals[] Meals: Filter by available meal plans. Multiple values are combined with OR.")
	_ = cmd.RegisterFlagCompletionFunc("meals", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"breakfastIncluded", "kitchenFacilities"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringSliceVar(&p_onlinePaymentVar, "online-payment", nil, "onlinePayment[] Online Payment: Filter by online payment options.")
	_ = cmd.RegisterFlagCompletionFunc("online-payment", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"acceptsOnlinePayments"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().IntVar(&p_pageVar, "page", 0, "page Page Number: Page number of the search results. Booking.com returns 25 results per page; pass `2` for results 26–50, `3` for 51–75, etc.")
	cmd.Flags().Float64Var(&p_price_maxVar, "price-max", 0, "price[max] Price Max: Maximum total price for the stay, in the requested `currency`. Must be `>= 20` and greater than `price[min]`. Required if `price[min]` is omitted.")
	cmd.Flags().Float64Var(&p_price_minVar, "price-min", 0, "price[min] Price Min: Minimum total price for the stay, in the requested `currency`. Must be `>= 10`. Required if `price[max]` is omitted.")
	cmd.Flags().StringSliceVar(&p_propertyAccessibilityVar, "property-accessibility", nil, "propertyAccessibility[] Property Accessibility: Filter by property-level accessibility features. Multiple values are combined with OR.")
	_ = cmd.RegisterFlagCompletionFunc("property-accessibility", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"auditoryGuidance", "toiletWithGrabRails", "visualAidsTactileSigns", "visualAidsBraille", "bathroomEmergencyCord", "raisedToilet", "loweredSink"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringSliceVar(&p_propertyTypeVar, "property-type", nil, "propertyType[] Property Type: Filter by property type. Multiple values are combined with OR.")
	_ = cmd.RegisterFlagCompletionFunc("property-type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"hostels", "bedAndBreakfast", "hotels", "apartments", "resorts", "guesthouses", "homestays", "entireHomesAndApartments"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringSliceVar(&p_ratingVar, "rating", nil, "rating[] Star Rating: Filter by official star rating. Multiple values are combined with OR.")
	_ = cmd.RegisterFlagCompletionFunc("rating", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"oneStar", "twoStars", "threeStars", "fourStars", "fiveStars"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringSliceVar(&p_reservationPolicyVar, "reservation-policy", nil, "reservationPolicy[] Reservation Policy: Filter by reservation flexibility. Multiple values are combined with OR.")
	_ = cmd.RegisterFlagCompletionFunc("reservation-policy", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"freeCancellation", "noPrepayment"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringSliceVar(&p_reviewScoreVar, "review-score", nil, "reviewScore[] Review Score: Filter by minimum guest review score bucket. Multiple values are combined with OR.")
	_ = cmd.RegisterFlagCompletionFunc("review-score", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"wonderful", "veryGood", "good", "pleasant"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringSliceVar(&p_roomAccessibilityVar, "room-accessibility", nil, "roomAccessibility[] Room Accessibility: Filter by in-room accessibility features. Multiple values are combined with OR.")
	_ = cmd.RegisterFlagCompletionFunc("room-accessibility", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"upperFloorsAccessibleByElevator", "entireUnitLocatedOnGroundFloor", "walkInShower", "entireUnitWheelchairAccessible", "adaptedBath", "rollInShower", "showerChair", "emergencyCordInBathroom", "toiletWithGrabRails", "raisedToilet", "lowerSink"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringSliceVar(&p_roomFacilitiesVar, "room-facilities", nil, "roomFacilities[] Room Facilities: Filter by in-room facilities. Multiple values are combined with OR.")
	_ = cmd.RegisterFlagCompletionFunc("room-facilities", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"privateBathroom", "balcony", "seaView", "kitchenKitchenette", "airConditioning", "bathtub", "hotTub", "view", "spaTub", "upperFloorsAccessibleByElevator", "microwave", "refrigerator", "coffeeMachine", "electricKettle", "heating", "towels", "toilet", "mountainView", "flatScreenTv", "tv", "coffeeTeaMaker", "hairdryer", "toiletPaper", "shower", "linens"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().IntVar(&p_roomsVar, "rooms", 1, "rooms Rooms: Number of rooms to book. (required)")
	_ = cmd.MarkFlagRequired("rooms")
	cmd.Flags().StringVar(&p_sortVar, "sort", "", "sort Sort Order: Sort order applied by Booking.com to the results page. [allowed: ourTopPicks|homesAndApartmentsFirst|priceLowestFirst|priceHighestFirst|bestReviewedAndLowestPrice|ratingHighToLow|ratingLowToHigh|ratingAndPrice|distanceFromDowntown|topReviewed]")
	_ = cmd.RegisterFlagCompletionFunc("sort", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"ourTopPicks", "homesAndApartmentsFirst", "priceLowestFirst", "priceHighestFirst", "bestReviewedAndLowestPrice", "ratingHighToLow", "ratingLowToHigh", "ratingAndPrice", "distanceFromDowntown", "topReviewed"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringSliceVar(&p_travelGroupVar, "travel-group", nil, "travelGroup[] Travel Group: Filter by travel-group oriented stay options. Multiple values are combined with OR.")
	_ = cmd.RegisterFlagCompletionFunc("travel-group", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"adultsOnly", "petFriendly"}, cobra.ShellCompDirectiveNoFileComp
	})

	return cmd
}

func init() {
	RegisterAPICommand("booking", "Booking", newBookingSearchCmd())
}
