// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newChatGptChatCmd() *cobra.Command {
	var p_promptVar string
	var p_timezoneVar string

	cmd := &cobra.Command{
		Use:   "chat-gpt-chat",
		Short: "ChatGPT Scraper API  (10 credits/call)",
		Long:  "The ChatGPT Scraper API sends a prompt to ChatGPT and returns the answer as text, together with the web sources ChatGPT consulted when it decided to search the web. No OpenAI account or API key is needed.\n\nEndpoint: GET https://api.hasdata.com/scrape/chatgpt/chat\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("prompt", p_promptVar)
			if c.Flags().Changed("timezone") {
				params.Set("timezone", p_timezoneVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/chatgpt/chat", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_promptVar, "prompt", "What are the latest developments in the James Webb Space Telescope this month?", "prompt Prompt: The question or instruction to send to ChatGPT, up to 8000 characters. A prompt that asks about recent events makes ChatGPT search the web and return sources; a general-knowledge prompt is answered from the model alone. The prompt also decides the language of the answer — write it in the language you want back, or ask for one explicitly (\"Antworte auf Deutsch\"). (required)")
	_ = cmd.MarkFlagRequired("prompt")
	cmd.Flags().StringVar(&p_timezoneVar, "timezone", "Europe/Berlin", "timezone Timezone: IANA time zone name, for example `America/Chicago` or `Europe/Berlin`. It sets what ChatGPT treats as the current date and time, which matters for prompts that say \"today\", \"this week\" or \"latest\".")

	return cmd
}

func init() {
	RegisterAPICommand("ai", "AI", newChatGptChatCmd())
}
