// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newBookingPlaceCmd() *cobra.Command {
	var p_adultsVar int
	var p_checkInDateVar string
	var p_checkOutDateVar string
	var p_childrenVar int
	var p_childrenAgesJsonVar string
	var p_currencyVar string
	var p_languageVar string
	var p_roomsVar int
	var p_urlVar string

	cmd := &cobra.Command{
		Use:   "booking-place",
		Short: "Booking Place API  (10 credits/call)",
		Long:  "The Booking Place API returns full details for a single Booking.com property along with the list of available room suites for the requested stay dates and guest composition.\n\nEndpoint: GET https://api.hasdata.com/scrape/booking/place\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("adults", strconv.Itoa(p_adultsVar))
			params.Set("checkInDate", p_checkInDateVar)
			params.Set("checkOutDate", p_checkOutDateVar)
			params.Set("children", strconv.Itoa(p_childrenVar))
			if c.Flags().Changed("children-ages-json") {
				params.Set("childrenAgesJson", p_childrenAgesJsonVar)
			}
			if c.Flags().Changed("currency") {
				params.Set("currency", p_currencyVar)
			}
			if c.Flags().Changed("language") {
				params.Set("language", p_languageVar)
			}
			params.Set("rooms", strconv.Itoa(p_roomsVar))
			params.Set("url", p_urlVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/booking/place", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().IntVar(&p_adultsVar, "adults", 2, "adults Adults: Number of adult guests across all rooms. (required)")
	_ = cmd.MarkFlagRequired("adults")
	cmd.Flags().StringVar(&p_checkInDateVar, "check-in-date", "2026-06-01", "checkInDate Check-in Date: Check-in date in `YYYY-MM-DD` format. Must be in the future and earlier than `checkOutDate`. (required)")
	_ = cmd.MarkFlagRequired("check-in-date")
	cmd.Flags().StringVar(&p_checkOutDateVar, "check-out-date", "2026-06-05", "checkOutDate Check-out Date: Check-out date in `YYYY-MM-DD` format. Must be later than `checkInDate`. (required)")
	_ = cmd.MarkFlagRequired("check-out-date")
	cmd.Flags().IntVar(&p_childrenVar, "children", 0, "children Children Count: Number of child guests across all rooms (0–10). Pass `0` if there are no children. (required)")
	_ = cmd.MarkFlagRequired("children")
	cmd.Flags().StringVar(&p_childrenAgesJsonVar, "children-ages-json", "", "childrenAgesJson Children Ages: JSON-encoded array of child ages, one entry per child (each `0`–`17`). Required when `children > 0` and the array length must equal `children`. Must not be passed when `children = 0`.\n\nExample: `[1, 3, 7]`\n")
	cmd.Flags().StringVar(&p_currencyVar, "currency", "", "currency Currency: Currency of the prices returned in the response. Use `hotelCurrency` to keep each property's native currency.")
	cmd.Flags().StringVar(&p_languageVar, "language", "", "language Language: Language of the Booking.com interface and localized fields in the response.")
	cmd.Flags().IntVar(&p_roomsVar, "rooms", 1, "rooms Rooms: Number of rooms to book. (required)")
	_ = cmd.MarkFlagRequired("rooms")
	cmd.Flags().StringVar(&p_urlVar, "url", "https://www.booking.com/hotel/fr/le-bristol-paris.html", "url Property URL: Full Booking.com URL of the property page. Only `booking.com` and `www.booking.com` hosts are accepted. (required)")
	_ = cmd.MarkFlagRequired("url")

	return cmd
}

func init() {
	RegisterAPICommand("booking", "Booking", newBookingPlaceCmd())
}
