// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newGoogleMapsContributorReviewsCmd() *cobra.Command {
	var p_contributorIdVar string
	var p_glVar string
	var p_hlVar string
	var p_nextPageTokenVar string
	var p_numVar int

	cmd := &cobra.Command{
		Use:   "google-maps-contributor-reviews",
		Short: "Google Maps Contributor Reviews API  (5 credits/call)",
		Long:  "The Google Maps Contributor Reviews API allows to retrieve reviews submitted by specific users on Google Maps.\n\nEndpoint: GET https://api.hasdata.com/scrape/google-maps/contributor-reviews\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("contributorId", p_contributorIdVar)
			if c.Flags().Changed("gl") {
				params.Set("gl", p_glVar)
			}
			if c.Flags().Changed("hl") {
				params.Set("hl", p_hlVar)
			}
			if c.Flags().Changed("next-page-token") {
				params.Set("nextPageToken", p_nextPageTokenVar)
			}
			if c.Flags().Changed("num") {
				params.Set("num", strconv.Itoa(p_numVar))
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/google-maps/contributor-reviews", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_contributorIdVar, "contributor-id", "117472887966458832611", "contributorId Contributor ID: Google Maps Contributor ID. (required)")
	_ = cmd.MarkFlagRequired("contributor-id")
	cmd.Flags().StringVar(&p_glVar, "gl", "", "gl Country: The two-letter country code for the country you want to limit the search to.")
	cmd.Flags().StringVar(&p_hlVar, "hl", "", "hl Language: The two-letter language code for the language you want to use for the search.")
	cmd.Flags().StringVar(&p_nextPageTokenVar, "next-page-token", "", "nextPageToken Next Page Token: Defines the next page token. It is used for retrieving the next page results.")
	cmd.Flags().IntVar(&p_numVar, "num", 0, "num Number of Results: Number of results per page, ranging from 10 to 200.")

	return cmd
}

func init() {
	RegisterAPICommand("google_maps", "Google Maps", newGoogleMapsContributorReviewsCmd())
}
