// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newGoogleMapsReviewsCmd() *cobra.Command {
	var p_dataIdVar string
	var p_hlVar string
	var p_nextPageTokenVar string
	var p_placeIdVar string
	var p_sortByVar string
	var p_topicIdVar string

	cmd := &cobra.Command{
		Use:   "google-maps-reviews",
		Short: "Google Maps Reviews API  (5 credits/call)",
		Long:  "The Google Maps Reviews API provides access to reviews from Google Maps, with options to specify the data ID, place ID, language, sorting parameters, and topic filters.\n\nEndpoint: GET https://api.hasdata.com/scrape/google-maps/reviews\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("sort-by") {
				if err := validateEnumString("sort-by", p_sortByVar, []string{"qualityScore", "newestFirst", "ratingHigh", "ratingLow"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("data-id") {
				params.Set("dataId", p_dataIdVar)
			}
			if c.Flags().Changed("hl") {
				params.Set("hl", p_hlVar)
			}
			if c.Flags().Changed("next-page-token") {
				params.Set("nextPageToken", p_nextPageTokenVar)
			}
			if c.Flags().Changed("place-id") {
				params.Set("placeId", p_placeIdVar)
			}
			if c.Flags().Changed("sort-by") {
				params.Set("sortBy", p_sortByVar)
			}
			if c.Flags().Changed("topic-id") {
				params.Set("topicId", p_topicIdVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/google-maps/reviews", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_dataIdVar, "data-id", "0x873312ae759b4d15:0x1f38a9bec9912029", "dataId Data ID: Google Maps data ID.")
	cmd.Flags().StringVar(&p_hlVar, "hl", "", "hl Language: The two-letter language code for the language you want to use for the search.")
	cmd.Flags().StringVar(&p_nextPageTokenVar, "next-page-token", "", "nextPageToken Next Page Token: Defines the next page token. It is used for retrieving the next page results.")
	cmd.Flags().StringVar(&p_placeIdVar, "place-id", "", "placeId Place ID: Unique reference to a place on a Google Map. Either dataId or placeId should be set.")
	cmd.Flags().StringVar(&p_sortByVar, "sort-by", "", "sortBy Sort By: Parameter used for sorting and refining results. [allowed: qualityScore|newestFirst|ratingHigh|ratingLow]")
	_ = cmd.RegisterFlagCompletionFunc("sort-by", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"qualityScore", "newestFirst", "ratingHigh", "ratingLow"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_topicIdVar, "topic-id", "", "topicId Topic ID: Defines the ID of the topic you want to use for filtering reviews.")

	return cmd
}

func init() {
	RegisterAPICommand("google_maps", "Google Maps", newGoogleMapsReviewsCmd())
}
