// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newZillowListingCmd() *cobra.Command {
	var p_basementVar []string
	var p_baths_maxVar float64
	var p_baths_minVar float64
	var p_beds_maxVar float64
	var p_beds_minVar float64
	var p_daysOnZillowVar string
	var p_hide55plusCommunitiesVar bool
	var p_hoaVar float64
	var p_homeTypesVar []string
	var p_keywordVar string
	var p_keywordsVar string
	var p_listingPublishOptionsVar []string
	var p_listingTypeVar string
	var p_lotSize_maxVar float64
	var p_lotSize_minVar float64
	var p_moveInDateVar string
	var p_mustHaveGarageVar bool
	var p_otherAmenitiesVar []string
	var p_pageVar float64
	var p_parkingSpotsMinVar float64
	var p_petsVar []string
	var p_price_maxVar float64
	var p_price_minVar float64
	var p_propertyStatusVar []string
	var p_singleStoryOnlyVar bool
	var p_sortVar string
	var p_squareFeet_maxVar float64
	var p_squareFeet_minVar float64
	var p_toursVar []string
	var p_typeVar string
	var p_viewsVar []string
	var p_yearBuilt_maxVar float64
	var p_yearBuilt_minVar float64

	cmd := &cobra.Command{
		Use:   "zillow-listing",
		Short: "Zillow Listing API  (5 credits/call)",
		Long:  "The Zillow Listing API allows you to retrieve real estate listings from Zillow based on various search parameters.\n\nEndpoint: GET https://api.hasdata.com/scrape/zillow/listing\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("basement") {
				if err := validateEnumStringSlice("basement", p_basementVar, []string{"finished", "unfinished"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("days-on-zillow") {
				if err := validateEnumString("days-on-zillow", p_daysOnZillowVar, []string{"6m", "12m", "24m", "36m"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("home-types") {
				if err := validateEnumStringSlice("home-types", p_homeTypesVar, []string{"house", "townhome", "multiFamily", "condo", "lot", "apartment", "manufactured"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("listing-publish-options") {
				if err := validateEnumStringSlice("listing-publish-options", p_listingPublishOptionsVar, []string{"ownerPosted", "agentListed", "newConstruction", "foreclosures", "auctions", "foreclosed", "preForeclosures"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("listing-type") {
				if err := validateEnumString("listing-type", p_listingTypeVar, []string{"byAgent", "byOwner"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("other-amenities") {
				if err := validateEnumStringSlice("other-amenities", p_otherAmenitiesVar, []string{"ac", "pool", "waterfront", "onsiteParking", "inUnitLaundry", "acceptZillowApplications", "incomeRestricted", "apartmentCommunity"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("pets") {
				if err := validateEnumStringSlice("pets", p_petsVar, []string{"allowsLargeDogs", "allowsSmallDogs", "allowsCats"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("property-status") {
				if err := validateEnumStringSlice("property-status", p_propertyStatusVar, []string{"comingSoon", "acceptingBackupOffers", "pendingAndUnderContract"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("sort") {
				if err := validateEnumString("sort", p_sortVar, []string{"verifiedSource", "homesForYou", "priceHighToLow", "priceLowToHigh", "paymentHighToLow", "paymentLowToHigh", "newest", "bedrooms", "bathrooms", "squareFeet", "lotSize"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("tours") {
				if err := validateEnumStringSlice("tours", p_toursVar, []string{"open", "3d"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("type") {
				if err := validateEnumString("type", p_typeVar, []string{"forSale", "forRent", "sold"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("views") {
				if err := validateEnumStringSlice("views", p_viewsVar, []string{"city", "mountain", "park", "water"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("basement") {
				for _, v := range p_basementVar {
					params.Add("basement"+"[]", v)
				}
			}
			if c.Flags().Changed("baths-max") {
				params.Set("baths[max]", strconv.FormatFloat(p_baths_maxVar, 'f', -1, 64))
			}
			if c.Flags().Changed("baths-min") {
				params.Set("baths[min]", strconv.FormatFloat(p_baths_minVar, 'f', -1, 64))
			}
			if c.Flags().Changed("beds-max") {
				params.Set("beds[max]", strconv.FormatFloat(p_beds_maxVar, 'f', -1, 64))
			}
			if c.Flags().Changed("beds-min") {
				params.Set("beds[min]", strconv.FormatFloat(p_beds_minVar, 'f', -1, 64))
			}
			if c.Flags().Changed("days-on-zillow") {
				params.Set("daysOnZillow", p_daysOnZillowVar)
			}
			if c.Flags().Changed("hide55plus-communities") {
				params.Set("hide55plusCommunities", strconv.FormatBool(p_hide55plusCommunitiesVar))
			}
			if c.Flags().Changed("hoa") {
				params.Set("hoa", strconv.FormatFloat(p_hoaVar, 'f', -1, 64))
			}
			if c.Flags().Changed("home-types") {
				for _, v := range p_homeTypesVar {
					params.Add("homeTypes"+"[]", v)
				}
			}
			params.Set("keyword", p_keywordVar)
			if c.Flags().Changed("keywords") {
				params.Set("keywords", p_keywordsVar)
			}
			if c.Flags().Changed("listing-publish-options") {
				for _, v := range p_listingPublishOptionsVar {
					params.Add("listingPublishOptions"+"[]", v)
				}
			}
			if c.Flags().Changed("listing-type") {
				params.Set("listingType", p_listingTypeVar)
			}
			if c.Flags().Changed("lot-size-max") {
				params.Set("lotSize[max]", strconv.FormatFloat(p_lotSize_maxVar, 'f', -1, 64))
			}
			if c.Flags().Changed("lot-size-min") {
				params.Set("lotSize[min]", strconv.FormatFloat(p_lotSize_minVar, 'f', -1, 64))
			}
			if c.Flags().Changed("move-in-date") {
				params.Set("moveInDate", p_moveInDateVar)
			}
			if c.Flags().Changed("must-have-garage") {
				params.Set("mustHaveGarage", strconv.FormatBool(p_mustHaveGarageVar))
			}
			if c.Flags().Changed("other-amenities") {
				for _, v := range p_otherAmenitiesVar {
					params.Add("otherAmenities"+"[]", v)
				}
			}
			if c.Flags().Changed("page") {
				params.Set("page", strconv.FormatFloat(p_pageVar, 'f', -1, 64))
			}
			if c.Flags().Changed("parking-spots-min") {
				params.Set("parkingSpotsMin", strconv.FormatFloat(p_parkingSpotsMinVar, 'f', -1, 64))
			}
			if c.Flags().Changed("pets") {
				for _, v := range p_petsVar {
					params.Add("pets"+"[]", v)
				}
			}
			if c.Flags().Changed("price-max") {
				params.Set("price[max]", strconv.FormatFloat(p_price_maxVar, 'f', -1, 64))
			}
			if c.Flags().Changed("price-min") {
				params.Set("price[min]", strconv.FormatFloat(p_price_minVar, 'f', -1, 64))
			}
			if c.Flags().Changed("property-status") {
				for _, v := range p_propertyStatusVar {
					params.Add("propertyStatus"+"[]", v)
				}
			}
			if c.Flags().Changed("single-story-only") {
				params.Set("singleStoryOnly", strconv.FormatBool(p_singleStoryOnlyVar))
			}
			if c.Flags().Changed("sort") {
				params.Set("sort", p_sortVar)
			}
			if c.Flags().Changed("square-feet-max") {
				params.Set("squareFeet[max]", strconv.FormatFloat(p_squareFeet_maxVar, 'f', -1, 64))
			}
			if c.Flags().Changed("square-feet-min") {
				params.Set("squareFeet[min]", strconv.FormatFloat(p_squareFeet_minVar, 'f', -1, 64))
			}
			if c.Flags().Changed("tours") {
				for _, v := range p_toursVar {
					params.Add("tours"+"[]", v)
				}
			}
			params.Set("type", p_typeVar)
			if c.Flags().Changed("views") {
				for _, v := range p_viewsVar {
					params.Add("views"+"[]", v)
				}
			}
			if c.Flags().Changed("year-built-max") {
				params.Set("yearBuilt[max]", strconv.FormatFloat(p_yearBuilt_maxVar, 'f', -1, 64))
			}
			if c.Flags().Changed("year-built-min") {
				params.Set("yearBuilt[min]", strconv.FormatFloat(p_yearBuilt_minVar, 'f', -1, 64))
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/zillow/listing", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringSliceVar(&p_basementVar, "basement", nil, "basement[] Basement: An array of basement options.")
	_ = cmd.RegisterFlagCompletionFunc("basement", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"finished", "unfinished"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().Float64Var(&p_baths_maxVar, "baths-max", 0, "baths[max] Baths Max: The maximum number of bathrooms.")
	cmd.Flags().Float64Var(&p_baths_minVar, "baths-min", 0, "baths[min] Baths Min: The minimum number of bathrooms.")
	cmd.Flags().Float64Var(&p_beds_maxVar, "beds-max", 0, "beds[max] Beds Max: The maximum number of bedrooms.")
	cmd.Flags().Float64Var(&p_beds_minVar, "beds-min", 0, "beds[min] Beds Min: The minimum number of bedrooms.")
	cmd.Flags().StringVar(&p_daysOnZillowVar, "days-on-zillow", "", "daysOnZillow Days on Zillow: The number of days a listing has been on Zillow. [allowed: 6m|12m|24m|36m]")
	_ = cmd.RegisterFlagCompletionFunc("days-on-zillow", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"6m", "12m", "24m", "36m"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().BoolVar(&p_hide55plusCommunitiesVar, "hide55plus-communities", false, "hide55plusCommunities Hide 55+ Communities: If set to true, 55+ communities will be excluded.")
	cmd.Flags().Float64Var(&p_hoaVar, "hoa", 0, "hoa HOA: The Homeowners Association (HOA) fee.")
	cmd.Flags().StringSliceVar(&p_homeTypesVar, "home-types", nil, "homeTypes[] Home Types: An array of home types to filter the listings.")
	_ = cmd.RegisterFlagCompletionFunc("home-types", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"house", "townhome", "multiFamily", "condo", "lot", "apartment", "manufactured"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_keywordVar, "keyword", "New York, NY", "keyword Location: The keyword used to search for listings. (required)")
	_ = cmd.MarkFlagRequired("keyword")
	cmd.Flags().StringVar(&p_keywordsVar, "keywords", "", "keywords Additional Keywords: Additional keywords to refine the search.")
	cmd.Flags().StringSliceVar(&p_listingPublishOptionsVar, "listing-publish-options", nil, "listingPublishOptions[] Listing Publish Options: An array of listing publish options.")
	_ = cmd.RegisterFlagCompletionFunc("listing-publish-options", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"ownerPosted", "agentListed", "newConstruction", "foreclosures", "auctions", "foreclosed", "preForeclosures"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_listingTypeVar, "listing-type", "", "listingType Listing Category: The category of the listing. [allowed: byAgent|byOwner]")
	_ = cmd.RegisterFlagCompletionFunc("listing-type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"byAgent", "byOwner"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().Float64Var(&p_lotSize_maxVar, "lot-size-max", 0, "lotSize[max] Lot Size Max: The maximum lot size.")
	cmd.Flags().Float64Var(&p_lotSize_minVar, "lot-size-min", 0, "lotSize[min] Lot Size Min: The minimum lot size.")
	cmd.Flags().StringVar(&p_moveInDateVar, "move-in-date", "", "moveInDate Move In Date: The desired move-in date.")
	cmd.Flags().BoolVar(&p_mustHaveGarageVar, "must-have-garage", false, "mustHaveGarage Must Have Garage: If set to true, only listings with a garage will be included.")
	cmd.Flags().StringSliceVar(&p_otherAmenitiesVar, "other-amenities", nil, "otherAmenities[] Other Amenities: An array of other amenities.")
	_ = cmd.RegisterFlagCompletionFunc("other-amenities", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"ac", "pool", "waterfront", "onsiteParking", "inUnitLaundry", "acceptZillowApplications", "incomeRestricted", "apartmentCommunity"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().Float64Var(&p_pageVar, "page", 0, "page Page Number: The page number of the results to retrieve.")
	cmd.Flags().Float64Var(&p_parkingSpotsMinVar, "parking-spots-min", 0, "parkingSpotsMin Parking Spots Min: The minimum number of parking spots.")
	cmd.Flags().StringSliceVar(&p_petsVar, "pets", nil, "pets[] pets: An array of pet options.")
	_ = cmd.RegisterFlagCompletionFunc("pets", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"allowsLargeDogs", "allowsSmallDogs", "allowsCats"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().Float64Var(&p_price_maxVar, "price-max", 0, "price[max] Price Max: The maximum price of the listing.")
	cmd.Flags().Float64Var(&p_price_minVar, "price-min", 0, "price[min] Price Min: The minimum price of the listing.")
	cmd.Flags().StringSliceVar(&p_propertyStatusVar, "property-status", nil, "propertyStatus[] Property Status: An array of property statuses.")
	_ = cmd.RegisterFlagCompletionFunc("property-status", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"comingSoon", "acceptingBackupOffers", "pendingAndUnderContract"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().BoolVar(&p_singleStoryOnlyVar, "single-story-only", false, "singleStoryOnly Single Story Only: If set to true, only single-story properties will be included.")
	cmd.Flags().StringVar(&p_sortVar, "sort", "", "sort Sort By: The sorting option for the search results. [allowed: verifiedSource|homesForYou|priceHighToLow|priceLowToHigh|paymentHighToLow|paymentLowToHigh|newest|bedrooms|bathrooms|squareFeet|lotSize]")
	_ = cmd.RegisterFlagCompletionFunc("sort", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"verifiedSource", "homesForYou", "priceHighToLow", "priceLowToHigh", "paymentHighToLow", "paymentLowToHigh", "newest", "bedrooms", "bathrooms", "squareFeet", "lotSize"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().Float64Var(&p_squareFeet_maxVar, "square-feet-max", 0, "squareFeet[max] Square Feet Max: The maximum square footage.")
	cmd.Flags().Float64Var(&p_squareFeet_minVar, "square-feet-min", 0, "squareFeet[min] Square Feet Min: The minimum square footage.")
	cmd.Flags().StringSliceVar(&p_toursVar, "tours", nil, "tours[] Tours: An array of tour options.")
	_ = cmd.RegisterFlagCompletionFunc("tours", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"open", "3d"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_typeVar, "type", "forSale", "type Listing Type: The type of listing. [allowed: forSale|forRent|sold] (required)")
	_ = cmd.MarkFlagRequired("type")
	_ = cmd.RegisterFlagCompletionFunc("type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"forSale", "forRent", "sold"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringSliceVar(&p_viewsVar, "views", nil, "views[] Views: An array of views.")
	_ = cmd.RegisterFlagCompletionFunc("views", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"city", "mountain", "park", "water"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().Float64Var(&p_yearBuilt_maxVar, "year-built-max", 0, "yearBuilt[max] Year Built Max: The maximum year the property was built.")
	cmd.Flags().Float64Var(&p_yearBuilt_minVar, "year-built-min", 0, "yearBuilt[min] Year Built Min: The minimum year the property was built.")

	return cmd
}

func init() {
	RegisterAPICommand("zillow", "Zillow", newZillowListingCmd())
}
