// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newTiktokSearchCmd() *cobra.Command {
	var p_keywordVar string
	var p_nextPageTokenVar string
	var p_typeVar string

	cmd := &cobra.Command{
		Use:   "tiktok-search",
		Short: "TikTok Search Scraper API  (10 credits/call)",
		Long:  "The TikTok Search Scraper API lets you search TikTok by keyword for videos or users. Video results include description, hashtags, stats, cover and playable URLs, and author info; user results include nickname, bio, avatar, verified flag, and follower count. Results are paginated with a token.\n\nEndpoint: GET https://api.hasdata.com/scrape/tiktok/search\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("type") {
				if err := validateEnumString("type", p_typeVar, []string{"video", "user"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("keyword", p_keywordVar)
			if c.Flags().Changed("next-page-token") {
				params.Set("nextPageToken", p_nextPageTokenVar)
			}
			if c.Flags().Changed("type") {
				params.Set("type", p_typeVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/tiktok/search", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_keywordVar, "keyword", "dance", "keyword Keyword: The phrase to search for on TikTok. (required)")
	_ = cmd.MarkFlagRequired("keyword")
	cmd.Flags().StringVar(&p_nextPageTokenVar, "next-page-token", "", "nextPageToken Next Page Token: Defines the next page token. Use the `nextPageToken` value returned by the previous response. Omit it to fetch the first page.")
	cmd.Flags().StringVar(&p_typeVar, "type", "", "type Result Type: What to search for — videos or users. Defaults to video. [allowed: video|user]")
	_ = cmd.RegisterFlagCompletionFunc("type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"video", "user"}, cobra.ShellCompDirectiveNoFileComp
	})

	return cmd
}

func init() {
	RegisterAPICommand("social", "Social", newTiktokSearchCmd())
}
