// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newGoogleScholarCiteCmd() *cobra.Command {
	var p_hlVar string
	var p_qVar string

	cmd := &cobra.Command{
		Use:   "google-scholar-cite",
		Short: "Google Scholar Cite API  (5 credits/call)",
		Long:  "Provides real-time access to Google Scholar citation formats and reference-manager export links for a single organic search result.\n\nEndpoint: GET https://api.hasdata.com/scrape/google/scholar-cite\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("hl") {
				params.Set("hl", p_hlVar)
			}
			params.Set("q", p_qVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/google/scholar-cite", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_hlVar, "hl", "", "hl Language: The two-letter language code for the language you want to use for the search.")
	cmd.Flags().StringVar(&p_qVar, "q", "EQ8shYj8Ai8J", "q Result ID: The `resultId` of a Google Scholar organic result, as returned by the google/scholar endpoint. (required)")
	_ = cmd.MarkFlagRequired("q")

	return cmd
}

func init() {
	RegisterAPICommand("google_scholar", "Google Scholar", newGoogleScholarCiteCmd())
}
