// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newYoutubeTranscriptApiCmd() *cobra.Command {
	var p_languageCodeVar string
	var p_typeVar string
	var p_vVar string

	cmd := &cobra.Command{
		Use:   "youtube-transcript-api",
		Short: "YouTube Transcript API  (10 credits/call)",
		Long:  "The YouTube Transcript API extracts the full transcript (subtitles) from a YouTube video.\n\nEndpoint: GET https://api.hasdata.com/scrape/youtube/transcript\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("language-code") {
				params.Set("languageCode", p_languageCodeVar)
			}
			if c.Flags().Changed("type") {
				params.Set("type", p_typeVar)
			}
			params.Set("v", p_vVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/youtube/transcript", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_languageCodeVar, "language-code", "en", "languageCode Language Code: Language code for the transcript (e.g. `en`, `de`, `en-US`).")
	cmd.Flags().StringVar(&p_typeVar, "type", "", "type Transcript Type: Transcript type (e.g. `asr` for auto-generated).")
	cmd.Flags().StringVar(&p_vVar, "v-param", "dQw4w9WgXcQ", "v Video ID: YouTube video ID (e.g. `dQw4w9WgXcQ`). (required)")
	_ = cmd.MarkFlagRequired("v-param")

	return cmd
}

func init() {
	RegisterAPICommand("youtube", "YouTube", newYoutubeTranscriptApiCmd())
}
