// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newZillowPropertyCmd() *cobra.Command {
	var p_extractAgentEmailsVar bool
	var p_urlVar string

	cmd := &cobra.Command{
		Use:   "zillow-property",
		Short: "Zillow Property API  (5 credits/call)",
		Long:  "The Zillow Property API allows users to retrieve detailed information about a specific property using its URL. It provides details such as property features, price, and agent contacts.\n\nEndpoint: GET https://api.hasdata.com/scrape/zillow/property\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("extract-agent-emails") {
				params.Set("extractAgentEmails", strconv.FormatBool(p_extractAgentEmailsVar))
			}
			params.Set("url", p_urlVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/zillow/property", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().BoolVar(&p_extractAgentEmailsVar, "extract-agent-emails", false, "extractAgentEmails Extract Agent Emails: If enabled, attempts to extract agent email addresses from the property details. Increases the cost of the request.")
	cmd.Flags().StringVar(&p_urlVar, "url", "https://www.zillow.com/homedetails/301-E-79th-St-APT-23S-New-York-NY-10075/31543731_zpid/", "url Property URL: The URL of the property on Zillow. Must be a valid Zillow property URL. (required)")
	_ = cmd.MarkFlagRequired("url")

	return cmd
}

func init() {
	RegisterAPICommand("zillow", "Zillow", newZillowPropertyCmd())
}
