// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newAirbnbPropertyCmd() *cobra.Command {
	var p_urlVar string

	cmd := &cobra.Command{
		Use:   "airbnb-property",
		Short: "Airbnb Property API  (5 credits/call)",
		Long:  "The Airbnb Property API allows users to retrieve detailed information about a specific Airbnb listing using its URL.\n\nEndpoint: GET https://api.hasdata.com/scrape/airbnb/property\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("url", p_urlVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/airbnb/property", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_urlVar, "url", "https://www.airbnb.com/rooms/7777642", "url Property URL: The URL of the Airbnb listing. Must be a valid Airbnb listing URL. (required)")
	_ = cmd.MarkFlagRequired("url")

	return cmd
}

func init() {
	RegisterAPICommand("airbnb", "Airbnb", newAirbnbPropertyCmd())
}
