// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newYoutubeVideoApiCmd() *cobra.Command {
	var p_deviceTypeVar string
	var p_glVar string
	var p_hlVar string
	var p_vVar string

	cmd := &cobra.Command{
		Use:   "youtube-video-api",
		Short: "YouTube Video API  (10 credits/call)",
		Long:  "The YouTube Video API provides structured data for a YouTube video page.\n\nEndpoint: GET https://api.hasdata.com/scrape/youtube/video\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("device-type") {
				if err := validateEnumString("device-type", p_deviceTypeVar, []string{"desktop", "mobile"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("device-type") {
				params.Set("deviceType", p_deviceTypeVar)
			}
			if c.Flags().Changed("gl") {
				params.Set("gl", p_glVar)
			}
			if c.Flags().Changed("hl") {
				params.Set("hl", p_hlVar)
			}
			params.Set("v", p_vVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/youtube/video", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_deviceTypeVar, "device-type", "", "deviceType Device: Device type for the request. [allowed: desktop|mobile]")
	_ = cmd.RegisterFlagCompletionFunc("device-type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"desktop", "mobile"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_glVar, "gl", "", "gl Country: The two-letter country code for the country you want to limit the search to.")
	cmd.Flags().StringVar(&p_hlVar, "hl", "", "hl Language: The two-letter language code for the language you want to use for the search.")
	cmd.Flags().StringVar(&p_vVar, "v-param", "dQw4w9WgXcQ", "v Video ID: YouTube video ID (e.g. `dQw4w9WgXcQ`). (required)")
	_ = cmd.MarkFlagRequired("v-param")

	return cmd
}

func init() {
	RegisterAPICommand("youtube", "YouTube", newYoutubeVideoApiCmd())
}
