// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newRedfinPropertyCmd() *cobra.Command {
	var p_urlVar string

	cmd := &cobra.Command{
		Use:   "redfin-property",
		Short: "Redfin Property API  (5 credits/call)",
		Long:  "The Redfin Property API allows users to retrieve detailed information about a specific property using its URL. It provides details such as property features, price, and agent contacts.\n\nEndpoint: GET https://api.hasdata.com/scrape/redfin/property\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("url", p_urlVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/redfin/property", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_urlVar, "url", "https://www.redfin.com/IL/Chicago/1322-S-Prairie-Ave-60605/unit-1106/home/12694628", "url Property URL: The URL of the property on Redfin. Must be a valid Redfin property URL. (required)")
	_ = cmd.MarkFlagRequired("url")

	return cmd
}

func init() {
	RegisterAPICommand("redfin", "Redfin", newRedfinPropertyCmd())
}
