// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newYoutubeChannelApiCmd() *cobra.Command {
	var p_channelIdVar string
	var p_deviceTypeVar string
	var p_glVar string
	var p_hlVar string
	var p_paginationTokenVar string
	var p_tabVar string

	cmd := &cobra.Command{
		Use:   "youtube-channel-api",
		Short: "YouTube Channel API  (10 credits/call)",
		Long:  "The YouTube Channel API provides structured data from YouTube channel pages including channel info, videos, shorts, playlists, posts, streams, releases, podcasts, and more.\n\nEndpoint: GET https://api.hasdata.com/scrape/youtube/channel\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("device-type") {
				if err := validateEnumString("device-type", p_deviceTypeVar, []string{"desktop", "mobile"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("tab") {
				if err := validateEnumString("tab", p_tabVar, []string{"featured", "videos", "shorts", "streams", "playlists", "posts", "community", "podcasts", "releases", "about", "store"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("channelId", p_channelIdVar)
			if c.Flags().Changed("device-type") {
				params.Set("deviceType", p_deviceTypeVar)
			}
			if c.Flags().Changed("gl") {
				params.Set("gl", p_glVar)
			}
			if c.Flags().Changed("hl") {
				params.Set("hl", p_hlVar)
			}
			if c.Flags().Changed("pagination-token") {
				params.Set("paginationToken", p_paginationTokenVar)
			}
			if c.Flags().Changed("tab") {
				params.Set("tab", p_tabVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/youtube/channel", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_channelIdVar, "channel-id", "@PewDiePie", "channelId Channel ID: YouTube channel ID or handle (e.g. `UCxxxxxx` or `@PewDiePie`). (required)")
	_ = cmd.MarkFlagRequired("channel-id")
	cmd.Flags().StringVar(&p_deviceTypeVar, "device-type", "", "deviceType Device: Device type for the request. [allowed: desktop|mobile]")
	_ = cmd.RegisterFlagCompletionFunc("device-type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"desktop", "mobile"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_glVar, "gl", "", "gl Country: The two-letter country code for the country you want to limit the search to.")
	cmd.Flags().StringVar(&p_hlVar, "hl", "", "hl Language: The two-letter language code for the language you want to use for the search.")
	cmd.Flags().StringVar(&p_paginationTokenVar, "pagination-token", "", "paginationToken Pagination Token: Token returned in the previous response to fetch the next page of results.")
	cmd.Flags().StringVar(&p_tabVar, "tab", "", "tab Tab: Channel tab to scrape. Defaults to `featured` (Home tab). [allowed: featured|videos|shorts|streams|playlists|posts|community|podcasts|releases|about|store]")
	_ = cmd.RegisterFlagCompletionFunc("tab", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"featured", "videos", "shorts", "streams", "playlists", "posts", "community", "podcasts", "releases", "about", "store"}, cobra.ShellCompDirectiveNoFileComp
	})

	return cmd
}

func init() {
	RegisterAPICommand("youtube", "YouTube", newYoutubeChannelApiCmd())
}
