// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newBingSerpCmd() *cobra.Command {
	var p_ccVar string
	var p_countVar int
	var p_deviceTypeVar string
	var p_filtersVar string
	var p_firstVar int
	var p_latVar string
	var p_locationVar string
	var p_lonVar string
	var p_mktVar string
	var p_qVar string
	var p_safeVar string

	cmd := &cobra.Command{
		Use:   "bing-serp",
		Short: "Bing SERP API  (10 credits/call)",
		Long:  "The Bing SERP API provides real-time access to structured Bing search results, offering no blocks or CAPTCHAs.\n\nEndpoint: GET https://api.hasdata.com/scrape/bing/serp\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			if c.Flags().Changed("device-type") {
				if err := validateEnumString("device-type", p_deviceTypeVar, []string{"desktop", "mobile", "tablet"}); err != nil {
					return err
				}
			}
			if c.Flags().Changed("safe") {
				if err := validateEnumString("safe", p_safeVar, []string{"off", "moderate", "strict"}); err != nil {
					return err
				}
			}
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("cc") {
				params.Set("cc", p_ccVar)
			}
			if c.Flags().Changed("count") {
				params.Set("count", strconv.Itoa(p_countVar))
			}
			if c.Flags().Changed("device-type") {
				params.Set("deviceType", p_deviceTypeVar)
			}
			if c.Flags().Changed("filters") {
				params.Set("filters", p_filtersVar)
			}
			if c.Flags().Changed("first") {
				params.Set("first", strconv.Itoa(p_firstVar))
			}
			if c.Flags().Changed("lat") {
				params.Set("lat", p_latVar)
			}
			if c.Flags().Changed("location") {
				params.Set("location", p_locationVar)
			}
			if c.Flags().Changed("lon") {
				params.Set("lon", p_lonVar)
			}
			if c.Flags().Changed("mkt") {
				params.Set("mkt", p_mktVar)
			}
			params.Set("q", p_qVar)
			if c.Flags().Changed("safe") {
				params.Set("safe", p_safeVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/bing/serp", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_ccVar, "cc", "", "cc Country: The two-letter country code for the country to search from.")
	cmd.Flags().IntVar(&p_countVar, "count", 0, "count Number of Results: Number of results per page, ranging from 1 to 50.")
	cmd.Flags().StringVar(&p_deviceTypeVar, "device-type", "desktop", "deviceType Device: Specify the device type for the search. [allowed: desktop|mobile|tablet]")
	_ = cmd.RegisterFlagCompletionFunc("device-type", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"desktop", "mobile", "tablet"}, cobra.ShellCompDirectiveNoFileComp
	})
	cmd.Flags().StringVar(&p_filtersVar, "filters", "", "filters Additional Filtering: Allows applying various filters to narrow search results, including date-based options:\n\n  - `ex1:\"ez1\"` – past 24 hours\n  - `ex1:\"ez2\"` – past week\n  - `ex1:\"ez3\"` – past month\n\nFor complex filters, run a Bing search and copy the filters parameter from the URL.\n")
	cmd.Flags().IntVar(&p_firstVar, "first", 0, "first Result Offset: This parameter specifies the number of search results to skip and is used for implementing pagination. For example, a value of 1 (default) indicates the first page of results, 11 refers to the second page, and 21 to the third page.\n")
	cmd.Flags().StringVar(&p_latVar, "lat", "", "lat Latitude: GPS latitude for the search origin.")
	cmd.Flags().StringVar(&p_locationVar, "location", "Austin,Texas,United States", "location Location: Defines the search’s origin location. For realistic results, set location at the city level. If omitted, the proxy’s location may be used.")
	cmd.Flags().StringVar(&p_lonVar, "lon", "", "lon Longitude: GPS longitude for the search origin.")
	cmd.Flags().StringVar(&p_mktVar, "mkt", "", "mkt Market Code: The two-letter country code for the country to search from.")
	cmd.Flags().StringVar(&p_qVar, "q", "Coffee", "q Search Query: Specify the search term for which you want to scrape the SERP. (required)")
	_ = cmd.MarkFlagRequired("q")
	cmd.Flags().StringVar(&p_safeVar, "safe", "", "safe Adult Content Filtering: Adult Content Filtering option. [allowed: off|moderate|strict]")
	_ = cmd.RegisterFlagCompletionFunc("safe", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
		return []string{"off", "moderate", "strict"}, cobra.ShellCompDirectiveNoFileComp
	})

	return cmd
}

func init() {
	RegisterAPICommand("bing", "Bing", newBingSerpCmd())
}
