// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newGoogleEventsCmd() *cobra.Command {
	var p_pageTokenVar string

	cmd := &cobra.Command{
		Use:   "google-events",
		Short: "Google Events API  (10 credits/call)",
		Long:  "The Google Events API retrieves full details for a single Google event — venue, ticket sources, ratings, and description — given the `pageToken` of an event returned by the Google Search API.\n\nEndpoint: GET https://api.hasdata.com/scrape/google/events\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("pageToken", p_pageTokenVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/google/events", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_pageTokenVar, "page-token", "", "pageToken Page Token: Token identifying a single event, taken from the `pageToken` field of an `eventsResults` entry in a `google/serp` response. Expires a few minutes after it is minted. (required)")
	_ = cmd.MarkFlagRequired("page-token")

	return cmd
}

func init() {
	RegisterAPICommand("google_serp", "Google SERP", newGoogleEventsCmd())
}
