// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newTiktokCommentsCmd() *cobra.Command {
	var p_commentIdVar string
	var p_nextPageTokenVar string
	var p_videoIdVar string

	cmd := &cobra.Command{
		Use:   "tiktok-comments",
		Short: "TikTok Comments Scraper API  (10 credits/call)",
		Long:  "The TikTok Comments Scraper API returns the comments on a public TikTok video, or the replies to a specific comment. Each comment includes its text, like count, timestamp, reply count, and author (with links to the author's profile and posts). Results are paginated with a token.\n\nEndpoint: GET https://api.hasdata.com/scrape/tiktok/comments\nCost: 10 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("comment-id") {
				params.Set("commentId", p_commentIdVar)
			}
			if c.Flags().Changed("next-page-token") {
				params.Set("nextPageToken", p_nextPageTokenVar)
			}
			params.Set("videoId", p_videoIdVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/tiktok/comments", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_commentIdVar, "comment-id", "", "commentId Comment ID: When provided, returns the replies to this comment instead of the video's top-level comments.")
	cmd.Flags().StringVar(&p_nextPageTokenVar, "next-page-token", "", "nextPageToken Next Page Token: Defines the next page token. Use the `nextPageToken` value returned by the previous response. Omit it to fetch the first page.")
	cmd.Flags().StringVar(&p_videoIdVar, "video-id", "7667749432279977230", "videoId Video ID: The numeric id of the video (the number after `/video/` in a TikTok URL). (required)")
	_ = cmd.MarkFlagRequired("video-id")

	return cmd
}

func init() {
	RegisterAPICommand("social", "Social", newTiktokCommentsCmd())
}
