// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newYellowpagesPlaceCmd() *cobra.Command {
	var p_urlVar string

	cmd := &cobra.Command{
		Use:   "yellowpages-place",
		Short: "YellowPages Place API  (5 credits/call)",
		Long:  "The YellowPages Place API allows users to retrieve detailed information about a specific place using its YellowPages URL.\n\nEndpoint: GET https://api.hasdata.com/scrape/yellowpages/place\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			params.Set("url", p_urlVar)
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/yellowpages/place", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().StringVar(&p_urlVar, "url", "https://www.yellowpages.com/kings-county-ny/mip/aladdin-plumbing-corp-548289617", "url URL: The YellowPages URL of the place. (required)")
	_ = cmd.MarkFlagRequired("url")

	return cmd
}

func init() {
	RegisterAPICommand("business", "Business", newYellowpagesPlaceCmd())
}
