// Code generated by internal/gen. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"

	"github.com/spf13/cobra"
)

var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = url.Values{}
	_ = strconv.Itoa
)

func newGoogleAiModeCmd() *cobra.Command {
	var p_continuableVar bool
	var p_glVar string
	var p_hlVar string
	var p_locationVar string
	var p_qVar string
	var p_subsequentRequestTokenVar string
	var p_uuleVar string

	cmd := &cobra.Command{
		Use:   "google-ai-mode",
		Short: "Google AI Mode SERP API  (5 credits/call)",
		Long:  "The Google AI Mode SERP API captures Gemini-powered AI responses from Google Search. Get structured, conversational answers with links, summaries, and subtopic breakdowns—ideal for next-gen search and content tools.\n\nEndpoint: GET https://api.hasdata.com/scrape/google/ai-mode\nCost: 5 credits per call.",
		Args:  cobra.NoArgs,
		PreRunE: func(c *cobra.Command, _ []string) error {
			return nil
		},
		RunE: func(c *cobra.Command, _ []string) error {
			ctx := c.Context()
			cli, err := Client()
			if err != nil {
				return err
			}
			params := url.Values{}
			if c.Flags().Changed("continuable") {
				params.Set("continuable", strconv.FormatBool(p_continuableVar))
			}
			if c.Flags().Changed("gl") {
				params.Set("gl", p_glVar)
			}
			if c.Flags().Changed("hl") {
				params.Set("hl", p_hlVar)
			}
			if c.Flags().Changed("location") {
				params.Set("location", p_locationVar)
			}
			params.Set("q", p_qVar)
			if c.Flags().Changed("subsequent-request-token") {
				params.Set("subsequentRequestToken", p_subsequentRequestTokenVar)
			}
			if c.Flags().Changed("uule") {
				params.Set("uule", p_uuleVar)
			}
			resp, err := cli.Do(ctx, "GET", "https://api.hasdata.com/scrape/google/ai-mode", params, nil)
			if err != nil {
				return err
			}
			return WriteResponse(c, resp)
		},
	}
	cmd.Flags().BoolVar(&p_continuableVar, "continuable", false, "continuable Continuable: Whether to continue an existing AI Mode conversation.")
	cmd.Flags().StringVar(&p_glVar, "gl", "", "gl Country: The two-letter country code for the country you want to limit the search to.")
	cmd.Flags().StringVar(&p_hlVar, "hl", "", "hl Language: The two-letter language code for the language you want to use for the search.")
	cmd.Flags().StringVar(&p_locationVar, "location", "Austin,Texas,United States", "location Location: Google canonical location for the search.")
	cmd.Flags().StringVar(&p_qVar, "q", "Is coffee good for health?", "q Search Query: Specify the search term for which you want to scrape the SERP. (required)")
	_ = cmd.MarkFlagRequired("q")
	cmd.Flags().StringVar(&p_subsequentRequestTokenVar, "subsequent-request-token", "", "subsequentRequestToken Subsequent Request Token: Token used to continue a previous AI Mode request.")
	cmd.Flags().StringVar(&p_uuleVar, "uule", "", "uule Encoded Location: The encoded location parameter.")

	return cmd
}

func init() {
	RegisterAPICommand("google_serp", "Google SERP", newGoogleAiModeCmd())
}
